// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: oss.proto

// Protobuf Java Version: 3.25.5
package org.laokou.distributed.identifier.api;

/**
 * Protobuf type
 * {@code org.laokou.distributed.identifier.api.DistributedIdentifierBatchCmd}
 */
public final class DistributedIdentifierBatchCmd extends com.google.protobuf.GeneratedMessageV3 implements
		// @@protoc_insertion_point(message_implements:org.laokou.distributed.identifier.api.DistributedIdentifierBatchCmd)
		DistributedIdentifierBatchCmdOrBuilder {

	private static final long serialVersionUID = 0L;

	// Use DistributedIdentifierBatchCmd.newBuilder() to construct.
	private DistributedIdentifierBatchCmd(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
		super(builder);
	}

	private DistributedIdentifierBatchCmd() {
	}

	@java.lang.Override
	@SuppressWarnings({ "unused" })
	protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
		return new DistributedIdentifierBatchCmd();
	}

	public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
		return org.laokou.distributed.identifier.api.Oss.internal_static_org_laokou_distributed_identifier_api_DistributedIdentifierBatchCmd_descriptor;
	}

	@java.lang.Override
	protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
		return org.laokou.distributed.identifier.api.Oss.internal_static_org_laokou_distributed_identifier_api_DistributedIdentifierBatchCmd_fieldAccessorTable
			.ensureFieldAccessorsInitialized(org.laokou.distributed.identifier.api.DistributedIdentifierBatchCmd.class,
					org.laokou.distributed.identifier.api.DistributedIdentifierBatchCmd.Builder.class);
	}

	public static final int NUM_FIELD_NUMBER = 1;

	private int num_ = 0;

	/**
	 * <code>int32 num = 1;</code>
	 * @return The num.
	 */
	@java.lang.Override
	public int getNum() {
		return num_;
	}

	private byte memoizedIsInitialized = -1;

	@java.lang.Override
	public final boolean isInitialized() {
		byte isInitialized = memoizedIsInitialized;
		if (isInitialized == 1)
			return true;
		if (isInitialized == 0)
			return false;

		memoizedIsInitialized = 1;
		return true;
	}

	@java.lang.Override
	public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
		if (num_ != 0) {
			output.writeInt32(1, num_);
		}
		getUnknownFields().writeTo(output);
	}

	@java.lang.Override
	public int getSerializedSize() {
		int size = memoizedSize;
		if (size != -1)
			return size;

		size = 0;
		if (num_ != 0) {
			size += com.google.protobuf.CodedOutputStream.computeInt32Size(1, num_);
		}
		size += getUnknownFields().getSerializedSize();
		memoizedSize = size;
		return size;
	}

	@java.lang.Override
	public boolean equals(final java.lang.Object obj) {
		if (obj == this) {
			return true;
		}
		if (!(obj instanceof org.laokou.distributed.identifier.api.DistributedIdentifierBatchCmd)) {
			return super.equals(obj);
		}
		org.laokou.distributed.identifier.api.DistributedIdentifierBatchCmd other = (org.laokou.distributed.identifier.api.DistributedIdentifierBatchCmd) obj;

		if (getNum() != other.getNum())
			return false;
		if (!getUnknownFields().equals(other.getUnknownFields()))
			return false;
		return true;
	}

	@java.lang.Override
	public int hashCode() {
		if (memoizedHashCode != 0) {
			return memoizedHashCode;
		}
		int hash = 41;
		hash = (19 * hash) + getDescriptor().hashCode();
		hash = (37 * hash) + NUM_FIELD_NUMBER;
		hash = (53 * hash) + getNum();
		hash = (29 * hash) + getUnknownFields().hashCode();
		memoizedHashCode = hash;
		return hash;
	}

	public static org.laokou.distributed.identifier.api.DistributedIdentifierBatchCmd parseFrom(
			java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data);
	}

	public static org.laokou.distributed.identifier.api.DistributedIdentifierBatchCmd parseFrom(
			java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data, extensionRegistry);
	}

	public static org.laokou.distributed.identifier.api.DistributedIdentifierBatchCmd parseFrom(
			com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data);
	}

	public static org.laokou.distributed.identifier.api.DistributedIdentifierBatchCmd parseFrom(
			com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data, extensionRegistry);
	}

	public static org.laokou.distributed.identifier.api.DistributedIdentifierBatchCmd parseFrom(byte[] data)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data);
	}

	public static org.laokou.distributed.identifier.api.DistributedIdentifierBatchCmd parseFrom(byte[] data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data, extensionRegistry);
	}

	public static org.laokou.distributed.identifier.api.DistributedIdentifierBatchCmd parseFrom(
			java.io.InputStream input) throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
	}

	public static org.laokou.distributed.identifier.api.DistributedIdentifierBatchCmd parseFrom(
			java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
	}

	public static org.laokou.distributed.identifier.api.DistributedIdentifierBatchCmd parseDelimitedFrom(
			java.io.InputStream input) throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
	}

	public static org.laokou.distributed.identifier.api.DistributedIdentifierBatchCmd parseDelimitedFrom(
			java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
	}

	public static org.laokou.distributed.identifier.api.DistributedIdentifierBatchCmd parseFrom(
			com.google.protobuf.CodedInputStream input) throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
	}

	public static org.laokou.distributed.identifier.api.DistributedIdentifierBatchCmd parseFrom(
			com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
	}

	@java.lang.Override
	public Builder newBuilderForType() {
		return newBuilder();
	}

	public static Builder newBuilder() {
		return DEFAULT_INSTANCE.toBuilder();
	}

	public static Builder newBuilder(org.laokou.distributed.identifier.api.DistributedIdentifierBatchCmd prototype) {
		return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
	}

	@java.lang.Override
	public Builder toBuilder() {
		return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
	}

	@java.lang.Override
	protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
		Builder builder = new Builder(parent);
		return builder;
	}

	/**
	 * Protobuf type
	 * {@code org.laokou.distributed.identifier.api.DistributedIdentifierBatchCmd}
	 */
	public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
			// @@protoc_insertion_point(builder_implements:org.laokou.distributed.identifier.api.DistributedIdentifierBatchCmd)
			org.laokou.distributed.identifier.api.DistributedIdentifierBatchCmdOrBuilder {

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return org.laokou.distributed.identifier.api.Oss.internal_static_org_laokou_distributed_identifier_api_DistributedIdentifierBatchCmd_descriptor;
		}

		@java.lang.Override
		protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
			return org.laokou.distributed.identifier.api.Oss.internal_static_org_laokou_distributed_identifier_api_DistributedIdentifierBatchCmd_fieldAccessorTable
				.ensureFieldAccessorsInitialized(
						org.laokou.distributed.identifier.api.DistributedIdentifierBatchCmd.class,
						org.laokou.distributed.identifier.api.DistributedIdentifierBatchCmd.Builder.class);
		}

		// Construct using
		// org.laokou.distributed.identifier.api.DistributedIdentifierBatchCmd.newBuilder()
		private Builder() {

		}

		private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
			super(parent);

		}

		@java.lang.Override
		public Builder clear() {
			super.clear();
			bitField0_ = 0;
			num_ = 0;
			return this;
		}

		@java.lang.Override
		public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
			return org.laokou.distributed.identifier.api.Oss.internal_static_org_laokou_distributed_identifier_api_DistributedIdentifierBatchCmd_descriptor;
		}

		@java.lang.Override
		public org.laokou.distributed.identifier.api.DistributedIdentifierBatchCmd getDefaultInstanceForType() {
			return org.laokou.distributed.identifier.api.DistributedIdentifierBatchCmd.getDefaultInstance();
		}

		@java.lang.Override
		public org.laokou.distributed.identifier.api.DistributedIdentifierBatchCmd build() {
			org.laokou.distributed.identifier.api.DistributedIdentifierBatchCmd result = buildPartial();
			if (!result.isInitialized()) {
				throw newUninitializedMessageException(result);
			}
			return result;
		}

		@java.lang.Override
		public org.laokou.distributed.identifier.api.DistributedIdentifierBatchCmd buildPartial() {
			org.laokou.distributed.identifier.api.DistributedIdentifierBatchCmd result = new org.laokou.distributed.identifier.api.DistributedIdentifierBatchCmd(
					this);
			if (bitField0_ != 0) {
				buildPartial0(result);
			}
			onBuilt();
			return result;
		}

		private void buildPartial0(org.laokou.distributed.identifier.api.DistributedIdentifierBatchCmd result) {
			int from_bitField0_ = bitField0_;
			if (((from_bitField0_ & 0x00000001) != 0)) {
				result.num_ = num_;
			}
		}

		@java.lang.Override
		public Builder clone() {
			return super.clone();
		}

		@java.lang.Override
		public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
			return super.setField(field, value);
		}

		@java.lang.Override
		public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
			return super.clearField(field);
		}

		@java.lang.Override
		public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
			return super.clearOneof(oneof);
		}

		@java.lang.Override
		public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index,
				java.lang.Object value) {
			return super.setRepeatedField(field, index, value);
		}

		@java.lang.Override
		public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
			return super.addRepeatedField(field, value);
		}

		@java.lang.Override
		public Builder mergeFrom(com.google.protobuf.Message other) {
			if (other instanceof org.laokou.distributed.identifier.api.DistributedIdentifierBatchCmd) {
				return mergeFrom((org.laokou.distributed.identifier.api.DistributedIdentifierBatchCmd) other);
			}
			else {
				super.mergeFrom(other);
				return this;
			}
		}

		public Builder mergeFrom(org.laokou.distributed.identifier.api.DistributedIdentifierBatchCmd other) {
			if (other == org.laokou.distributed.identifier.api.DistributedIdentifierBatchCmd.getDefaultInstance())
				return this;
			if (other.getNum() != 0) {
				setNum(other.getNum());
			}
			this.mergeUnknownFields(other.getUnknownFields());
			onChanged();
			return this;
		}

		@java.lang.Override
		public final boolean isInitialized() {
			return true;
		}

		@java.lang.Override
		public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			if (extensionRegistry == null) {
				throw new java.lang.NullPointerException();
			}
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
						case 0:
							done = true;
							break;
						case 8: {
							num_ = input.readInt32();
							bitField0_ |= 0x00000001;
							break;
						} // case 8
						default: {
							if (!super.parseUnknownField(input, extensionRegistry, tag)) {
								done = true; // was an endgroup tag
							}
							break;
						} // default:
					} // switch (tag)
				} // while (!done)
			}
			catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.unwrapIOException();
			}
			finally {
				onChanged();
			} // finally
			return this;
		}

		private int bitField0_;

		private int num_;

		/**
		 * <code>int32 num = 1;</code>
		 * @return The num.
		 */
		@java.lang.Override
		public int getNum() {
			return num_;
		}

		/**
		 * <code>int32 num = 1;</code>
		 * @param value The num to set.
		 * @return This builder for chaining.
		 */
		public Builder setNum(int value) {

			num_ = value;
			bitField0_ |= 0x00000001;
			onChanged();
			return this;
		}

		/**
		 * <code>int32 num = 1;</code>
		 * @return This builder for chaining.
		 */
		public Builder clearNum() {
			bitField0_ = (bitField0_ & ~0x00000001);
			num_ = 0;
			onChanged();
			return this;
		}

		@java.lang.Override
		public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
			return super.setUnknownFields(unknownFields);
		}

		@java.lang.Override
		public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
			return super.mergeUnknownFields(unknownFields);
		}

		// @@protoc_insertion_point(builder_scope:org.laokou.distributed.identifier.api.DistributedIdentifierBatchCmd)

	}

	// @@protoc_insertion_point(class_scope:org.laokou.distributed.identifier.api.DistributedIdentifierBatchCmd)
	private static final org.laokou.distributed.identifier.api.DistributedIdentifierBatchCmd DEFAULT_INSTANCE;
	static {
		DEFAULT_INSTANCE = new org.laokou.distributed.identifier.api.DistributedIdentifierBatchCmd();
	}

	public static org.laokou.distributed.identifier.api.DistributedIdentifierBatchCmd getDefaultInstance() {
		return DEFAULT_INSTANCE;
	}

	private static final com.google.protobuf.Parser<DistributedIdentifierBatchCmd> PARSER = new com.google.protobuf.AbstractParser<DistributedIdentifierBatchCmd>() {
		@java.lang.Override
		public DistributedIdentifierBatchCmd parsePartialFrom(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			Builder builder = newBuilder();
			try {
				builder.mergeFrom(input, extensionRegistry);
			}
			catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(builder.buildPartial());
			}
			catch (com.google.protobuf.UninitializedMessageException e) {
				throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
			}
			catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(e)
					.setUnfinishedMessage(builder.buildPartial());
			}
			return builder.buildPartial();
		}
	};

	public static com.google.protobuf.Parser<DistributedIdentifierBatchCmd> parser() {
		return PARSER;
	}

	@java.lang.Override
	public com.google.protobuf.Parser<DistributedIdentifierBatchCmd> getParserForType() {
		return PARSER;
	}

	@java.lang.Override
	public org.laokou.distributed.identifier.api.DistributedIdentifierBatchCmd getDefaultInstanceForType() {
		return DEFAULT_INSTANCE;
	}

}
