// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: oss.proto

// Protobuf Java Version: 3.25.5
package org.laokou.distributed.identifier.api;

/**
 * Protobuf type {@code org.laokou.distributed.identifier.api.DistributedIdentifierResult}
 */
public final class DistributedIdentifierResult extends com.google.protobuf.GeneratedMessageV3 implements
		// @@protoc_insertion_point(message_implements:org.laokou.distributed.identifier.api.DistributedIdentifierResult)
		DistributedIdentifierResultOrBuilder {

	private static final long serialVersionUID = 0L;

	// Use DistributedIdentifierResult.newBuilder() to construct.
	private DistributedIdentifierResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
		super(builder);
	}

	private DistributedIdentifierResult() {
		code_ = "";
		msg_ = "";
	}

	@java.lang.Override
	@SuppressWarnings({ "unused" })
	protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
		return new DistributedIdentifierResult();
	}

	public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
		return org.laokou.distributed.identifier.api.Oss.internal_static_org_laokou_distributed_identifier_api_DistributedIdentifierResult_descriptor;
	}

	@java.lang.Override
	protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
		return org.laokou.distributed.identifier.api.Oss.internal_static_org_laokou_distributed_identifier_api_DistributedIdentifierResult_fieldAccessorTable
			.ensureFieldAccessorsInitialized(org.laokou.distributed.identifier.api.DistributedIdentifierResult.class,
					org.laokou.distributed.identifier.api.DistributedIdentifierResult.Builder.class);
	}

	public static final int CODE_FIELD_NUMBER = 1;

	@SuppressWarnings("serial")
	private volatile java.lang.Object code_ = "";

	/**
	 * <code>string code = 1;</code>
	 * @return The code.
	 */
	@java.lang.Override
	public java.lang.String getCode() {
		java.lang.Object ref = code_;
		if (ref instanceof java.lang.String) {
			return (java.lang.String) ref;
		}
		else {
			com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
			java.lang.String s = bs.toStringUtf8();
			code_ = s;
			return s;
		}
	}

	/**
	 * <code>string code = 1;</code>
	 * @return The bytes for code.
	 */
	@java.lang.Override
	public com.google.protobuf.ByteString getCodeBytes() {
		java.lang.Object ref = code_;
		if (ref instanceof java.lang.String) {
			com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
			code_ = b;
			return b;
		}
		else {
			return (com.google.protobuf.ByteString) ref;
		}
	}

	public static final int MSG_FIELD_NUMBER = 2;

	@SuppressWarnings("serial")
	private volatile java.lang.Object msg_ = "";

	/**
	 * <code>string msg = 2;</code>
	 * @return The msg.
	 */
	@java.lang.Override
	public java.lang.String getMsg() {
		java.lang.Object ref = msg_;
		if (ref instanceof java.lang.String) {
			return (java.lang.String) ref;
		}
		else {
			com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
			java.lang.String s = bs.toStringUtf8();
			msg_ = s;
			return s;
		}
	}

	/**
	 * <code>string msg = 2;</code>
	 * @return The bytes for msg.
	 */
	@java.lang.Override
	public com.google.protobuf.ByteString getMsgBytes() {
		java.lang.Object ref = msg_;
		if (ref instanceof java.lang.String) {
			com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
			msg_ = b;
			return b;
		}
		else {
			return (com.google.protobuf.ByteString) ref;
		}
	}

	public static final int DATA_FIELD_NUMBER = 3;

	private long data_ = 0L;

	/**
	 * <code>int64 data = 3;</code>
	 * @return The data.
	 */
	@java.lang.Override
	public long getData() {
		return data_;
	}

	private byte memoizedIsInitialized = -1;

	@java.lang.Override
	public final boolean isInitialized() {
		byte isInitialized = memoizedIsInitialized;
		if (isInitialized == 1)
			return true;
		if (isInitialized == 0)
			return false;

		memoizedIsInitialized = 1;
		return true;
	}

	@java.lang.Override
	public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
		if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(code_)) {
			com.google.protobuf.GeneratedMessageV3.writeString(output, 1, code_);
		}
		if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msg_)) {
			com.google.protobuf.GeneratedMessageV3.writeString(output, 2, msg_);
		}
		if (data_ != 0L) {
			output.writeInt64(3, data_);
		}
		getUnknownFields().writeTo(output);
	}

	@java.lang.Override
	public int getSerializedSize() {
		int size = memoizedSize;
		if (size != -1)
			return size;

		size = 0;
		if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(code_)) {
			size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, code_);
		}
		if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msg_)) {
			size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, msg_);
		}
		if (data_ != 0L) {
			size += com.google.protobuf.CodedOutputStream.computeInt64Size(3, data_);
		}
		size += getUnknownFields().getSerializedSize();
		memoizedSize = size;
		return size;
	}

	@java.lang.Override
	public boolean equals(final java.lang.Object obj) {
		if (obj == this) {
			return true;
		}
		if (!(obj instanceof org.laokou.distributed.identifier.api.DistributedIdentifierResult)) {
			return super.equals(obj);
		}
		org.laokou.distributed.identifier.api.DistributedIdentifierResult other = (org.laokou.distributed.identifier.api.DistributedIdentifierResult) obj;

		if (!getCode().equals(other.getCode()))
			return false;
		if (!getMsg().equals(other.getMsg()))
			return false;
		if (getData() != other.getData())
			return false;
		if (!getUnknownFields().equals(other.getUnknownFields()))
			return false;
		return true;
	}

	@java.lang.Override
	public int hashCode() {
		if (memoizedHashCode != 0) {
			return memoizedHashCode;
		}
		int hash = 41;
		hash = (19 * hash) + getDescriptor().hashCode();
		hash = (37 * hash) + CODE_FIELD_NUMBER;
		hash = (53 * hash) + getCode().hashCode();
		hash = (37 * hash) + MSG_FIELD_NUMBER;
		hash = (53 * hash) + getMsg().hashCode();
		hash = (37 * hash) + DATA_FIELD_NUMBER;
		hash = (53 * hash) + com.google.protobuf.Internal.hashLong(getData());
		hash = (29 * hash) + getUnknownFields().hashCode();
		memoizedHashCode = hash;
		return hash;
	}

	public static org.laokou.distributed.identifier.api.DistributedIdentifierResult parseFrom(java.nio.ByteBuffer data)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data);
	}

	public static org.laokou.distributed.identifier.api.DistributedIdentifierResult parseFrom(java.nio.ByteBuffer data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data, extensionRegistry);
	}

	public static org.laokou.distributed.identifier.api.DistributedIdentifierResult parseFrom(
			com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data);
	}

	public static org.laokou.distributed.identifier.api.DistributedIdentifierResult parseFrom(
			com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data, extensionRegistry);
	}

	public static org.laokou.distributed.identifier.api.DistributedIdentifierResult parseFrom(byte[] data)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data);
	}

	public static org.laokou.distributed.identifier.api.DistributedIdentifierResult parseFrom(byte[] data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data, extensionRegistry);
	}

	public static org.laokou.distributed.identifier.api.DistributedIdentifierResult parseFrom(java.io.InputStream input)
			throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
	}

	public static org.laokou.distributed.identifier.api.DistributedIdentifierResult parseFrom(java.io.InputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
	}

	public static org.laokou.distributed.identifier.api.DistributedIdentifierResult parseDelimitedFrom(
			java.io.InputStream input) throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
	}

	public static org.laokou.distributed.identifier.api.DistributedIdentifierResult parseDelimitedFrom(
			java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
	}

	public static org.laokou.distributed.identifier.api.DistributedIdentifierResult parseFrom(
			com.google.protobuf.CodedInputStream input) throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
	}

	public static org.laokou.distributed.identifier.api.DistributedIdentifierResult parseFrom(
			com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
	}

	@java.lang.Override
	public Builder newBuilderForType() {
		return newBuilder();
	}

	public static Builder newBuilder() {
		return DEFAULT_INSTANCE.toBuilder();
	}

	public static Builder newBuilder(org.laokou.distributed.identifier.api.DistributedIdentifierResult prototype) {
		return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
	}

	@java.lang.Override
	public Builder toBuilder() {
		return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
	}

	@java.lang.Override
	protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
		Builder builder = new Builder(parent);
		return builder;
	}

	/**
	 * Protobuf type
	 * {@code org.laokou.distributed.identifier.api.DistributedIdentifierResult}
	 */
	public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
			// @@protoc_insertion_point(builder_implements:org.laokou.distributed.identifier.api.DistributedIdentifierResult)
			org.laokou.distributed.identifier.api.DistributedIdentifierResultOrBuilder {

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return org.laokou.distributed.identifier.api.Oss.internal_static_org_laokou_distributed_identifier_api_DistributedIdentifierResult_descriptor;
		}

		@java.lang.Override
		protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
			return org.laokou.distributed.identifier.api.Oss.internal_static_org_laokou_distributed_identifier_api_DistributedIdentifierResult_fieldAccessorTable
				.ensureFieldAccessorsInitialized(
						org.laokou.distributed.identifier.api.DistributedIdentifierResult.class,
						org.laokou.distributed.identifier.api.DistributedIdentifierResult.Builder.class);
		}

		// Construct using
		// org.laokou.distributed.identifier.api.DistributedIdentifierResult.newBuilder()
		private Builder() {

		}

		private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
			super(parent);

		}

		@java.lang.Override
		public Builder clear() {
			super.clear();
			bitField0_ = 0;
			code_ = "";
			msg_ = "";
			data_ = 0L;
			return this;
		}

		@java.lang.Override
		public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
			return org.laokou.distributed.identifier.api.Oss.internal_static_org_laokou_distributed_identifier_api_DistributedIdentifierResult_descriptor;
		}

		@java.lang.Override
		public org.laokou.distributed.identifier.api.DistributedIdentifierResult getDefaultInstanceForType() {
			return org.laokou.distributed.identifier.api.DistributedIdentifierResult.getDefaultInstance();
		}

		@java.lang.Override
		public org.laokou.distributed.identifier.api.DistributedIdentifierResult build() {
			org.laokou.distributed.identifier.api.DistributedIdentifierResult result = buildPartial();
			if (!result.isInitialized()) {
				throw newUninitializedMessageException(result);
			}
			return result;
		}

		@java.lang.Override
		public org.laokou.distributed.identifier.api.DistributedIdentifierResult buildPartial() {
			org.laokou.distributed.identifier.api.DistributedIdentifierResult result = new org.laokou.distributed.identifier.api.DistributedIdentifierResult(
					this);
			if (bitField0_ != 0) {
				buildPartial0(result);
			}
			onBuilt();
			return result;
		}

		private void buildPartial0(org.laokou.distributed.identifier.api.DistributedIdentifierResult result) {
			int from_bitField0_ = bitField0_;
			if (((from_bitField0_ & 0x00000001) != 0)) {
				result.code_ = code_;
			}
			if (((from_bitField0_ & 0x00000002) != 0)) {
				result.msg_ = msg_;
			}
			if (((from_bitField0_ & 0x00000004) != 0)) {
				result.data_ = data_;
			}
		}

		@java.lang.Override
		public Builder clone() {
			return super.clone();
		}

		@java.lang.Override
		public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
			return super.setField(field, value);
		}

		@java.lang.Override
		public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
			return super.clearField(field);
		}

		@java.lang.Override
		public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
			return super.clearOneof(oneof);
		}

		@java.lang.Override
		public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index,
				java.lang.Object value) {
			return super.setRepeatedField(field, index, value);
		}

		@java.lang.Override
		public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
			return super.addRepeatedField(field, value);
		}

		@java.lang.Override
		public Builder mergeFrom(com.google.protobuf.Message other) {
			if (other instanceof org.laokou.distributed.identifier.api.DistributedIdentifierResult) {
				return mergeFrom((org.laokou.distributed.identifier.api.DistributedIdentifierResult) other);
			}
			else {
				super.mergeFrom(other);
				return this;
			}
		}

		public Builder mergeFrom(org.laokou.distributed.identifier.api.DistributedIdentifierResult other) {
			if (other == org.laokou.distributed.identifier.api.DistributedIdentifierResult.getDefaultInstance())
				return this;
			if (!other.getCode().isEmpty()) {
				code_ = other.code_;
				bitField0_ |= 0x00000001;
				onChanged();
			}
			if (!other.getMsg().isEmpty()) {
				msg_ = other.msg_;
				bitField0_ |= 0x00000002;
				onChanged();
			}
			if (other.getData() != 0L) {
				setData(other.getData());
			}
			this.mergeUnknownFields(other.getUnknownFields());
			onChanged();
			return this;
		}

		@java.lang.Override
		public final boolean isInitialized() {
			return true;
		}

		@java.lang.Override
		public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			if (extensionRegistry == null) {
				throw new java.lang.NullPointerException();
			}
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
						case 0:
							done = true;
							break;
						case 10: {
							code_ = input.readStringRequireUtf8();
							bitField0_ |= 0x00000001;
							break;
						} // case 10
						case 18: {
							msg_ = input.readStringRequireUtf8();
							bitField0_ |= 0x00000002;
							break;
						} // case 18
						case 24: {
							data_ = input.readInt64();
							bitField0_ |= 0x00000004;
							break;
						} // case 24
						default: {
							if (!super.parseUnknownField(input, extensionRegistry, tag)) {
								done = true; // was an endgroup tag
							}
							break;
						} // default:
					} // switch (tag)
				} // while (!done)
			}
			catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.unwrapIOException();
			}
			finally {
				onChanged();
			} // finally
			return this;
		}

		private int bitField0_;

		private java.lang.Object code_ = "";

		/**
		 * <code>string code = 1;</code>
		 * @return The code.
		 */
		public java.lang.String getCode() {
			java.lang.Object ref = code_;
			if (!(ref instanceof java.lang.String)) {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				code_ = s;
				return s;
			}
			else {
				return (java.lang.String) ref;
			}
		}

		/**
		 * <code>string code = 1;</code>
		 * @return The bytes for code.
		 */
		public com.google.protobuf.ByteString getCodeBytes() {
			java.lang.Object ref = code_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				code_ = b;
				return b;
			}
			else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		/**
		 * <code>string code = 1;</code>
		 * @param value The code to set.
		 * @return This builder for chaining.
		 */
		public Builder setCode(java.lang.String value) {
			if (value == null) {
				throw new NullPointerException();
			}
			code_ = value;
			bitField0_ |= 0x00000001;
			onChanged();
			return this;
		}

		/**
		 * <code>string code = 1;</code>
		 * @return This builder for chaining.
		 */
		public Builder clearCode() {
			code_ = getDefaultInstance().getCode();
			bitField0_ = (bitField0_ & ~0x00000001);
			onChanged();
			return this;
		}

		/**
		 * <code>string code = 1;</code>
		 * @param value The bytes for code to set.
		 * @return This builder for chaining.
		 */
		public Builder setCodeBytes(com.google.protobuf.ByteString value) {
			if (value == null) {
				throw new NullPointerException();
			}
			checkByteStringIsUtf8(value);
			code_ = value;
			bitField0_ |= 0x00000001;
			onChanged();
			return this;
		}

		private java.lang.Object msg_ = "";

		/**
		 * <code>string msg = 2;</code>
		 * @return The msg.
		 */
		public java.lang.String getMsg() {
			java.lang.Object ref = msg_;
			if (!(ref instanceof java.lang.String)) {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				msg_ = s;
				return s;
			}
			else {
				return (java.lang.String) ref;
			}
		}

		/**
		 * <code>string msg = 2;</code>
		 * @return The bytes for msg.
		 */
		public com.google.protobuf.ByteString getMsgBytes() {
			java.lang.Object ref = msg_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				msg_ = b;
				return b;
			}
			else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		/**
		 * <code>string msg = 2;</code>
		 * @param value The msg to set.
		 * @return This builder for chaining.
		 */
		public Builder setMsg(java.lang.String value) {
			if (value == null) {
				throw new NullPointerException();
			}
			msg_ = value;
			bitField0_ |= 0x00000002;
			onChanged();
			return this;
		}

		/**
		 * <code>string msg = 2;</code>
		 * @return This builder for chaining.
		 */
		public Builder clearMsg() {
			msg_ = getDefaultInstance().getMsg();
			bitField0_ = (bitField0_ & ~0x00000002);
			onChanged();
			return this;
		}

		/**
		 * <code>string msg = 2;</code>
		 * @param value The bytes for msg to set.
		 * @return This builder for chaining.
		 */
		public Builder setMsgBytes(com.google.protobuf.ByteString value) {
			if (value == null) {
				throw new NullPointerException();
			}
			checkByteStringIsUtf8(value);
			msg_ = value;
			bitField0_ |= 0x00000002;
			onChanged();
			return this;
		}

		private long data_;

		/**
		 * <code>int64 data = 3;</code>
		 * @return The data.
		 */
		@java.lang.Override
		public long getData() {
			return data_;
		}

		/**
		 * <code>int64 data = 3;</code>
		 * @param value The data to set.
		 * @return This builder for chaining.
		 */
		public Builder setData(long value) {

			data_ = value;
			bitField0_ |= 0x00000004;
			onChanged();
			return this;
		}

		/**
		 * <code>int64 data = 3;</code>
		 * @return This builder for chaining.
		 */
		public Builder clearData() {
			bitField0_ = (bitField0_ & ~0x00000004);
			data_ = 0L;
			onChanged();
			return this;
		}

		@java.lang.Override
		public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
			return super.setUnknownFields(unknownFields);
		}

		@java.lang.Override
		public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
			return super.mergeUnknownFields(unknownFields);
		}

		// @@protoc_insertion_point(builder_scope:org.laokou.distributed.identifier.api.DistributedIdentifierResult)

	}

	// @@protoc_insertion_point(class_scope:org.laokou.distributed.identifier.api.DistributedIdentifierResult)
	private static final org.laokou.distributed.identifier.api.DistributedIdentifierResult DEFAULT_INSTANCE;
	static {
		DEFAULT_INSTANCE = new org.laokou.distributed.identifier.api.DistributedIdentifierResult();
	}

	public static org.laokou.distributed.identifier.api.DistributedIdentifierResult getDefaultInstance() {
		return DEFAULT_INSTANCE;
	}

	private static final com.google.protobuf.Parser<DistributedIdentifierResult> PARSER = new com.google.protobuf.AbstractParser<DistributedIdentifierResult>() {
		@java.lang.Override
		public DistributedIdentifierResult parsePartialFrom(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			Builder builder = newBuilder();
			try {
				builder.mergeFrom(input, extensionRegistry);
			}
			catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(builder.buildPartial());
			}
			catch (com.google.protobuf.UninitializedMessageException e) {
				throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
			}
			catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(e)
					.setUnfinishedMessage(builder.buildPartial());
			}
			return builder.buildPartial();
		}
	};

	public static com.google.protobuf.Parser<DistributedIdentifierResult> parser() {
		return PARSER;
	}

	@java.lang.Override
	public com.google.protobuf.Parser<DistributedIdentifierResult> getParserForType() {
		return PARSER;
	}

	@java.lang.Override
	public org.laokou.distributed.identifier.api.DistributedIdentifierResult getDefaultInstanceForType() {
		return DEFAULT_INSTANCE;
	}

}
