// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: oss.proto

// Protobuf Java Version: 3.25.5
package org.laokou.distributed.identifier.api;

public interface DistributedIdentifierBatchResultOrBuilder extends
		// @@protoc_insertion_point(interface_extends:org.laokou.distributed.identifier.api.DistributedIdentifierBatchResult)
		com.google.protobuf.MessageOrBuilder {

	/**
	 * <code>string code = 1;</code>
	 * @return The code.
	 */
	java.lang.String getCode();

	/**
	 * <code>string code = 1;</code>
	 * @return The bytes for code.
	 */
	com.google.protobuf.ByteString getCodeBytes();

	/**
	 * <code>string msg = 2;</code>
	 * @return The msg.
	 */
	java.lang.String getMsg();

	/**
	 * <code>string msg = 2;</code>
	 * @return The bytes for msg.
	 */
	com.google.protobuf.ByteString getMsgBytes();

	/**
	 * <code>repeated int64 data = 3;</code>
	 * @return A list containing the data.
	 */
	java.util.List<java.lang.Long> getDataList();

	/**
	 * <code>repeated int64 data = 3;</code>
	 * @return The count of data.
	 */
	int getDataCount();

	/**
	 * <code>repeated int64 data = 3;</code>
	 * @param index The index of the element to return.
	 * @return The data at the given index.
	 */
	long getData(int index);

}
