// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: oss.proto

// Protobuf Java Version: 3.25.5
package org.laokou.distributed.identifier.api;

public interface DistributedIdentifierBatchCmdOrBuilder extends
		// @@protoc_insertion_point(interface_extends:org.laokou.distributed.identifier.api.DistributedIdentifierBatchCmd)
		com.google.protobuf.MessageOrBuilder {

	/**
	 * <code>int32 num = 1;</code>
	 * @return The num.
	 */
	int getNum();

}
