// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: oss.proto

// Protobuf Java Version: 3.25.5
package org.laokou.distributed.identifier.api;

public interface DistributedIdentifierCmdOrBuilder extends
		// @@protoc_insertion_point(interface_extends:org.laokou.distributed.identifier.api.DistributedIdentifierCmd)
		com.google.protobuf.MessageOrBuilder {

}
