// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: oss.proto

// Protobuf Java Version: 3.25.5
package org.laokou.distributed.identifier.api;

public final class Oss {

	private Oss() {
	}

	public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {
	}

	public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
		registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
	}

	static final com.google.protobuf.Descriptors.Descriptor internal_static_org_laokou_distributed_identifier_api_DistributedIdentifierCmd_descriptor;
	static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_org_laokou_distributed_identifier_api_DistributedIdentifierCmd_fieldAccessorTable;
	static final com.google.protobuf.Descriptors.Descriptor internal_static_org_laokou_distributed_identifier_api_DistributedIdentifierResult_descriptor;
	static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_org_laokou_distributed_identifier_api_DistributedIdentifierResult_fieldAccessorTable;
	static final com.google.protobuf.Descriptors.Descriptor internal_static_org_laokou_distributed_identifier_api_DistributedIdentifierBatchCmd_descriptor;
	static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_org_laokou_distributed_identifier_api_DistributedIdentifierBatchCmd_fieldAccessorTable;
	static final com.google.protobuf.Descriptors.Descriptor internal_static_org_laokou_distributed_identifier_api_DistributedIdentifierBatchResult_descriptor;
	static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_org_laokou_distributed_identifier_api_DistributedIdentifierBatchResult_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
		return descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
	static {
		java.lang.String[] descriptorData = { "\n\toss.proto\022%org.laokou.distributed.iden"
				+ "tifier.api\"\032\n\030DistributedIdentifierCmd\"F"
				+ "\n\033DistributedIdentifierResult\022\014\n\004code\030\001 "
				+ "\001(\t\022\013\n\003msg\030\002 \001(\t\022\014\n\004data\030\003 \001(\003\",\n\035Distri"
				+ "butedIdentifierBatchCmd\022\013\n\003num\030\001 \001(\005\"K\n "
				+ "DistributedIdentifierBatchResult\022\014\n\004code"
				+ "\030\001 \001(\t\022\013\n\003msg\030\002 \001(\t\022\014\n\004data\030\003 \003(\0032\344\002\n\035Di"
				+ "stributedIdentifierServiceI\022\230\001\n\021generate"
				+ "Snowflake\022?.org.laokou.distributed.ident" + "ifier.api.DistributedIdentifierCmd\032B.org"
				+ ".laokou.distributed.identifier.api.Distr" + "ibutedIdentifierResult\022\247\001\n\026generateSnowf"
				+ "lakeBatch\022D.org.laokou.distributed.ident" + "ifier.api.DistributedIdentifierBatchCmd\032"
				+ "G.org.laokou.distributed.identifier.api." + "DistributedIdentifierBatchResultB\002P\001b\006pr"
				+ "oto3" };
		descriptor = com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
				new com.google.protobuf.Descriptors.FileDescriptor[] {});
		internal_static_org_laokou_distributed_identifier_api_DistributedIdentifierCmd_descriptor = getDescriptor()
			.getMessageTypes()
			.get(0);
		internal_static_org_laokou_distributed_identifier_api_DistributedIdentifierCmd_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
				internal_static_org_laokou_distributed_identifier_api_DistributedIdentifierCmd_descriptor,
				new java.lang.String[] {});
		internal_static_org_laokou_distributed_identifier_api_DistributedIdentifierResult_descriptor = getDescriptor()
			.getMessageTypes()
			.get(1);
		internal_static_org_laokou_distributed_identifier_api_DistributedIdentifierResult_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
				internal_static_org_laokou_distributed_identifier_api_DistributedIdentifierResult_descriptor,
				new java.lang.String[] { "Code", "Msg", "Data", });
		internal_static_org_laokou_distributed_identifier_api_DistributedIdentifierBatchCmd_descriptor = getDescriptor()
			.getMessageTypes()
			.get(2);
		internal_static_org_laokou_distributed_identifier_api_DistributedIdentifierBatchCmd_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
				internal_static_org_laokou_distributed_identifier_api_DistributedIdentifierBatchCmd_descriptor,
				new java.lang.String[] { "Num", });
		internal_static_org_laokou_distributed_identifier_api_DistributedIdentifierBatchResult_descriptor = getDescriptor()
			.getMessageTypes()
			.get(3);
		internal_static_org_laokou_distributed_identifier_api_DistributedIdentifierBatchResult_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
				internal_static_org_laokou_distributed_identifier_api_DistributedIdentifierBatchResult_descriptor,
				new java.lang.String[] { "Code", "Msg", "Data", });
	}

	// @@protoc_insertion_point(outer_class_scope)

}
