# /*
#  * Copyright (c) 2022-2026 KCloud-Platform-IoT Author or Authors. All Rights Reserved.
#  * <p>
#  * Licensed under the Apache License, Version 2.0 (the "License");
#  * you may not use this file except in compliance with the License.
#  * You may obtain a copy of the License at
#  * <p>
#  *   http://www.apache.org/licenses/LICENSE-2.0
#  * <p>
#  * Unless required by applicable law or agreed to in writing, software
#  * distributed under the License is distributed on an "AS IS" BASIS,
#  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  * See the License for the specific language governing permissions and
#  * limitations under the License.
#  */
worker_processes  auto;
worker_rlimit_nofile 200000;

events {
	use epoll;
    worker_connections      65535;
	multi_accept on;
}

http  {

    include                 mime.types;
    default_type            application/octet-stream;
	server_tokens 			off;
	sendfile 				on;
	tcp_nopush 				on;
	tcp_nodelay 			on;
	keepalive_timeout 		60;
	keepalive_requests 		100000;
	client_max_body_size 	1024m;

	# ====================
	# GZIP
	# ====================
	gzip on;
	gzip_comp_level 6;
	gzip_min_length 1k;
	gzip_types
        text/plain
        text/css
        text/javascript
        application/json
        application/javascript
        application/xml
        application/xml+rss
        application/x-javascript;

	# ====================
	# Gateway Cluster
	# ====================
	upstream gateway_cluster {

		least_conn;

		keepalive 512;

		server gateway:5555
            max_fails=3
            fail_timeout=30s;
	}

	# ====================
	# Auth Cluster
	# ====================
	upstream auth_cluster {

		keepalive 128;

		server auth:1111
            max_fails=3
            fail_timeout=30s;
	}

	# ====================
	# Frontend
	# ====================
    server  {
        listen 88;

		root /usr/share/nginx/dist;
		index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        location /api-gateway {
            proxy_pass http://gateway_cluster;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

			# websocket
			proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";

			proxy_connect_timeout 10s;
			proxy_send_timeout 60s;
			proxy_read_timeout 60s;
			proxy_buffer_size 32k;
			proxy_buffers 8 32k;
			proxy_busy_buffers_size 64k;
			proxy_buffering on;
			add_header Access-Control-Allow-Origin *;
			add_header Access-Control-Allow-Credentials true;
			add_header Access-Control-Allow-Headers *;
			add_header Access-Control-Allow-Methods *;
        }
    }
	server {
		listen 89;

		location /api {
			proxy_pass http://auth_cluster;
			proxy_http_version 1.1;
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-Forwarded-Proto $scheme;
			proxy_connect_timeout 10s;
			proxy_send_timeout 60s;
			proxy_read_timeout 60s;
			proxy_buffer_size 16k;
			proxy_buffers 4 32k;
			proxy_buffering on;
			add_header Access-Control-Allow-Origin *;
			add_header Access-Control-Allow-Credentials true;
			add_header Access-Control-Allow-Headers *;
			add_header Access-Control-Allow-Methods *;
		}

	}
}
