module laokou.im.server {
    requires lombok;
    requires spring.context;
    requires io.netty.transport;
    requires io.netty.handler;
    requires io.netty.codec.http;
    requires spring.cloud.context;
    requires laokou.common.netty;
    requires spring.boot.autoconfigure;
    requires laokou.common.redis;
    requires com.github.benmanes.caffeine;
    requires laokou.common.i18n;
    requires laokou.common.core;
    requires laokou.auth.domain;
    requires io.netty.buffer;
    requires io.netty.common;
    requires spring.boot;
    requires micrometer.commons;
    requires laokou.common.nacos;
    requires jakarta.annotation;
    requires rocketmq.spring.boot;
    requires laokou.common.rocketmq;
    requires rocketmq.common;
    requires laokou.im.client;
    requires spring.cloud.commons;
    requires jasypt.spring.boot;
    requires laokou.common.security;
    requires nacos.client;
}