#/**
# * Copyright (c) 2022-2024 KCloud-Platform-IoT Author or Authors. All Rights Reserved.
# * <p>
# * Licensed under the Apache License, Version 2.0 (the "License");
# * you may not use this file except in compliance with the License.
# * You may obtain a copy of the License at
# * <p>
# *   http://www.apache.org/licenses/LICENSE-2.0
# * <p>
# * Unless required by applicable law or agreed to in writing, software
# * distributed under the License is distributed on an "AS IS" BASIS,
# * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# * See the License for the specific language governing permissions and
# * limitations under the License.
# */
# 用户名密码登录
# https://datatracker.ietf.org/doc/html/rfc6749#section-1.3
POST {{schema}}{{host}}/oauth2/token
Authorization: {{Authorization}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="grant_type"

password
--WebAppBoundary
Content-Disposition: form-data; name="username"

{{username}}
--WebAppBoundary
Content-Disposition: form-data; name="password"

{{password}}
--WebAppBoundary
Content-Disposition: form-data; name="uuid"

{{uuid}}
--WebAppBoundary
Content-Disposition: form-data; name="captcha"

{{captcha}}
--WebAppBoundary
Content-Disposition: form-data; name="tenant_id"

{{tenant_id}}
--WebAppBoundary

###

# 手机登录
POST {{schema}}{{host}}/oauth2/token
Authorization: {{Authorization}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="grant_type"

mobile
--WebAppBoundary
Content-Disposition: form-data; name="mobile"

{{mobile}}
--WebAppBoundary
Content-Disposition: form-data; name="code"

{{mobile_code}}
--WebAppBoundary
Content-Disposition: form-data; name="tenant_id"

{{tenant_id}}
--WebAppBoundary


###

# 邮箱登录
POST {{schema}}{{host}}/oauth2/token
Authorization: {{Authorization}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="grant_type"

mail
--WebAppBoundary
Content-Disposition: form-data; name="mail"

{{mail}}
--WebAppBoundary
Content-Disposition: form-data; name="code"

{{mail_code}}
--WebAppBoundary
Content-Disposition: form-data; name="tenant_id"

{{tenant_id}}
--WebAppBoundary

###

# 授权码模式(默认数据库)
# 用户名/密码：admin/admin123
# 获取code地址：https://127.0.0.1:1111/oauth2/authorize?client_id=95TxSsTPFA3tF12TBSMmUVK0da&client_secret=FpHwIfw4wY92dO&response_type=code&scope=password mail mobile&redirect_uri=http://127.0.0.1:8000
# 获取code地址：http://127.0.0.1:1111/oauth2/authorize?client_id=95TxSsTPFA3tF12TBSMmUVK0da&client_secret=FpHwIfw4wY92dO&response_type=code&scope=password mail mobile&redirect_uri=http://127.0.0.1:8000
POST {{schema}}{{host}}/oauth2/token
Authorization: {{Authorization}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="grant_type"

authorization_code
--WebAppBoundary
Content-Disposition: form-data; name="code"

{{code}}
--WebAppBoundary
Content-Disposition: form-data; name="redirect_uri"

{{redirect_uri}}
--WebAppBoundary

###

# 客户端模式(默认数据库)
POST {{schema}}{{host}}/oauth2/token
Authorization: {{Authorization}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="grant_type"

client_credentials
--WebAppBoundary

###

# 获取设备码(默认数据库)
POST {{schema}}{{host}}/oauth2/device_authorization
Authorization: {{Authorization}}
Content-Type: application/x-www-form-urlencoded; boundary=WebAppBoundary

###

# 设备端模式(默认数据库)
POST {{schema}}{{host}}/oauth2/token
Authorization: {{Authorization}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="device_code"

{{device_code}}
--WebAppBoundary
Content-Disposition: form-data; name="grant_type"

urn:ietf:params:oauth:grant-type:device_code
--WebAppBoundary

###

# 刷新令牌
POST {{schema}}{{host}}/oauth2/token
Authorization: {{Authorization}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="grant_type"

refresh_token
--WebAppBoundary
Content-Disposition: form-data; name="refresh_token"

{{refresh_token}}
--WebAppBoundary
