// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: oss.proto

// Protobuf Java Version: 3.25.5
package org.laokou.oss.api;

public final class Oss {

	private Oss() {
	}

	public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {
	}

	public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
		registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
	}

	static final com.google.protobuf.Descriptors.Descriptor internal_static_org_laokou_oss_api_OssUploadCmd_descriptor;
	static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_org_laokou_oss_api_OssUploadCmd_fieldAccessorTable;
	static final com.google.protobuf.Descriptors.Descriptor internal_static_org_laokou_oss_api_OssUploadCO_descriptor;
	static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_org_laokou_oss_api_OssUploadCO_fieldAccessorTable;
	static final com.google.protobuf.Descriptors.Descriptor internal_static_org_laokou_oss_api_OssUploadResult_descriptor;
	static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_org_laokou_oss_api_OssUploadResult_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
		return descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
	static {
		java.lang.String[] descriptorData = { "\n\toss.proto\022\022org.laokou.oss.api\"r\n\014OssUp"
				+ "loadCmd\022\020\n\010fileType\030\001 \001(\t\022\016\n\006buffer\030\002 \001("
				+ "\014\022\014\n\004name\030\003 \001(\t\022\017\n\007extName\030\004 \001(\t\022\023\n\013cont"
				+ "entType\030\005 \001(\t\022\014\n\004size\030\006 \001(\003\"&\n\013OssUpload"
				+ "CO\022\n\n\002id\030\001 \001(\003\022\013\n\003url\030\002 \001(\t\"[\n\017OssUpload"
				+ "Result\022\014\n\004code\030\001 \001(\t\022\013\n\003msg\030\002 \001(\t\022-\n\004dat"
				+ "a\030\003 \001(\0132\037.org.laokou.oss.api.OssUploadCO"
				+ "2a\n\013OssServiceI\022R\n\tuploadOss\022 .org.laoko" + "u.oss.api.OssUploadCmd\032#.org.laokou.oss."
				+ "api.OssUploadResultB\002P\001b\006proto3" };
		descriptor = com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
				new com.google.protobuf.Descriptors.FileDescriptor[] {});
		internal_static_org_laokou_oss_api_OssUploadCmd_descriptor = getDescriptor().getMessageTypes().get(0);
		internal_static_org_laokou_oss_api_OssUploadCmd_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
				internal_static_org_laokou_oss_api_OssUploadCmd_descriptor,
				new java.lang.String[] { "FileType", "Buffer", "Name", "ExtName", "ContentType", "Size", });
		internal_static_org_laokou_oss_api_OssUploadCO_descriptor = getDescriptor().getMessageTypes().get(1);
		internal_static_org_laokou_oss_api_OssUploadCO_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
				internal_static_org_laokou_oss_api_OssUploadCO_descriptor, new java.lang.String[] { "Id", "Url", });
		internal_static_org_laokou_oss_api_OssUploadResult_descriptor = getDescriptor().getMessageTypes().get(2);
		internal_static_org_laokou_oss_api_OssUploadResult_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
				internal_static_org_laokou_oss_api_OssUploadResult_descriptor,
				new java.lang.String[] { "Code", "Msg", "Data", });
	}

	// @@protoc_insertion_point(outer_class_scope)

}
