// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: oss.proto

// Protobuf Java Version: 3.25.5
package org.laokou.oss.api;

public interface OssUploadResultOrBuilder extends
		// @@protoc_insertion_point(interface_extends:org.laokou.oss.api.OssUploadResult)
		com.google.protobuf.MessageOrBuilder {

	/**
	 * <code>string code = 1;</code>
	 * @return The code.
	 */
	java.lang.String getCode();

	/**
	 * <code>string code = 1;</code>
	 * @return The bytes for code.
	 */
	com.google.protobuf.ByteString getCodeBytes();

	/**
	 * <code>string msg = 2;</code>
	 * @return The msg.
	 */
	java.lang.String getMsg();

	/**
	 * <code>string msg = 2;</code>
	 * @return The bytes for msg.
	 */
	com.google.protobuf.ByteString getMsgBytes();

	/**
	 * <code>.org.laokou.oss.api.OssUploadCO data = 3;</code>
	 * @return Whether the data field is set.
	 */
	boolean hasData();

	/**
	 * <code>.org.laokou.oss.api.OssUploadCO data = 3;</code>
	 * @return The data.
	 */
	org.laokou.oss.api.OssUploadCO getData();

	/**
	 * <code>.org.laokou.oss.api.OssUploadCO data = 3;</code>
	 */
	org.laokou.oss.api.OssUploadCOOrBuilder getDataOrBuilder();

}
