// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: oss.proto

// Protobuf Java Version: 3.25.5
package org.laokou.oss.api;

public interface OssUploadCOOrBuilder extends
		// @@protoc_insertion_point(interface_extends:org.laokou.oss.api.OssUploadCO)
		com.google.protobuf.MessageOrBuilder {

	/**
	 * <code>int64 id = 1;</code>
	 * @return The id.
	 */
	long getId();

	/**
	 * <code>string url = 2;</code>
	 * @return The url.
	 */
	java.lang.String getUrl();

	/**
	 * <code>string url = 2;</code>
	 * @return The bytes for url.
	 */
	com.google.protobuf.ByteString getUrlBytes();

}
