name: Bug报告
description: 帮助我们改进
title: "[Bug报告]: 描述"
labels: ["缺陷"]
assignees: 'KouShenhai'
body:
  - type: markdown
    attributes:
      value: |
        请确认以下信息：
        1. 请按此模板提交issues, 不按模板提交的问题将直接关闭
        2. 如果你使用的版本号不是最新版, 那么你的 issue 大概率将会被直接关闭
        3. 如果你的问题与该仓库无关或者可以直接在以往 issue 中找到, 那么你的 issue 大概率将会被直接关闭
        4. 提交问题务必描述清楚、附上日志, 描述不清导致无法理解和分析的问题 大概率会被直接关闭
  - type: checkboxes
    id: confirm
    attributes:
      label: 确认
      description: 在提交 issue 之前, 请确认你已经阅读并确认以下内容, 如果 不全部勾选 或 勾选与事实不符 那么你的 issue 大概率将会被直接关闭
      options:
        - label: 我使用的版本是[最新版](https://github.com/KouShenhai/KCloud-Platform-IoT), 并且使用插件确认过项目里无依赖版本冲突
          required: true
        - label: 我已经在 [issue](https://github.com/KouShenhai/KCloud-Platform-IoT/issues) 中搜索过, 确认问题没有被提出过
          required: true
        - label: 我已经修改标题, 将标题中的 描述 替换为遇到的问题
          required: true
  - type: input
    id: version
    attributes:
      label: 当前程序版本
      description: 遇到问题时程序所在的版本号
    validations:
      required: true
  - type: input
    id: jdk-version
    attributes:
      label: 当前JDK版本
      description: 遇到问题时程序所在的JDK版本
    validations:
      required: true
  - type: input
    id: spring-boot-version
    attributes:
      label: 当前SpringBoot版本
      description: 遇到问题时程序所在的SpringBoot版本
    validations:
      required: true
  - type: input
    id: spring-cloud-version
    attributes:
      label: 当前SpringCloud版本
      description: 遇到问题时程序所在的SpringCloud版本
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: BUG描述（简洁描述）
      description: 请描述你碰到的问题
      placeholder: "BUG描述（简洁描述）"
    validations:
      required: true
  - type: textarea
    id: bug-reproduction-steps
    attributes:
      label: BUG复现步骤（写清楚并附图）
      description: 请详细描述BUG复现步骤
      placeholder: "BUG复现步骤（写清楚并附图）"
    validations:
      required: true
  - type: textarea
    id: desired-result
    attributes:
      label: 预期效果（简洁描述）
      description: 请描述预期效果
      placeholder: "预期效果（简洁描述）"
    validations:
      required: true
  - type: textarea
    id: stack-log
    attributes:
      label: 详细堆栈日志
      description: 问题出现时，程序错误堆栈日志
      render: bash
