name: 功能改进
description: 功能改进
title: "[功能改进]: 描述"
labels: ["功能"]
assignees: 'KouShenhai'
body:
  - type: markdown
    attributes:
      value: |
        请说明你希望添加的功能
  - type: checkboxes
    id: confirm
    attributes:
      label: 确认
      description: 在提交 issue 之前，请确认你已经阅读并确认以下内容
      options:
        - label: 我的版本是[最新版](https://github.com/KouShenhai/KCloud-Platform-IoT), 并且项目里无依赖冲突
          required: true
        - label: 我已经在 [issue](https://github.com/KouShenhai/KCloud-Platform-IoT/issues) 中搜索过, 确认功能没有被提出过
          required: true
        - label: 我已经修改标题, 将标题中的 描述 替换为改进的功能
          required: true
  - type: textarea
    id: feature-request
    attributes:
      label: 功能改进
      description: 请详细描述需要改进或者添加的功能。
      placeholder: "功能改进"
    validations:
      required: true
  - type: textarea
    id: references
    attributes:
      label: 参考资料
      description: 可以列举一些参考资料，但是不要引用同类但商业化软件的任何内容。
      placeholder: "参考资料"
