module laokou.power.job {
    requires spring.context;
    requires jakarta.websocket.api;
    requires spring.beans;
    requires spring.boot.autoconfigure;
    requires lombok;
    requires powerjob.server.remote;
    requires io.swagger.v3.oas.models;
    requires powerjob.server.common;
    requires org.springdoc.openapi.common;
    requires spring.core;
    requires spring.websocket;
    requires spring.webmvc;
    requires spring.web;
    requires powerjob.server.core;
    requires powerjob.server.persistence;
    requires powerjob.common;
    requires spring.data.commons;
    requires com.google.common;
    requires org.apache.commons.lang3;
    requires java.servlet;
    requires java.annotation;
    requires org.apache.commons.io;
    requires fastjson;
    requires spring.messaging;
    requires org.aspectj.weaver;
    requires jasypt.spring.boot;
    requires spring.boot;
}