server:
  port: ${SERVER_PORT:9997}
  ssl:
    # 开启证书
    enabled: @SSL-ENABLED@
    # 证书位置
    key-store: classpath:scg-keystore.p12
    # 证书别名
    key-alias: ${spring.application.name}
    # 秘钥类型
    key-store-type: PKCS12
    # 证书密码
    key-store-password: laokou
  http2:
    enabled: @SSL-ENABLED@
  shutdown: graceful
  forward-headers-strategy: native

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  tracing:
    enabled: true
    propagation:
      type: w3c
    # 采样率 => 100%
    sampling:
      probability: 1
  otlp:
    tracing:
      endpoint: http://otel-collector:4317/v1/traces
      compression: gzip
      timeout: 10s
      transport: grpc
    metrics:
      export:
        enabled: false
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  config: classpath:log4j2-@PROFILE-ACTIVE@.xml

spring:
  application:
    name: ${SERVICE_ID:laokou-tcp}
  profiles:
    active: @PROFILE-ACTIVE@
  threads:
    virtual:
      enabled: true
  tcp-server:
    # 创建120个端口
    ports:
      - 3880
      - 3881
      - 3882
      - 3883
      - 3884
      - 3885
      - 3886
      - 3887
      - 3888
      - 3889
      - 3890
      - 3891
      - 3892
      - 3893
      - 3894
      - 3895
      - 3896
      - 3897
      - 3898
      - 3899
      - 3900
      - 3901
      - 3902
      - 3903
      - 3904
      - 3905
      - 3906
      - 3907
      - 3908
      - 3909
      - 3910
      - 3911
      - 3912
      - 3913
      - 3914
      - 3915
      - 3916
      - 3917
      - 3918
      - 3919
      - 3920
      - 3921
      - 3922
      - 3923
      - 3924
      - 3925
      - 3926
      - 3927
      - 3928
      - 3929
      - 3930
      - 3931
      - 3932
      - 3933
      - 3934
      - 3935
      - 3936
      - 3937
      - 3938
      - 3939
      - 3940
      - 3941
      - 3942
      - 3943
      - 3944
      - 3945
      - 3946
      - 3947
      - 3948
      - 3949
      - 3950
      - 3951
      - 3952
      - 3953
      - 3954
      - 3955
      - 3956
      - 3957
      - 3958
      - 3959
      - 3960
      - 3961
      - 3962
      - 3963
      - 3964
      - 3965
      - 3966
      - 3967
      - 3968
      - 3969
      - 3970
      - 3971
      - 3972
      - 3973
      - 3974
      - 3975
      - 3976
      - 3977
      - 3978
      - 3979
      - 3980
      - 3981
      - 3982
      - 3983
      - 3984
      - 3985
      - 3986
      - 3987
      - 3988
      - 3989
      - 3990
      - 3991
      - 3992
      - 3993
      - 3994
      - 3995
      - 3996
      - 3997
      - 3998
      - 3999
      - 4000
