-- liquibase formatted sql

-- changeset dev:000001
DROP TABLE IF EXISTS "public"."sys_i18n_menu";
CREATE TABLE "public"."sys_i18n_menu" (
	"id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"creator" int8 NOT NULL DEFAULT 0,
	"editor" int8 NOT NULL DEFAULT 0,
	"create_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"update_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"del_flag" int2 NOT NULL DEFAULT 0,
	"version" int4 NOT NULL DEFAULT 0,
	"tenant_id" int8 NOT NULL DEFAULT 0,
	"dept_id" int8 NOT NULL DEFAULT 1,
	"code" varchar(50) NOT NULL,
	"menu" varchar(50) NOT NULL
);
COMMENT ON COLUMN "public"."sys_i18n_menu"."id" IS 'ID';
COMMENT ON COLUMN "public"."sys_i18n_menu"."creator" IS '创建人';
COMMENT ON COLUMN "public"."sys_i18n_menu"."editor" IS '编辑人';
COMMENT ON COLUMN "public"."sys_i18n_menu"."create_time" IS '创建时间';
COMMENT ON COLUMN "public"."sys_i18n_menu"."update_time" IS '修改时间';
COMMENT ON COLUMN "public"."sys_i18n_menu"."del_flag" IS '删除标识 0未删除 1已删除';
COMMENT ON COLUMN "public"."sys_i18n_menu"."version" IS '版本号';
COMMENT ON COLUMN "public"."sys_i18n_menu"."tenant_id" IS '租户ID';
COMMENT ON COLUMN "public"."sys_i18n_menu"."dept_id" IS '部门ID';
COMMENT ON COLUMN "public"."sys_i18n_menu"."code" IS '编码';
COMMENT ON COLUMN "public"."sys_i18n_menu"."menu" IS '菜单';
COMMENT ON TABLE "public"."sys_i18n_menu" IS '国际化菜单';

CREATE INDEX "sys_i18n_menu_code_menu_idx" ON "public"."sys_i18n_menu" USING btree (
	"code",
	"menu"
);
COMMENT ON INDEX "public"."sys_i18n_menu_code_menu_idx" IS '编码_菜单_唯一索引';

ALTER TABLE "public"."sys_i18n_menu" ADD CONSTRAINT "sys_i18n_menu_pkey" PRIMARY KEY ("id");
