DROP TABLE IF EXISTS "public"."t_user";
CREATE TABLE "public"."t_user" (
								   "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
								   "name" varchar(20) NOT NULL,
								   "creator" int8 NOT NULL DEFAULT 0,
								   "editor" int8 NOT NULL DEFAULT 0,
								   "create_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
								   "update_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
								   "del_flag" int2 NOT NULL DEFAULT 0,
								   "version" int4 NOT NULL DEFAULT 0,
								   "tenant_id" int8 NOT NULL DEFAULT 0,
								   CONSTRAINT "t_user_pkey" PRIMARY KEY ("id")
);
COMMENT ON COLUMN "public"."t_user"."id" IS 'ID';
COMMENT ON COLUMN "public"."t_user"."name" IS '名称';
COMMENT ON COLUMN "public"."t_user"."creator" IS '创建人';
COMMENT ON COLUMN "public"."t_user"."editor" IS '编辑人';
COMMENT ON COLUMN "public"."t_user"."create_time" IS '创建时间';
COMMENT ON COLUMN "public"."t_user"."update_time" IS '修改时间';
COMMENT ON COLUMN "public"."t_user"."del_flag" IS '删除标识 0未删除 1已删除';
COMMENT ON COLUMN "public"."t_user"."version" IS '版本号';
COMMENT ON COLUMN "public"."t_user"."tenant_id" IS '租户ID';
INSERT INTO "public"."t_user" VALUES (1, '老寇', 1, 1, '2025-04-17 22:35:13.722422', '2025-04-17 22:35:13.722422', 0, 0, 0);
