/*
 * Copyright (c) 2022-2026 KCloud-Platform-IoT Author or Authors. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

package org.laokou.iot.common.config.mqtt;

import io.netty.handler.codec.mqtt.MqttVersion;
import lombok.Data;

/**
 * @author laokou
 */
@Data
public final class MqttClientConfig {

	private boolean auth = true;

	private boolean ssl = false;

	private String username;

	private String password;

	private String host = "127.0.0.1";

	private int port = 1883;

	/**
	 * 生产环境必须显式配置稳定的客户端ID，否则应用重启后无法恢复持久会话.
	 */
	private String clientId;

	private int receiveBufferSize = -1;

	/**
	 * 默认限制单条消息为100MiB，避免异常大包耗尽堆外内存.
	 */
	private int maxMessageSize = 100 * 1024 * 1024;

	/**
	 * 心跳包每隔60秒发一次.
	 */
	private int keepAliveInterval = 60;

	private boolean autoKeepAlive = true;

	private long reconnectInterval = 5000;

	private int reconnectAttempts = Integer.MAX_VALUE;

	private int ackTimeout = 30;

	private boolean autoAck = false;

	private boolean isAutoGeneratedClientId = false;

	private boolean tcpNoDelay = true;

	private boolean tcpKeepAlive = true;

	private int connectTimeout = 15000;

	private int soLinger = 0;

	private long sessionExpireInterval = 0L;

	private boolean cleanSession = true;

	private byte version = MqttVersion.MQTT_5.protocolLevel();

	private int maxInflightQueue = 1024;

}
