/*
 * Copyright (c) 2022-2026 KCloud-Platform-IoT Author or Authors. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

package org.laokou.iot.common.config.mqtt;

import lombok.Data;
import org.laokou.common.core.util.UUIDGenerator;

/**
 * @author laokou
 */
@Data
public final class MqttClientConfig {

	private boolean auth = true;

	private boolean ssl = false;

	private String username = "root";

	private String password = "laokou123";

	private String host = "127.0.0.1";

	private int port = 1883;

	private String clientId = UUIDGenerator.generateUUID();

	private int receiveBufferSize = -1;

	private int maxMessageSize = -1;

	/**
	 * 心跳包每隔60秒发一次.
	 */
	private int keepAliveInterval = 60;

	private boolean autoKeepAlive = true;

	private long reconnectInterval = 5000;

	private int reconnectAttempts = -1;

	private int ackTimeout = -1;

	private boolean autoAck = true;

	private boolean isAutoGeneratedClientId = false;

	private boolean tcpNoDelay = true;

	private boolean tcpKeepAlive = true;

	private int connectTimeout = 15000;

	private int soLinger = 0;

}
