/*
 Navicat Premium Dump SQL

 Source Server         : 127.0.0.1
 Source Server Type    : PostgreSQL
 Source Server Version : 170003 (170003)
 Source Host           : 127.0.0.1:5432
 Source Catalog        : kcloud_platform
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 170003 (170003)
 File Encoding         : 65001

 Date: 15/05/2025 11:26:07
*/

DROP TABLE IF EXISTS "public"."sys_user_202401";
CREATE TABLE "public"."sys_user_202401" (
"id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
"name" varchar(50)  NOT NULL,
"create_time" timestamp(6) NOT NULL
)
;
COMMENT ON COLUMN "public"."sys_user_202401"."id" IS 'ID';
COMMENT ON COLUMN "public"."sys_user_202401"."name" IS '名称';
COMMENT ON COLUMN "public"."sys_user_202401"."create_time" IS '创建时间';
ALTER TABLE "public"."sys_user_202401" ADD CONSTRAINT "sys_user_202401_pkey" PRIMARY KEY ("id");

DROP TABLE IF EXISTS "public"."sys_user_202402";
CREATE TABLE "public"."sys_user_202402" (
"id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
"name" varchar(50)  NOT NULL,
"create_time" timestamp(6) NOT NULL
)
;
COMMENT ON COLUMN "public"."sys_user_202402"."id" IS 'ID';
COMMENT ON COLUMN "public"."sys_user_202402"."name" IS '名称';
COMMENT ON COLUMN "public"."sys_user_202402"."create_time" IS '创建时间';
ALTER TABLE "public"."sys_user_202402" ADD CONSTRAINT "sys_user_202402_pkey" PRIMARY KEY ("id");

DROP TABLE IF EXISTS "public"."sys_user_202403";
CREATE TABLE "public"."sys_user_202403" (
"id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
"name" varchar(50)  NOT NULL,
"create_time" timestamp(6) NOT NULL
)
;
COMMENT ON COLUMN "public"."sys_user_202403"."id" IS 'ID';
COMMENT ON COLUMN "public"."sys_user_202403"."name" IS '名称';
COMMENT ON COLUMN "public"."sys_user_202403"."create_time" IS '创建时间';
ALTER TABLE "public"."sys_user_202403" ADD CONSTRAINT "sys_user_202403_pkey" PRIMARY KEY ("id");

DROP TABLE IF EXISTS "public"."sys_user_202404";
CREATE TABLE "public"."sys_user_202404" (
"id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
"name" varchar(50)  NOT NULL,
"create_time" timestamp(6) NOT NULL
)
;
COMMENT ON COLUMN "public"."sys_user_202404"."id" IS 'ID';
COMMENT ON COLUMN "public"."sys_user_202404"."name" IS '名称';
COMMENT ON COLUMN "public"."sys_user_202404"."create_time" IS '创建时间';
ALTER TABLE "public"."sys_user_202404" ADD CONSTRAINT "sys_user_202404_pkey" PRIMARY KEY ("id");

DROP TABLE IF EXISTS "public"."sys_user_202405";
CREATE TABLE "public"."sys_user_202405" (
"id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
"name" varchar(50)  NOT NULL,
"create_time" timestamp(6) NOT NULL
)
;
COMMENT ON COLUMN "public"."sys_user_202405"."id" IS 'ID';
COMMENT ON COLUMN "public"."sys_user_202405"."name" IS '名称';
COMMENT ON COLUMN "public"."sys_user_202405"."create_time" IS '创建时间';
ALTER TABLE "public"."sys_user_202405" ADD CONSTRAINT "sys_user_202405_pkey" PRIMARY KEY ("id");

DROP TABLE IF EXISTS "public"."sys_user_202406";
CREATE TABLE "public"."sys_user_202406" (
"id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
"name" varchar(50)  NOT NULL,
"create_time" timestamp(6) NOT NULL
)
;
COMMENT ON COLUMN "public"."sys_user_202406"."id" IS 'ID';
COMMENT ON COLUMN "public"."sys_user_202406"."name" IS '名称';
COMMENT ON COLUMN "public"."sys_user_202406"."create_time" IS '创建时间';
ALTER TABLE "public"."sys_user_202406" ADD CONSTRAINT "sys_user_202406_pkey" PRIMARY KEY ("id");

DROP TABLE IF EXISTS "public"."sys_user_202407";
CREATE TABLE "public"."sys_user_202407" (
"id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
"name" varchar(50)  NOT NULL,
"create_time" timestamp(6) NOT NULL
)
;
COMMENT ON COLUMN "public"."sys_user_202407"."id" IS 'ID';
COMMENT ON COLUMN "public"."sys_user_202407"."name" IS '名称';
COMMENT ON COLUMN "public"."sys_user_202407"."create_time" IS '创建时间';
ALTER TABLE "public"."sys_user_202407" ADD CONSTRAINT "sys_user_202407_pkey" PRIMARY KEY ("id");

DROP TABLE IF EXISTS "public"."sys_user_202408";
CREATE TABLE "public"."sys_user_202408" (
"id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
"name" varchar(50)  NOT NULL,
"create_time" timestamp(6) NOT NULL
)
;
COMMENT ON COLUMN "public"."sys_user_202408"."id" IS 'ID';
COMMENT ON COLUMN "public"."sys_user_202408"."name" IS '名称';
COMMENT ON COLUMN "public"."sys_user_202408"."create_time" IS '创建时间';
ALTER TABLE "public"."sys_user_202408" ADD CONSTRAINT "sys_user_202408_pkey" PRIMARY KEY ("id");

DROP TABLE IF EXISTS "public"."sys_user_202409";
CREATE TABLE "public"."sys_user_202409" (
"id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
"name" varchar(50)  NOT NULL,
"create_time" timestamp(6) NOT NULL
)
;
COMMENT ON COLUMN "public"."sys_user_202409"."id" IS 'ID';
COMMENT ON COLUMN "public"."sys_user_202409"."name" IS '名称';
COMMENT ON COLUMN "public"."sys_user_202409"."create_time" IS '创建时间';
ALTER TABLE "public"."sys_user_202409" ADD CONSTRAINT "sys_user_202409_pkey" PRIMARY KEY ("id");

DROP TABLE IF EXISTS "public"."sys_user_202410";
CREATE TABLE "public"."sys_user_202410" (
"id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
"name" varchar(50)  NOT NULL,
"create_time" timestamp(6) NOT NULL
)
;
COMMENT ON COLUMN "public"."sys_user_202410"."id" IS 'ID';
COMMENT ON COLUMN "public"."sys_user_202410"."name" IS '名称';
COMMENT ON COLUMN "public"."sys_user_202410"."create_time" IS '创建时间';
ALTER TABLE "public"."sys_user_202410" ADD CONSTRAINT "sys_user_202410_pkey" PRIMARY KEY ("id");
INSERT INTO "public"."sys_user_202410" VALUES (1, 'sys_user_202410_用户1', '2024-10-26 20:14:22');

DROP TABLE IF EXISTS "public"."sys_user_202411";
CREATE TABLE "public"."sys_user_202411" (
"id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
"name" varchar(50)  NOT NULL,
"create_time" timestamp(6) NOT NULL
)
;
COMMENT ON COLUMN "public"."sys_user_202411"."id" IS 'ID';
COMMENT ON COLUMN "public"."sys_user_202411"."name" IS '名称';
COMMENT ON COLUMN "public"."sys_user_202411"."create_time" IS '创建时间';

ALTER TABLE "public"."sys_user_202411" ADD CONSTRAINT "sys_user_202411_pkey" PRIMARY KEY ("id");

DROP TABLE IF EXISTS "public"."sys_user_202412";
CREATE TABLE "public"."sys_user_202412" (
"id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
"name" varchar(50)  NOT NULL,
"create_time" timestamp(6) NOT NULL
)
;
COMMENT ON COLUMN "public"."sys_user_202412"."id" IS 'ID';
COMMENT ON COLUMN "public"."sys_user_202412"."name" IS '名称';
COMMENT ON COLUMN "public"."sys_user_202412"."create_time" IS '创建时间';

ALTER TABLE "public"."sys_user_202412" ADD CONSTRAINT "sys_user_202412_pkey" PRIMARY KEY ("id");

DROP TABLE IF EXISTS "public"."t_user";
CREATE TABLE "public"."t_user" (
   "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   "name" varchar(20) NOT NULL,
   "creator" int8 NOT NULL DEFAULT 0,
   "editor" int8 NOT NULL DEFAULT 0,
   "create_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
   "update_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
   "del_flag" int2 NOT NULL DEFAULT 0,
   "version" int4 NOT NULL DEFAULT 0,
   "tenant_id" int8 NOT NULL DEFAULT 0,
   CONSTRAINT "t_user_pkey" PRIMARY KEY ("id")
);
COMMENT ON COLUMN "public"."t_user"."id" IS 'ID';
COMMENT ON COLUMN "public"."t_user"."name" IS '名称';
COMMENT ON COLUMN "public"."t_user"."creator" IS '创建人';
COMMENT ON COLUMN "public"."t_user"."editor" IS '编辑人';
COMMENT ON COLUMN "public"."t_user"."create_time" IS '创建时间';
COMMENT ON COLUMN "public"."t_user"."update_time" IS '修改时间';
COMMENT ON COLUMN "public"."t_user"."del_flag" IS '删除标识 0未删除 1已删除';
COMMENT ON COLUMN "public"."t_user"."version" IS '版本号';
COMMENT ON COLUMN "public"."t_user"."tenant_id" IS '租户ID';
INSERT INTO "public"."t_user" VALUES (1, '老寇', 1, 1, '2025-04-17 22:35:13.722422', '2025-04-17 22:35:13.722422', 0, 0, 0);

