/*
 Navicat Premium Data Transfer

 Source Server         : 127.0.0.1
 Source Server Type    : PostgreSQL
 Source Server Version : 160002 (160002)
 Source Host           : 127.0.0.1:5432
 Source Catalog        : kcloud_platform_iot_xxl_job
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 160002 (160002)
 File Encoding         : 65001

 Date: 02/05/2024 02:22:37
*/


-- ----------------------------
-- Sequence structure for xxl_job_group_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."xxl_job_group_id_seq";
CREATE SEQUENCE "public"."xxl_job_group_id_seq"
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for xxl_job_info_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."xxl_job_info_id_seq";
CREATE SEQUENCE "public"."xxl_job_info_id_seq"
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for xxl_job_log_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."xxl_job_log_id_seq";
CREATE SEQUENCE "public"."xxl_job_log_id_seq"
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for xxl_job_log_report_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."xxl_job_log_report_id_seq";
CREATE SEQUENCE "public"."xxl_job_log_report_id_seq"
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for xxl_job_logglue_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."xxl_job_logglue_id_seq";
CREATE SEQUENCE "public"."xxl_job_logglue_id_seq"
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for xxl_job_registry_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."xxl_job_registry_id_seq";
CREATE SEQUENCE "public"."xxl_job_registry_id_seq"
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for xxl_job_user_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."xxl_job_user_id_seq";
CREATE SEQUENCE "public"."xxl_job_user_id_seq"
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Table structure for flyway_schema_history
-- ----------------------------
DROP TABLE IF EXISTS "public"."flyway_schema_history";
CREATE TABLE "public"."flyway_schema_history" (
												  "installed_rank" int4 NOT NULL,
												  "version" varchar(50) COLLATE "pg_catalog"."default",
												  "description" varchar(200) COLLATE "pg_catalog"."default" NOT NULL,
												  "type" varchar(20) COLLATE "pg_catalog"."default" NOT NULL,
												  "script" varchar(1000) COLLATE "pg_catalog"."default" NOT NULL,
												  "checksum" int4,
												  "installed_by" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
												  "installed_on" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
												  "execution_time" int4 NOT NULL,
												  "success" int2 NOT NULL
)
;

-- ----------------------------
-- Records of flyway_schema_history
-- ----------------------------
INSERT INTO "public"."flyway_schema_history" VALUES (1, '1.0', 'init', 'SQL', 'V1.0__init.sql', -2013399993, 'root', '2024-04-07 20:35:58', 220, 1);
INSERT INTO "public"."flyway_schema_history" VALUES (2, '1.1', 'insert', 'SQL', 'V1.1__insert.sql', 584436304, 'root', '2024-04-07 20:35:59', 10, 1);
INSERT INTO "public"."flyway_schema_history" VALUES (3, '1.2', 'update', 'SQL', 'V1.2__update.sql', -620854605, 'root', '2024-04-07 20:35:59', 12, 1);
INSERT INTO "public"."flyway_schema_history" VALUES (4, '1.3', 'update', 'SQL', 'V1.3__update.sql', 391130883, 'root', '2024-04-07 20:35:59', 14, 1);
INSERT INTO "public"."flyway_schema_history" VALUES (5, '1.4', 'update', 'SQL', 'V1.4__update.sql', -1080352449, 'root', '2024-04-07 20:35:59', 14, 1);

-- ----------------------------
-- Table structure for xxl_job_group
-- ----------------------------
DROP TABLE IF EXISTS "public"."xxl_job_group";
CREATE TABLE "public"."xxl_job_group" (
										  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
											  INCREMENT 1
											  MINVALUE  1
											  MAXVALUE 2147483647
											  START 1
											  CACHE 1
											  ),
										  "app_name" varchar(64) COLLATE "pg_catalog"."default" NOT NULL,
										  "title" varchar(12) COLLATE "pg_catalog"."default" NOT NULL,
										  "address_type" int2 NOT NULL DEFAULT 0,
										  "address_list" text COLLATE "pg_catalog"."default",
										  "update_time" timestamp(6)
)
;
COMMENT ON COLUMN "public"."xxl_job_group"."app_name" IS '执行器AppName';
COMMENT ON COLUMN "public"."xxl_job_group"."title" IS '执行器名称';
COMMENT ON COLUMN "public"."xxl_job_group"."address_type" IS '执行器地址类型：0=自动注册、1=手动录入';
COMMENT ON COLUMN "public"."xxl_job_group"."address_list" IS '执行器地址列表，多地址逗号分隔';

-- ----------------------------
-- Records of xxl_job_group
-- ----------------------------
INSERT INTO "public"."xxl_job_group" VALUES (4, 'laokou-logstash', '分布式链路', 0, NULL, '2024-04-30 01:12:32');

-- ----------------------------
-- Table structure for xxl_job_info
-- ----------------------------
DROP TABLE IF EXISTS "public"."xxl_job_info";
CREATE TABLE "public"."xxl_job_info" (
										 "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
											 INCREMENT 1
											 MINVALUE  1
											 MAXVALUE 2147483647
											 START 1
											 CACHE 1
											 ),
										 "job_group" int4 NOT NULL,
										 "job_desc" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
										 "add_time" timestamp(6),
										 "update_time" timestamp(6),
										 "author" varchar(64) COLLATE "pg_catalog"."default",
										 "alarm_email" varchar(255) COLLATE "pg_catalog"."default",
										 "schedule_type" varchar(50) COLLATE "pg_catalog"."default" NOT NULL DEFAULT 'NONE'::character varying,
										 "schedule_conf" varchar(128) COLLATE "pg_catalog"."default",
										 "misfire_strategy" varchar(50) COLLATE "pg_catalog"."default" NOT NULL DEFAULT 'DO_NOTHING'::character varying,
										 "executor_route_strategy" varchar(50) COLLATE "pg_catalog"."default",
										 "executor_handler" varchar(255) COLLATE "pg_catalog"."default",
										 "executor_param" varchar(512) COLLATE "pg_catalog"."default",
										 "executor_block_strategy" varchar(50) COLLATE "pg_catalog"."default",
										 "executor_timeout" int4 NOT NULL DEFAULT 0,
										 "executor_fail_retry_count" int4 NOT NULL DEFAULT 0,
										 "glue_type" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
										 "glue_source" text COLLATE "pg_catalog"."default",
										 "glue_remark" varchar(128) COLLATE "pg_catalog"."default",
										 "glue_updatetime" timestamp(6),
										 "child_jobid" varchar(255) COLLATE "pg_catalog"."default",
										 "trigger_status" int2 NOT NULL DEFAULT 0,
										 "trigger_last_time" int8 NOT NULL DEFAULT 0,
										 "trigger_next_time" int8 NOT NULL DEFAULT 0
)
;
COMMENT ON COLUMN "public"."xxl_job_info"."job_group" IS '执行器主键ID';
COMMENT ON COLUMN "public"."xxl_job_info"."author" IS '作者';
COMMENT ON COLUMN "public"."xxl_job_info"."alarm_email" IS '报警邮件';
COMMENT ON COLUMN "public"."xxl_job_info"."schedule_type" IS '调度类型';
COMMENT ON COLUMN "public"."xxl_job_info"."schedule_conf" IS '调度配置，值含义取决于调度类型';
COMMENT ON COLUMN "public"."xxl_job_info"."misfire_strategy" IS '调度过期策略';
COMMENT ON COLUMN "public"."xxl_job_info"."executor_route_strategy" IS '执行器路由策略';
COMMENT ON COLUMN "public"."xxl_job_info"."executor_handler" IS '执行器任务handler';
COMMENT ON COLUMN "public"."xxl_job_info"."executor_param" IS '执行器任务参数';
COMMENT ON COLUMN "public"."xxl_job_info"."executor_block_strategy" IS '阻塞处理策略';
COMMENT ON COLUMN "public"."xxl_job_info"."executor_timeout" IS '任务执行超时时间，单位秒';
COMMENT ON COLUMN "public"."xxl_job_info"."executor_fail_retry_count" IS '失败重试次数';
COMMENT ON COLUMN "public"."xxl_job_info"."glue_type" IS 'GLUE类型';
COMMENT ON COLUMN "public"."xxl_job_info"."glue_source" IS 'GLUE源代码';
COMMENT ON COLUMN "public"."xxl_job_info"."glue_remark" IS 'GLUE备注';
COMMENT ON COLUMN "public"."xxl_job_info"."glue_updatetime" IS 'GLUE更新时间';
COMMENT ON COLUMN "public"."xxl_job_info"."child_jobid" IS '子任务ID，多个逗号分隔';
COMMENT ON COLUMN "public"."xxl_job_info"."trigger_status" IS '调度状态：0-停止，1-运行';
COMMENT ON COLUMN "public"."xxl_job_info"."trigger_last_time" IS '上次调度时间';
COMMENT ON COLUMN "public"."xxl_job_info"."trigger_next_time" IS '下次调度时间';

-- ----------------------------
-- Records of xxl_job_info
-- ----------------------------
INSERT INTO "public"."xxl_job_info" VALUES (3, 4, '创建分布式链路索引任务', '2023-11-03 15:45:55', '2024-02-03 16:34:42', 'laokou', '2413176044@qq.com', 'CRON', '0 50 23 L * ?', 'DO_NOTHING', 'FIRST', 'createTraceIndexJobHandler', '', 'SERIAL_EXECUTION', 0, 0, 'BEAN', '', 'GLUE代码初始化', '2023-11-03 15:45:55', '', 1, 1709221800000, 1714492200000);
INSERT INTO "public"."xxl_job_info" VALUES (6, 5, '删除领域事件任务	', '2024-01-31 14:31:09', '2024-02-03 16:34:27', 'laokou', '2413176044@qq.com', 'CRON', '0 20 0 * * ?', 'DO_NOTHING', 'FIRST', 'removeDomainEventJobHandler', '', 'SERIAL_EXECUTION', 0, 0, 'BEAN', '', 'GLUE代码初始化', '2024-01-31 14:31:09', '', 1, 1714407600000, 1714494000000);
INSERT INTO "public"."xxl_job_info" VALUES (7, 6, '删除领域事件任务', '2024-01-31 14:39:35', '2024-02-03 16:34:37', 'laokou', '2413176044@qq.com', 'CRON', '0 20 0 * * ?', 'DO_NOTHING', 'FIRST', 'removeDomainEventJobHandler', '', 'SERIAL_EXECUTION', 0, 0, 'BEAN', '', 'GLUE代码初始化', '2024-01-31 14:39:35', '', 1, 1714407600000, 1714494000000);

-- ----------------------------
-- Table structure for xxl_job_lock
-- ----------------------------
DROP TABLE IF EXISTS "public"."xxl_job_lock";
CREATE TABLE "public"."xxl_job_lock" (
										 "lock_name" varchar(50) COLLATE "pg_catalog"."default" NOT NULL
)
;
COMMENT ON COLUMN "public"."xxl_job_lock"."lock_name" IS '锁名称';

-- ----------------------------
-- Records of xxl_job_lock
-- ----------------------------
INSERT INTO "public"."xxl_job_lock" VALUES ('schedule_lock');

-- ----------------------------
-- Table structure for xxl_job_log
-- ----------------------------
DROP TABLE IF EXISTS "public"."xxl_job_log";
CREATE TABLE "public"."xxl_job_log" (
										"id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
											INCREMENT 1
											MINVALUE  1
											MAXVALUE 9223372036854775807
											START 1
											CACHE 1
											),
										"job_group" int4 NOT NULL,
										"job_id" int4 NOT NULL,
										"executor_address" varchar(255) COLLATE "pg_catalog"."default",
										"executor_handler" varchar(255) COLLATE "pg_catalog"."default",
										"executor_param" varchar(512) COLLATE "pg_catalog"."default",
										"executor_sharding_param" varchar(20) COLLATE "pg_catalog"."default",
										"executor_fail_retry_count" int4 NOT NULL DEFAULT 0,
										"trigger_time" timestamp(6),
										"trigger_code" int4 NOT NULL,
										"trigger_msg" text COLLATE "pg_catalog"."default",
										"handle_time" timestamp(6),
										"handle_code" int4 NOT NULL,
										"handle_msg" text COLLATE "pg_catalog"."default",
										"alarm_status" int2 NOT NULL DEFAULT 0
)
;
COMMENT ON COLUMN "public"."xxl_job_log"."job_group" IS '执行器主键ID';
COMMENT ON COLUMN "public"."xxl_job_log"."job_id" IS '任务，主键ID';
COMMENT ON COLUMN "public"."xxl_job_log"."executor_address" IS '执行器地址，本次执行的地址';
COMMENT ON COLUMN "public"."xxl_job_log"."executor_handler" IS '执行器任务handler';
COMMENT ON COLUMN "public"."xxl_job_log"."executor_param" IS '执行器任务参数';
COMMENT ON COLUMN "public"."xxl_job_log"."executor_sharding_param" IS '执行器任务分片参数，格式如 1/2';
COMMENT ON COLUMN "public"."xxl_job_log"."executor_fail_retry_count" IS '失败重试次数';
COMMENT ON COLUMN "public"."xxl_job_log"."trigger_time" IS '调度-时间';
COMMENT ON COLUMN "public"."xxl_job_log"."trigger_code" IS '调度-结果';
COMMENT ON COLUMN "public"."xxl_job_log"."trigger_msg" IS '调度-日志';
COMMENT ON COLUMN "public"."xxl_job_log"."handle_time" IS '执行-时间';
COMMENT ON COLUMN "public"."xxl_job_log"."handle_code" IS '执行-状态';
COMMENT ON COLUMN "public"."xxl_job_log"."handle_msg" IS '执行-日志';
COMMENT ON COLUMN "public"."xxl_job_log"."alarm_status" IS '告警状态：0-默认、1-无需告警、2-告警成功、3-告警失败';

-- ----------------------------
-- Records of xxl_job_log
-- ----------------------------
INSERT INTO "public"."xxl_job_log" VALUES (1, 5, 6, NULL, NULL, NULL, NULL, 0, '2024-04-18 00:20:00', 0, NULL, NULL, 0, NULL, 0);
INSERT INTO "public"."xxl_job_log" VALUES (2, 6, 7, NULL, NULL, NULL, NULL, 0, '2024-04-18 00:20:00', 0, NULL, NULL, 0, NULL, 0);
INSERT INTO "public"."xxl_job_log" VALUES (3, 5, 6, NULL, NULL, NULL, NULL, 0, '2024-04-27 00:20:00', 0, NULL, NULL, 0, NULL, 0);
INSERT INTO "public"."xxl_job_log" VALUES (4, 6, 7, NULL, NULL, NULL, NULL, 0, '2024-04-27 00:20:00', 0, NULL, NULL, 0, NULL, 0);
INSERT INTO "public"."xxl_job_log" VALUES (5, 5, 6, NULL, NULL, NULL, NULL, 0, '2024-04-29 00:20:00', 0, NULL, NULL, 0, NULL, 0);
INSERT INTO "public"."xxl_job_log" VALUES (6, 6, 7, NULL, NULL, NULL, NULL, 0, '2024-04-29 00:20:00', 0, NULL, NULL, 0, NULL, 0);
INSERT INTO "public"."xxl_job_log" VALUES (7, 5, 6, NULL, NULL, NULL, NULL, 0, '2024-04-30 00:20:00', 0, NULL, NULL, 0, NULL, 0);
INSERT INTO "public"."xxl_job_log" VALUES (8, 6, 7, NULL, NULL, NULL, NULL, 0, '2024-04-30 00:20:00', 0, NULL, NULL, 0, NULL, 0);

-- ----------------------------
-- Table structure for xxl_job_log_report
-- ----------------------------
DROP TABLE IF EXISTS "public"."xxl_job_log_report";
CREATE TABLE "public"."xxl_job_log_report" (
											   "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
												   INCREMENT 1
												   MINVALUE  1
												   MAXVALUE 2147483647
												   START 1
												   CACHE 1
												   ),
											   "trigger_day" timestamp(6),
											   "running_count" int4 NOT NULL DEFAULT 0,
											   "suc_count" int4 NOT NULL DEFAULT 0,
											   "fail_count" int4 NOT NULL DEFAULT 0,
											   "update_time" timestamp(6)
)
;
COMMENT ON COLUMN "public"."xxl_job_log_report"."trigger_day" IS '调度-时间';
COMMENT ON COLUMN "public"."xxl_job_log_report"."running_count" IS '运行中-日志数量';
COMMENT ON COLUMN "public"."xxl_job_log_report"."suc_count" IS '执行成功-日志数量';
COMMENT ON COLUMN "public"."xxl_job_log_report"."fail_count" IS '执行失败-日志数量';

-- ----------------------------
-- Records of xxl_job_log_report
-- ----------------------------
INSERT INTO "public"."xxl_job_log_report" VALUES (1, '2024-04-07 00:00:00', 0, 0, 0, NULL);
INSERT INTO "public"."xxl_job_log_report" VALUES (2, '2024-04-06 00:00:00', 0, 0, 0, NULL);
INSERT INTO "public"."xxl_job_log_report" VALUES (3, '2024-04-05 00:00:00', 0, 0, 0, NULL);
INSERT INTO "public"."xxl_job_log_report" VALUES (4, '2024-04-11 00:00:00', 0, 0, 0, NULL);
INSERT INTO "public"."xxl_job_log_report" VALUES (5, '2024-04-10 00:00:00', 0, 0, 0, NULL);
INSERT INTO "public"."xxl_job_log_report" VALUES (6, '2024-04-09 00:00:00', 0, 0, 0, NULL);
INSERT INTO "public"."xxl_job_log_report" VALUES (7, '2024-04-13 00:00:00', 0, 0, 0, NULL);
INSERT INTO "public"."xxl_job_log_report" VALUES (8, '2024-04-12 00:00:00', 0, 0, 0, NULL);
INSERT INTO "public"."xxl_job_log_report" VALUES (9, '2024-04-14 00:00:00', 0, 0, 0, NULL);
INSERT INTO "public"."xxl_job_log_report" VALUES (10, '2024-04-18 00:00:00', 2, 0, 0, NULL);
INSERT INTO "public"."xxl_job_log_report" VALUES (11, '2024-04-17 00:00:00', 0, 0, 0, NULL);
INSERT INTO "public"."xxl_job_log_report" VALUES (12, '2024-04-16 00:00:00', 0, 0, 0, NULL);
INSERT INTO "public"."xxl_job_log_report" VALUES (13, '2024-04-20 00:00:00', 0, 0, 0, NULL);
INSERT INTO "public"."xxl_job_log_report" VALUES (14, '2024-04-19 00:00:00', 0, 0, 0, NULL);
INSERT INTO "public"."xxl_job_log_report" VALUES (15, '2024-04-24 00:00:00', 0, 0, 0, NULL);
INSERT INTO "public"."xxl_job_log_report" VALUES (16, '2024-04-23 00:00:00', 0, 0, 0, NULL);
INSERT INTO "public"."xxl_job_log_report" VALUES (17, '2024-04-22 00:00:00', 0, 0, 0, NULL);
INSERT INTO "public"."xxl_job_log_report" VALUES (18, '2024-04-25 00:00:00', 0, 0, 0, NULL);
INSERT INTO "public"."xxl_job_log_report" VALUES (19, '2024-04-26 00:00:00', 0, 0, 0, NULL);
INSERT INTO "public"."xxl_job_log_report" VALUES (20, '2024-04-27 00:00:00', 2, 0, 0, NULL);
INSERT INTO "public"."xxl_job_log_report" VALUES (21, '2024-04-28 00:00:00', 0, 0, 0, NULL);
INSERT INTO "public"."xxl_job_log_report" VALUES (22, '2024-04-29 00:00:00', 2, 0, 0, NULL);
INSERT INTO "public"."xxl_job_log_report" VALUES (23, '2024-04-30 00:00:00', 2, 0, 0, NULL);

-- ----------------------------
-- Table structure for xxl_job_logglue
-- ----------------------------
DROP TABLE IF EXISTS "public"."xxl_job_logglue";
CREATE TABLE "public"."xxl_job_logglue" (
											"id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
												INCREMENT 1
												MINVALUE  1
												MAXVALUE 2147483647
												START 1
												CACHE 1
												),
											"job_id" int4 NOT NULL,
											"glue_type" varchar(50) COLLATE "pg_catalog"."default",
											"glue_source" text COLLATE "pg_catalog"."default",
											"glue_remark" varchar(128) COLLATE "pg_catalog"."default" NOT NULL,
											"add_time" timestamp(6),
											"update_time" timestamp(6)
)
;
COMMENT ON COLUMN "public"."xxl_job_logglue"."job_id" IS '任务，主键ID';
COMMENT ON COLUMN "public"."xxl_job_logglue"."glue_type" IS 'GLUE类型';
COMMENT ON COLUMN "public"."xxl_job_logglue"."glue_source" IS 'GLUE源代码';
COMMENT ON COLUMN "public"."xxl_job_logglue"."glue_remark" IS 'GLUE备注';

-- ----------------------------
-- Records of xxl_job_logglue
-- ----------------------------

-- ----------------------------
-- Table structure for xxl_job_registry
-- ----------------------------
DROP TABLE IF EXISTS "public"."xxl_job_registry";
CREATE TABLE "public"."xxl_job_registry" (
											 "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
												 INCREMENT 1
												 MINVALUE  1
												 MAXVALUE 2147483647
												 START 1
												 CACHE 1
												 ),
											 "registry_group" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
											 "registry_key" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
											 "registry_value" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
											 "update_time" timestamp(6)
)
;

-- ----------------------------
-- Records of xxl_job_registry
-- ----------------------------
INSERT INTO "public"."xxl_job_registry" VALUES (70, 'EXECUTOR', 'laokou-auth', 'http://192.168.30.1:10000/', '2024-04-30 01:12:11');
INSERT INTO "public"."xxl_job_registry" VALUES (72, 'EXECUTOR', 'laokou-admin', 'http://192.168.30.1:9999/', '2024-04-30 01:12:11');

-- ----------------------------
-- Table structure for xxl_job_user
-- ----------------------------
DROP TABLE IF EXISTS "public"."xxl_job_user";
CREATE TABLE "public"."xxl_job_user" (
										 "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
											 INCREMENT 1
											 MINVALUE  1
											 MAXVALUE 2147483647
											 START 1
											 CACHE 1
											 ),
										 "username" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
										 "password" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
										 "role" int2 NOT NULL,
										 "permission" varchar(255) COLLATE "pg_catalog"."default"
)
;
COMMENT ON COLUMN "public"."xxl_job_user"."username" IS '账号';
COMMENT ON COLUMN "public"."xxl_job_user"."password" IS '密码';
COMMENT ON COLUMN "public"."xxl_job_user"."role" IS '角色：0-普通用户、1-管理员';
COMMENT ON COLUMN "public"."xxl_job_user"."permission" IS '权限：执行器ID列表，多个逗号分割';

-- ----------------------------
-- Records of xxl_job_user
-- ----------------------------
INSERT INTO "public"."xxl_job_user" VALUES (1, 'admin', '653ef328fde361f0f2977b7ce8bc08f6', 1, NULL);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."xxl_job_group_id_seq"
OWNED BY "public"."xxl_job_group"."id";
SELECT setval('"public"."xxl_job_group_id_seq"', 4, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."xxl_job_info_id_seq"
OWNED BY "public"."xxl_job_info"."id";
SELECT setval('"public"."xxl_job_info_id_seq"', 7, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."xxl_job_log_id_seq"
OWNED BY "public"."xxl_job_log"."id";
SELECT setval('"public"."xxl_job_log_id_seq"', 8, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."xxl_job_log_report_id_seq"
OWNED BY "public"."xxl_job_log_report"."id";
SELECT setval('"public"."xxl_job_log_report_id_seq"', 23, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."xxl_job_logglue_id_seq"
OWNED BY "public"."xxl_job_logglue"."id";
SELECT setval('"public"."xxl_job_logglue_id_seq"', 1, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."xxl_job_registry_id_seq"
OWNED BY "public"."xxl_job_registry"."id";
SELECT setval('"public"."xxl_job_registry_id_seq"', 72, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."xxl_job_user_id_seq"
OWNED BY "public"."xxl_job_user"."id";
SELECT setval('"public"."xxl_job_user_id_seq"', 1, true);

-- ----------------------------
-- Indexes structure for table flyway_schema_history
-- ----------------------------
CREATE INDEX "flyway_schema_history_success_idx" ON "public"."flyway_schema_history" USING btree (
	"success" "pg_catalog"."int2_ops" ASC NULLS LAST
	);

-- ----------------------------
-- Primary Key structure for table flyway_schema_history
-- ----------------------------
ALTER TABLE "public"."flyway_schema_history" ADD CONSTRAINT "flyway_schema_history_pkey" PRIMARY KEY ("installed_rank");

-- ----------------------------
-- Auto increment value for xxl_job_group
-- ----------------------------
SELECT setval('"public"."xxl_job_group_id_seq"', 4, true);

-- ----------------------------
-- Primary Key structure for table xxl_job_group
-- ----------------------------
ALTER TABLE "public"."xxl_job_group" ADD CONSTRAINT "xxl_job_group_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for xxl_job_info
-- ----------------------------
SELECT setval('"public"."xxl_job_info_id_seq"', 7, true);

-- ----------------------------
-- Primary Key structure for table xxl_job_info
-- ----------------------------
ALTER TABLE "public"."xxl_job_info" ADD CONSTRAINT "xxl_job_info_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table xxl_job_lock
-- ----------------------------
ALTER TABLE "public"."xxl_job_lock" ADD CONSTRAINT "xxl_job_lock_pkey" PRIMARY KEY ("lock_name");

-- ----------------------------
-- Auto increment value for xxl_job_log
-- ----------------------------
SELECT setval('"public"."xxl_job_log_id_seq"', 8, true);

-- ----------------------------
-- Indexes structure for table xxl_job_log
-- ----------------------------
CREATE INDEX "xxl_job_log_handle_code_idx" ON "public"."xxl_job_log" USING btree (
	"handle_code" "pg_catalog"."int4_ops" ASC NULLS LAST
	);
CREATE INDEX "xxl_job_log_trigger_time_idx" ON "public"."xxl_job_log" USING btree (
	"trigger_time" "pg_catalog"."timestamp_ops" ASC NULLS LAST
	);

-- ----------------------------
-- Primary Key structure for table xxl_job_log
-- ----------------------------
ALTER TABLE "public"."xxl_job_log" ADD CONSTRAINT "xxl_job_log_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for xxl_job_log_report
-- ----------------------------
SELECT setval('"public"."xxl_job_log_report_id_seq"', 23, true);

-- ----------------------------
-- Indexes structure for table xxl_job_log_report
-- ----------------------------
CREATE UNIQUE INDEX "xxl_job_log_report_trigger_day_idx" ON "public"."xxl_job_log_report" USING btree (
	"trigger_day" "pg_catalog"."timestamp_ops" ASC NULLS LAST
	);

-- ----------------------------
-- Primary Key structure for table xxl_job_log_report
-- ----------------------------
ALTER TABLE "public"."xxl_job_log_report" ADD CONSTRAINT "xxl_job_log_report_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for xxl_job_logglue
-- ----------------------------
SELECT setval('"public"."xxl_job_logglue_id_seq"', 1, false);

-- ----------------------------
-- Primary Key structure for table xxl_job_logglue
-- ----------------------------
ALTER TABLE "public"."xxl_job_logglue" ADD CONSTRAINT "xxl_job_logglue_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for xxl_job_registry
-- ----------------------------
SELECT setval('"public"."xxl_job_registry_id_seq"', 72, true);

-- ----------------------------
-- Indexes structure for table xxl_job_registry
-- ----------------------------
CREATE INDEX "xxl_job_registry_registry_group_registry_key_registry_value_idx" ON "public"."xxl_job_registry" USING btree (
	"registry_group" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
	"registry_key" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
	"registry_value" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
	);

-- ----------------------------
-- Primary Key structure for table xxl_job_registry
-- ----------------------------
ALTER TABLE "public"."xxl_job_registry" ADD CONSTRAINT "xxl_job_registry_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for xxl_job_user
-- ----------------------------
SELECT setval('"public"."xxl_job_user_id_seq"', 1, true);

-- ----------------------------
-- Indexes structure for table xxl_job_user
-- ----------------------------
CREATE UNIQUE INDEX "xxl_job_user_username_idx" ON "public"."xxl_job_user" USING btree (
	"username" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
	);

-- ----------------------------
-- Primary Key structure for table xxl_job_user
-- ----------------------------
ALTER TABLE "public"."xxl_job_user" ADD CONSTRAINT "xxl_job_user_pkey" PRIMARY KEY ("id");
