/*
 Navicat Premium Dump SQL

 Source Server         : 127.0.0.1
 Source Server Type    : PostgreSQL
 Source Server Version : 160002 (160002)
 Source Host           : 127.0.0.1:5432
 Source Catalog        : kcloud_platform_generator
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 160002 (160002)
 File Encoding         : 65001

 Date: 08/11/2024 10:29:12
*/


-- ----------------------------
-- Sequence structure for boot_generator_column_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."boot_generator_column_id_seq";
CREATE SEQUENCE "public"."boot_generator_column_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for boot_generator_info_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."boot_generator_info_id_seq";
CREATE SEQUENCE "public"."boot_generator_info_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for boot_generator_template_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."boot_generator_template_id_seq";
CREATE SEQUENCE "public"."boot_generator_template_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Table structure for boot_generator_column
-- ----------------------------
DROP TABLE IF EXISTS "public"."boot_generator_column";
CREATE TABLE "public"."boot_generator_column" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "creator" int8 NOT NULL DEFAULT 0,
  "editor" int8 NOT NULL DEFAULT 0,
  "create_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "del_flag" int2 NOT NULL DEFAULT 0,
  "version" int4 NOT NULL DEFAULT 0,
  "tenant_id" int8 NOT NULL DEFAULT 0,
  "name" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
  "comment" varchar(400) COLLATE "pg_catalog"."default",
  "type" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
  "required_flag" int2 NOT NULL,
  "save_flag" int2 NOT NULL,
  "modify_flag" int2 NOT NULL,
  "query_flag" int2 NOT NULL,
  "page_flag" int2 NOT NULL,
  "query_type" varchar(50) COLLATE "pg_catalog"."default",
  "component_type" varchar(50) COLLATE "pg_catalog"."default",
  "dict_type" varchar(50) COLLATE "pg_catalog"."default",
  "field_name" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
  "field_type" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
  "info_id" int8 NOT NULL
)
;
COMMENT ON COLUMN "public"."boot_generator_column"."id" IS 'ID';
COMMENT ON COLUMN "public"."boot_generator_column"."creator" IS '创建人';
COMMENT ON COLUMN "public"."boot_generator_column"."editor" IS '编辑人';
COMMENT ON COLUMN "public"."boot_generator_column"."create_time" IS '创建时间';
COMMENT ON COLUMN "public"."boot_generator_column"."update_time" IS '修改时间';
COMMENT ON COLUMN "public"."boot_generator_column"."del_flag" IS '删除标识 0未删除 1已删除';
COMMENT ON COLUMN "public"."boot_generator_column"."version" IS '版本号';
COMMENT ON COLUMN "public"."boot_generator_column"."tenant_id" IS '租户ID';
COMMENT ON COLUMN "public"."boot_generator_column"."name" IS '列名';
COMMENT ON COLUMN "public"."boot_generator_column"."comment" IS '描述';
COMMENT ON COLUMN "public"."boot_generator_column"."type" IS '类型';
COMMENT ON COLUMN "public"."boot_generator_column"."required_flag" IS '必填标识 0否 1是';
COMMENT ON COLUMN "public"."boot_generator_column"."save_flag" IS '保存标识 0否 1是';
COMMENT ON COLUMN "public"."boot_generator_column"."modify_flag" IS '修改标识 0否 1是';
COMMENT ON COLUMN "public"."boot_generator_column"."query_flag" IS '查询标识 0否 1是';
COMMENT ON COLUMN "public"."boot_generator_column"."page_flag" IS '分页标识 0否 1是';
COMMENT ON COLUMN "public"."boot_generator_column"."query_type" IS '查询类型';
COMMENT ON COLUMN "public"."boot_generator_column"."component_type" IS '组件类型';
COMMENT ON COLUMN "public"."boot_generator_column"."dict_type" IS '字典类型';
COMMENT ON COLUMN "public"."boot_generator_column"."field_name" IS '字段名称';
COMMENT ON COLUMN "public"."boot_generator_column"."field_type" IS '字段类型';
COMMENT ON COLUMN "public"."boot_generator_column"."info_id" IS '代码生成信息ID';
COMMENT ON TABLE "public"."boot_generator_column" IS '代码生成器字段';

-- ----------------------------
-- Records of boot_generator_column
-- ----------------------------

-- ----------------------------
-- Table structure for boot_generator_info
-- ----------------------------
DROP TABLE IF EXISTS "public"."boot_generator_info";
CREATE TABLE "public"."boot_generator_info" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "creator" int8 NOT NULL DEFAULT 0,
  "editor" int8 NOT NULL DEFAULT 0,
  "create_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "del_flag" int2 NOT NULL DEFAULT 0,
  "version" int4 NOT NULL DEFAULT 0,
  "tenant_id" int8 NOT NULL DEFAULT 0
)
;
COMMENT ON COLUMN "public"."boot_generator_info"."id" IS 'ID';
COMMENT ON COLUMN "public"."boot_generator_info"."creator" IS '创建人';
COMMENT ON COLUMN "public"."boot_generator_info"."editor" IS '编辑人';
COMMENT ON COLUMN "public"."boot_generator_info"."create_time" IS '创建时间';
COMMENT ON COLUMN "public"."boot_generator_info"."update_time" IS '修改时间';
COMMENT ON COLUMN "public"."boot_generator_info"."del_flag" IS '删除标识 0未删除 1已删除';
COMMENT ON COLUMN "public"."boot_generator_info"."version" IS '版本号';
COMMENT ON COLUMN "public"."boot_generator_info"."tenant_id" IS '租户ID';
COMMENT ON TABLE "public"."boot_generator_info" IS '代码生成器信息';

-- ----------------------------
-- Records of boot_generator_info
-- ----------------------------

-- ----------------------------
-- Table structure for boot_generator_template
-- ----------------------------
DROP TABLE IF EXISTS "public"."boot_generator_template";
CREATE TABLE "public"."boot_generator_template" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "creator" int8 NOT NULL DEFAULT 0,
  "editor" int8 NOT NULL DEFAULT 0,
  "create_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "del_flag" int2 NOT NULL DEFAULT 0,
  "version" int4 NOT NULL DEFAULT 0,
  "tenant_id" int8 NOT NULL DEFAULT 0
)
;
COMMENT ON COLUMN "public"."boot_generator_template"."id" IS 'ID';
COMMENT ON COLUMN "public"."boot_generator_template"."creator" IS '创建人';
COMMENT ON COLUMN "public"."boot_generator_template"."editor" IS '编辑人';
COMMENT ON COLUMN "public"."boot_generator_template"."create_time" IS '创建时间';
COMMENT ON COLUMN "public"."boot_generator_template"."update_time" IS '修改时间';
COMMENT ON COLUMN "public"."boot_generator_template"."del_flag" IS '删除标识 0未删除 1已删除';
COMMENT ON COLUMN "public"."boot_generator_template"."version" IS '版本号';
COMMENT ON COLUMN "public"."boot_generator_template"."tenant_id" IS '租户ID';
COMMENT ON TABLE "public"."boot_generator_template" IS '代码生成器模板';

-- ----------------------------
-- Records of boot_generator_template
-- ----------------------------

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."boot_generator_column_id_seq"
OWNED BY "public"."boot_generator_column"."id";
SELECT setval('"public"."boot_generator_column_id_seq"', 1, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."boot_generator_info_id_seq"
OWNED BY "public"."boot_generator_info"."id";
SELECT setval('"public"."boot_generator_info_id_seq"', 1, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."boot_generator_template_id_seq"
OWNED BY "public"."boot_generator_template"."id";
SELECT setval('"public"."boot_generator_template_id_seq"', 1, false);

-- ----------------------------
-- Auto increment value for boot_generator_column
-- ----------------------------
SELECT setval('"public"."boot_generator_column_id_seq"', 1, false);

-- ----------------------------
-- Auto increment value for boot_generator_info
-- ----------------------------
SELECT setval('"public"."boot_generator_info_id_seq"', 1, false);

-- ----------------------------
-- Auto increment value for boot_generator_template
-- ----------------------------
SELECT setval('"public"."boot_generator_template_id_seq"', 1, false);
