/*
 Navicat Premium Dump SQL

 Source Server         : 127.0.0.1
 Source Server Type    : PostgreSQL
 Source Server Version : 160003 (160003)
 Source Host           : 127.0.0.1:5432
 Source Catalog        : kcloud_platform_nacos
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 160003 (160003)
 File Encoding         : 65001

 Date: 30/12/2024 23:27:10
*/


-- ----------------------------
-- Table structure for users
-- ----------------------------
DROP TABLE IF EXISTS "public"."users";
CREATE TABLE "public"."users" (
  "username" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
  "password" varchar(500) COLLATE "pg_catalog"."default" NOT NULL,
  "enabled" bool NOT NULL DEFAULT true
)
;

-- ----------------------------
-- Records of users
-- ----------------------------
INSERT INTO "public"."users" VALUES ('laokou', '$2a$10$75WIn2J5FoX9F5wEBdFsL.0cKdv5h8QqBMKMWBABhWAxKB4TO8WZq', 'f');
INSERT INTO "public"."users" VALUES ('nacos', '$2a$10$oVX1zRtaql9Jbsyzaaovx.TU2M6Bw0ZpCbPYWOIED58d1ougzaFRm', 'f');

-- ----------------------------
-- Table structure for tenant_info
-- ----------------------------
DROP TABLE IF EXISTS "public"."tenant_info";
CREATE TABLE "public"."tenant_info" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "kp" varchar(128) COLLATE "pg_catalog"."default" NOT NULL,
  "tenant_id" varchar(128) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "tenant_name" varchar(128) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "tenant_desc" varchar(256) COLLATE "pg_catalog"."default",
  "create_source" varchar(32) COLLATE "pg_catalog"."default",
  "gmt_create" int8 NOT NULL,
  "gmt_modified" int8 NOT NULL
)
;
COMMENT ON COLUMN "public"."tenant_info"."id" IS 'id';
COMMENT ON COLUMN "public"."tenant_info"."kp" IS 'kp';
COMMENT ON COLUMN "public"."tenant_info"."tenant_id" IS 'tenant_id';
COMMENT ON COLUMN "public"."tenant_info"."tenant_name" IS 'tenant_name';
COMMENT ON COLUMN "public"."tenant_info"."tenant_desc" IS 'tenant_desc';
COMMENT ON COLUMN "public"."tenant_info"."create_source" IS 'create_source';
COMMENT ON COLUMN "public"."tenant_info"."gmt_create" IS '创建时间';
COMMENT ON COLUMN "public"."tenant_info"."gmt_modified" IS '修改时间';
COMMENT ON TABLE "public"."tenant_info" IS 'tenant_info';

-- ----------------------------
-- Records of tenant_info
-- ----------------------------
INSERT INTO "public"."tenant_info" VALUES (2, '1', 'a61abd4c-ef96-42a5-99a1-616adee531f3', 'test', 'test', 'nacos', 1673556960289, 1716628319164);
INSERT INTO "public"."tenant_info" VALUES (1, '1', '0dac1a68-2f01-40df-bd26-bf0cb199057a', 'dev', 'dev', 'nacos', 1716631648356, 1716631648356);
INSERT INTO "public"."tenant_info" VALUES (3, '1', '8140e92b-fb43-48f5-b63b-7506185206a5', 'prod', 'prod', 'nacos', 1716631657328, 1716631657328);

-- ----------------------------
-- Table structure for tenant_capacity
-- ----------------------------
DROP TABLE IF EXISTS "public"."tenant_capacity";
CREATE TABLE "public"."tenant_capacity" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "tenant_id" varchar(128) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "quota" int8 NOT NULL DEFAULT 0,
  "usage" int8 NOT NULL DEFAULT 0,
  "max_size" int8 NOT NULL DEFAULT 0,
  "max_aggr_count" int8 NOT NULL DEFAULT 0,
  "max_aggr_size" int8 NOT NULL DEFAULT 0,
  "max_history_count" int8 NOT NULL DEFAULT 0,
  "gmt_create" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "gmt_modified" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
)
;
COMMENT ON COLUMN "public"."tenant_capacity"."id" IS '主键ID';
COMMENT ON COLUMN "public"."tenant_capacity"."tenant_id" IS 'Tenant ID';
COMMENT ON COLUMN "public"."tenant_capacity"."quota" IS '配额，0表示使用默认值';
COMMENT ON COLUMN "public"."tenant_capacity"."usage" IS '使用量';
COMMENT ON COLUMN "public"."tenant_capacity"."max_size" IS '单个配置大小上限，单位为字节，0表示使用默认值';
COMMENT ON COLUMN "public"."tenant_capacity"."max_aggr_count" IS '聚合子配置最大个数';
COMMENT ON COLUMN "public"."tenant_capacity"."max_aggr_size" IS '单个聚合数据的子配置大小上限，单位为字节，0表示使用默认值';
COMMENT ON COLUMN "public"."tenant_capacity"."max_history_count" IS '最大变更历史数量';
COMMENT ON COLUMN "public"."tenant_capacity"."gmt_create" IS '创建时间';
COMMENT ON COLUMN "public"."tenant_capacity"."gmt_modified" IS '修改时间';
COMMENT ON TABLE "public"."tenant_capacity" IS '租户容量信息表';

-- ----------------------------
-- Records of tenant_capacity
-- ----------------------------

-- ----------------------------
-- Table structure for roles
-- ----------------------------
DROP TABLE IF EXISTS "public"."roles";
CREATE TABLE "public"."roles" (
  "username" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
  "role" varchar(50) COLLATE "pg_catalog"."default" NOT NULL
)
;

-- ----------------------------
-- Records of roles
-- ----------------------------
INSERT INTO "public"."roles" VALUES ('laokou', 'ADMIN');
INSERT INTO "public"."roles" VALUES ('nacos', 'ROLE_ADMIN');

-- ----------------------------
-- Table structure for permissions
-- ----------------------------
DROP TABLE IF EXISTS "public"."permissions";
CREATE TABLE "public"."permissions" (
  "role" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
  "resource" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "action" varchar(8) COLLATE "pg_catalog"."default" NOT NULL
)
;

-- ----------------------------
-- Records of permissions
-- ----------------------------
INSERT INTO "public"."permissions" VALUES ('ADMIN', ':*:*', 'rw');
INSERT INTO "public"."permissions" VALUES ('ADMIN', 'a61abd4c-ef96-42a5-99a1-616adee531f3:*:*', 'rw');
INSERT INTO "public"."permissions" VALUES ('ROLE_ADMIN', ':*:*', 'rw');
INSERT INTO "public"."permissions" VALUES ('ROLE_ADMIN', 'a61abd4c-ef96-42a5-99a1-616adee531f3:*:*', 'rw');

-- ----------------------------
-- Table structure for his_config_info
-- ----------------------------
DROP TABLE IF EXISTS "public"."his_config_info";
CREATE TABLE "public"."his_config_info" (
  "id" int8 NOT NULL,
  "nid" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "data_id" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "group_id" varchar(128) COLLATE "pg_catalog"."default" NOT NULL,
  "app_name" varchar(128) COLLATE "pg_catalog"."default",
  "content" text COLLATE "pg_catalog"."default" NOT NULL,
  "md5" varchar(32) COLLATE "pg_catalog"."default",
  "gmt_create" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "gmt_modified" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "src_user" text COLLATE "pg_catalog"."default",
  "src_ip" varchar(50) COLLATE "pg_catalog"."default",
  "op_type" char(10) COLLATE "pg_catalog"."default",
  "tenant_id" varchar(128) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "encrypted_data_key" text COLLATE "pg_catalog"."default" NOT NULL,
  "publish_type" varchar(50) COLLATE "pg_catalog"."default" NOT NULL default 'formal',
	"gray_name" varchar(128) COLLATE "pg_catalog"."default",
	"ext_info" text COLLATE "pg_catalog"."default"
)
;
COMMENT ON COLUMN "public"."his_config_info"."id" IS 'id';
COMMENT ON COLUMN "public"."his_config_info"."nid" IS 'nid';
COMMENT ON COLUMN "public"."his_config_info"."data_id" IS 'data_id';
COMMENT ON COLUMN "public"."his_config_info"."group_id" IS 'group_id';
COMMENT ON COLUMN "public"."his_config_info"."app_name" IS 'app_name';
COMMENT ON COLUMN "public"."his_config_info"."content" IS 'content';
COMMENT ON COLUMN "public"."his_config_info"."md5" IS 'md5';
COMMENT ON COLUMN "public"."his_config_info"."gmt_create" IS '创建时间';
COMMENT ON COLUMN "public"."his_config_info"."gmt_modified" IS '修改时间';
COMMENT ON COLUMN "public"."his_config_info"."src_user" IS 'source user';
COMMENT ON COLUMN "public"."his_config_info"."src_ip" IS 'source ip';
COMMENT ON COLUMN "public"."his_config_info"."op_type" IS 'operation type';
COMMENT ON COLUMN "public"."his_config_info"."tenant_id" IS '租户字段';
COMMENT ON COLUMN "public"."his_config_info"."encrypted_data_key" IS '秘钥';
COMMENT ON COLUMN "public"."his_config_info"."publish_type" IS 'publish type gray or formal';
COMMENT ON COLUMN "public"."his_config_info"."gray_name" IS 'gray name';
COMMENT ON COLUMN "public"."his_config_info"."ext_info" IS 'ext info';
COMMENT ON TABLE "public"."his_config_info" IS '多租户改造';

-- ----------------------------
-- Records of his_config_info
-- ----------------------------

-- ----------------------------
-- Table structure for group_capacity
-- ----------------------------
DROP TABLE IF EXISTS "public"."group_capacity";
CREATE TABLE "public"."group_capacity" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "group_id" varchar(128) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "quota" int8 NOT NULL DEFAULT 0,
  "usage" int8 NOT NULL DEFAULT 0,
  "max_size" int8 NOT NULL DEFAULT 0,
  "max_aggr_count" int8 NOT NULL DEFAULT 0,
  "max_aggr_size" int8 NOT NULL DEFAULT 0,
  "max_history_count" int8 NOT NULL DEFAULT 0,
  "gmt_create" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "gmt_modified" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
)
;
COMMENT ON COLUMN "public"."group_capacity"."id" IS '主键ID';
COMMENT ON COLUMN "public"."group_capacity"."group_id" IS 'Group ID，空字符表示整个集群';
COMMENT ON COLUMN "public"."group_capacity"."quota" IS '配额，0表示使用默认值';
COMMENT ON COLUMN "public"."group_capacity"."usage" IS '使用量';
COMMENT ON COLUMN "public"."group_capacity"."max_size" IS '单个配置大小上限，单位为字节，0表示使用默认值';
COMMENT ON COLUMN "public"."group_capacity"."max_aggr_count" IS '聚合子配置最大个数，，0表示使用默认值';
COMMENT ON COLUMN "public"."group_capacity"."max_aggr_size" IS '单个聚合数据的子配置大小上限，单位为字节，0表示使用默认值';
COMMENT ON COLUMN "public"."group_capacity"."max_history_count" IS '最大变更历史数量';
COMMENT ON COLUMN "public"."group_capacity"."gmt_create" IS '创建时间';
COMMENT ON COLUMN "public"."group_capacity"."gmt_modified" IS '修改时间';
COMMENT ON TABLE "public"."group_capacity" IS '集群、各Group容量信息表';

-- ----------------------------
-- Records of group_capacity
-- ----------------------------

-- ----------------------------
-- Table structure for databasechangeloglock
-- ----------------------------
DROP TABLE IF EXISTS "public"."databasechangeloglock";
CREATE TABLE "public"."databasechangeloglock" (
  "id" int4 NOT NULL,
  "locked" bool NOT NULL,
  "lockgranted" timestamp(6),
  "lockedby" varchar(255) COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Records of databasechangeloglock
-- ----------------------------
INSERT INTO "public"."databasechangeloglock" VALUES (1, 'f', NULL, NULL);

-- ----------------------------
-- Table structure for databasechangelog
-- ----------------------------
DROP TABLE IF EXISTS "public"."databasechangelog";
CREATE TABLE "public"."databasechangelog" (
  "id" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "author" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "filename" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "dateexecuted" timestamp(6) NOT NULL,
  "orderexecuted" int4 NOT NULL,
  "exectype" varchar(10) COLLATE "pg_catalog"."default" NOT NULL,
  "md5sum" varchar(35) COLLATE "pg_catalog"."default",
  "description" varchar(255) COLLATE "pg_catalog"."default",
  "comments" varchar(255) COLLATE "pg_catalog"."default",
  "tag" varchar(255) COLLATE "pg_catalog"."default",
  "liquibase" varchar(20) COLLATE "pg_catalog"."default",
  "contexts" varchar(255) COLLATE "pg_catalog"."default",
  "labels" varchar(255) COLLATE "pg_catalog"."default",
  "deployment_id" varchar(10) COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Records of databasechangelog
-- ----------------------------

-- ----------------------------
-- Table structure for config_tags_relation
-- ----------------------------
DROP TABLE IF EXISTS "public"."config_tags_relation";
CREATE TABLE "public"."config_tags_relation" (
  "id" int8 NOT NULL,
  "tag_name" varchar(128) COLLATE "pg_catalog"."default" NOT NULL,
  "tag_type" varchar(64) COLLATE "pg_catalog"."default",
  "data_id" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "group_id" varchar(128) COLLATE "pg_catalog"."default" NOT NULL,
  "tenant_id" varchar(128) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "nid" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
)
)
;
COMMENT ON COLUMN "public"."config_tags_relation"."id" IS 'id';
COMMENT ON COLUMN "public"."config_tags_relation"."tag_name" IS 'tag_name';
COMMENT ON COLUMN "public"."config_tags_relation"."tag_type" IS 'tag_type';
COMMENT ON COLUMN "public"."config_tags_relation"."data_id" IS 'data_id';
COMMENT ON COLUMN "public"."config_tags_relation"."group_id" IS 'group_id';
COMMENT ON COLUMN "public"."config_tags_relation"."tenant_id" IS 'tenant_id';
COMMENT ON TABLE "public"."config_tags_relation" IS 'config_tag_relation';

-- ----------------------------
-- Records of config_tags_relation
-- ----------------------------

-- ----------------------------
-- Table structure for config_info_tag
-- ----------------------------
DROP TABLE IF EXISTS "public"."config_info_tag";
CREATE TABLE "public"."config_info_tag" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "data_id" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "group_id" varchar(128) COLLATE "pg_catalog"."default" NOT NULL,
  "tenant_id" varchar(128) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "tag_id" varchar(128) COLLATE "pg_catalog"."default" NOT NULL,
  "app_name" varchar(128) COLLATE "pg_catalog"."default",
  "content" text COLLATE "pg_catalog"."default" NOT NULL,
  "md5" varchar(32) COLLATE "pg_catalog"."default",
  "gmt_create" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "gmt_modified" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "src_user" text COLLATE "pg_catalog"."default",
  "src_ip" varchar(50) COLLATE "pg_catalog"."default"
)
;
COMMENT ON COLUMN "public"."config_info_tag"."id" IS 'id';
COMMENT ON COLUMN "public"."config_info_tag"."data_id" IS 'data_id';
COMMENT ON COLUMN "public"."config_info_tag"."group_id" IS 'group_id';
COMMENT ON COLUMN "public"."config_info_tag"."tenant_id" IS 'tenant_id';
COMMENT ON COLUMN "public"."config_info_tag"."tag_id" IS 'tag_id';
COMMENT ON COLUMN "public"."config_info_tag"."app_name" IS 'app_name';
COMMENT ON COLUMN "public"."config_info_tag"."content" IS 'content';
COMMENT ON COLUMN "public"."config_info_tag"."md5" IS 'md5';
COMMENT ON COLUMN "public"."config_info_tag"."gmt_create" IS '创建时间';
COMMENT ON COLUMN "public"."config_info_tag"."gmt_modified" IS '修改时间';
COMMENT ON COLUMN "public"."config_info_tag"."src_user" IS 'source user';
COMMENT ON COLUMN "public"."config_info_tag"."src_ip" IS 'source ip';
COMMENT ON TABLE "public"."config_info_tag" IS 'config_info_tag';

-- ----------------------------
-- Records of config_info_tag
-- ----------------------------

-- ----------------------------
-- Table structure for config_info_beta
-- ----------------------------
DROP TABLE IF EXISTS "public"."config_info_beta";
CREATE TABLE "public"."config_info_beta" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "data_id" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "group_id" varchar(128) COLLATE "pg_catalog"."default" NOT NULL,
  "app_name" varchar(128) COLLATE "pg_catalog"."default",
  "content" text COLLATE "pg_catalog"."default" NOT NULL,
  "beta_ips" varchar(1024) COLLATE "pg_catalog"."default",
  "md5" varchar(32) COLLATE "pg_catalog"."default",
  "gmt_create" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "gmt_modified" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "src_user" text COLLATE "pg_catalog"."default",
  "src_ip" varchar(50) COLLATE "pg_catalog"."default",
  "tenant_id" varchar(128) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "encrypted_data_key" text COLLATE "pg_catalog"."default" NOT NULL
)
;
COMMENT ON COLUMN "public"."config_info_beta"."id" IS 'id';
COMMENT ON COLUMN "public"."config_info_beta"."data_id" IS 'data_id';
COMMENT ON COLUMN "public"."config_info_beta"."group_id" IS 'group_id';
COMMENT ON COLUMN "public"."config_info_beta"."app_name" IS 'app_name';
COMMENT ON COLUMN "public"."config_info_beta"."content" IS 'content';
COMMENT ON COLUMN "public"."config_info_beta"."beta_ips" IS 'betaIps';
COMMENT ON COLUMN "public"."config_info_beta"."md5" IS 'md5';
COMMENT ON COLUMN "public"."config_info_beta"."gmt_create" IS '创建时间';
COMMENT ON COLUMN "public"."config_info_beta"."gmt_modified" IS '修改时间';
COMMENT ON COLUMN "public"."config_info_beta"."src_user" IS 'source user';
COMMENT ON COLUMN "public"."config_info_beta"."src_ip" IS 'source ip';
COMMENT ON COLUMN "public"."config_info_beta"."tenant_id" IS '租户字段';
COMMENT ON COLUMN "public"."config_info_beta"."encrypted_data_key" IS '秘钥';
COMMENT ON TABLE "public"."config_info_beta" IS 'config_info_beta';

-- ----------------------------
-- Records of config_info_beta
-- ----------------------------

-- ----------------------------
-- Table structure for config_info_aggr
-- ----------------------------
DROP TABLE IF EXISTS "public"."config_info_aggr";
CREATE TABLE "public"."config_info_aggr" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "data_id" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "group_id" varchar(128) COLLATE "pg_catalog"."default" NOT NULL,
  "datum_id" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "content" text COLLATE "pg_catalog"."default" NOT NULL,
  "gmt_modified" timestamp(6) NOT NULL,
  "app_name" varchar(128) COLLATE "pg_catalog"."default",
  "tenant_id" varchar(128) COLLATE "pg_catalog"."default" DEFAULT ''::character varying
)
;
COMMENT ON COLUMN "public"."config_info_aggr"."id" IS 'id';
COMMENT ON COLUMN "public"."config_info_aggr"."data_id" IS 'data_id';
COMMENT ON COLUMN "public"."config_info_aggr"."group_id" IS 'group_id';
COMMENT ON COLUMN "public"."config_info_aggr"."datum_id" IS 'datum_id';
COMMENT ON COLUMN "public"."config_info_aggr"."content" IS '内容';
COMMENT ON COLUMN "public"."config_info_aggr"."gmt_modified" IS '修改时间';
COMMENT ON COLUMN "public"."config_info_aggr"."tenant_id" IS '租户字段';
COMMENT ON TABLE "public"."config_info_aggr" IS '增加租户字段';

-- ----------------------------
-- Records of config_info_aggr
-- ----------------------------

-- ----------------------------
-- Table structure for config_info
-- ----------------------------
DROP TABLE IF EXISTS "public"."config_info";
CREATE TABLE "public"."config_info" (
  "id" int8 NOT NULL GENERATED ALWAYS AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "data_id" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "group_id" varchar(128) COLLATE "pg_catalog"."default",
  "content" text COLLATE "pg_catalog"."default" NOT NULL,
  "md5" varchar(32) COLLATE "pg_catalog"."default",
  "gmt_create" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "gmt_modified" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "src_user" text COLLATE "pg_catalog"."default",
  "src_ip" varchar(50) COLLATE "pg_catalog"."default",
  "app_name" varchar(128) COLLATE "pg_catalog"."default",
  "tenant_id" varchar(128) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "c_desc" varchar(256) COLLATE "pg_catalog"."default",
  "c_use" varchar(64) COLLATE "pg_catalog"."default",
  "effect" varchar(64) COLLATE "pg_catalog"."default",
  "type" varchar(64) COLLATE "pg_catalog"."default",
  "c_schema" text COLLATE "pg_catalog"."default",
  "encrypted_data_key" text COLLATE "pg_catalog"."default" NOT NULL
)
;
COMMENT ON COLUMN "public"."config_info"."id" IS 'id';
COMMENT ON COLUMN "public"."config_info"."data_id" IS 'data_id';
COMMENT ON COLUMN "public"."config_info"."content" IS 'content';
COMMENT ON COLUMN "public"."config_info"."md5" IS 'md5';
COMMENT ON COLUMN "public"."config_info"."gmt_create" IS '创建时间';
COMMENT ON COLUMN "public"."config_info"."gmt_modified" IS '修改时间';
COMMENT ON COLUMN "public"."config_info"."src_user" IS 'source user';
COMMENT ON COLUMN "public"."config_info"."src_ip" IS 'source ip';
COMMENT ON COLUMN "public"."config_info"."app_name" IS 'app_name';
COMMENT ON COLUMN "public"."config_info"."tenant_id" IS '租户字段';
COMMENT ON COLUMN "public"."config_info"."c_desc" IS 'configuration description';
COMMENT ON COLUMN "public"."config_info"."c_use" IS 'configuration usage';
COMMENT ON COLUMN "public"."config_info"."effect" IS '配置生效的描述';
COMMENT ON COLUMN "public"."config_info"."type" IS '配置的类型';
COMMENT ON COLUMN "public"."config_info"."c_schema" IS '配置的模式';
COMMENT ON COLUMN "public"."config_info"."encrypted_data_key" IS '秘钥';
COMMENT ON TABLE "public"."config_info" IS 'config_info';

DROP TABLE IF EXISTS "public"."config_info_gray";
CREATE TABLE "public"."config_info_gray" (
	"id" numeric(20,0) NOT NULL,
	"data_id" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
	"group_id" varchar(128) COLLATE "pg_catalog"."default" NOT NULL,
	"content" text COLLATE "pg_catalog"."default" NOT NULL,
	"md5" varchar(32) COLLATE "pg_catalog"."default",
	"src_user" text COLLATE "pg_catalog"."default",
	"src_ip" varchar(100) COLLATE "pg_catalog"."default",
	"gmt_create" timestamp(6) NOT NULL,
	"gmt_modified" timestamp(6) NOT NULL,
	"app_name" varchar(128) COLLATE "pg_catalog"."default",
	"tenant_id" varchar(128) COLLATE "pg_catalog"."default",
	"gray_name" varchar(128) COLLATE "pg_catalog"."default" NOT NULL,
	"gray_rule" text COLLATE "pg_catalog"."default" NOT NULL,
	"encrypted_data_key" varchar(256) COLLATE "pg_catalog"."default" NOT NULL,
	CONSTRAINT "config_info_gray_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "idx_dataid_gmt_modified" ON "public"."config_info_gray" USING btree ("data_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,"gmt_modified" "pg_catalog"."timestamp_ops" ASC NULLS LAST);

CREATE INDEX "idx_gmt_modified" ON "public"."config_info_gray" USING btree ("gmt_modified" "pg_catalog"."timestamp_ops" ASC NULLS LAST);

CREATE UNIQUE INDEX "uk_configinfogray_datagrouptenantgray" ON "public"."config_info_gray" USING btree ("data_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,"group_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,"tenant_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,"gray_name" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST);

COMMENT ON COLUMN "public"."config_info_gray"."id" IS 'id';
COMMENT ON COLUMN "public"."config_info_gray"."data_id" IS 'data_id';
COMMENT ON COLUMN "public"."config_info_gray"."group_id" IS 'group_id';
COMMENT ON COLUMN "public"."config_info_gray"."content" IS 'content';
COMMENT ON COLUMN "public"."config_info_gray"."md5" IS 'md5';
COMMENT ON COLUMN "public"."config_info_gray"."src_user" IS 'src_user';
COMMENT ON COLUMN "public"."config_info_gray"."src_ip" IS 'src_ip';
COMMENT ON COLUMN "public"."config_info_gray"."gmt_create" IS 'gmt_create';
COMMENT ON COLUMN "public"."config_info_gray"."gmt_modified" IS 'gmt_modified';
COMMENT ON COLUMN "public"."config_info_gray"."app_name" IS 'app_name';
COMMENT ON COLUMN "public"."config_info_gray"."tenant_id" IS 'tenant_id';
COMMENT ON COLUMN "public"."config_info_gray"."gray_name" IS 'gray_name';
COMMENT ON COLUMN "public"."config_info_gray"."gray_rule" IS 'gray_rule';
COMMENT ON COLUMN "public"."config_info_gray"."encrypted_data_key" IS 'encrypted_data_key';
COMMENT ON TABLE "public"."config_info_gray" IS 'config_info_gray';

INSERT INTO "public"."config_info"  OVERRIDING SYSTEM VALUE VALUES  (20, 'admin-flow.json', 'LAOKOU_GROUP', '[
  {
    "resource": "/v3/users",
    "limitApp": "default",
    "count": 500000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/users/import",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/users/export",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/users/page",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/users/{id}",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/users/profile",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/tenants",
    "limitApp": "default",
    "count": 500000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/tenants/import",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/tenants/export",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/tenants/page",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/tenants/{id}",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/sources",
    "limitApp": "default",
    "count": 500000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/sources/import",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/sources/export",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/sources/page",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/sources/{id}",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/roles",
    "limitApp": "default",
    "count": 500000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/roles/import",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/roles/export",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/roles/page",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/roles/{id}",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/oss-logs",
    "limitApp": "default",
    "count": 500000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/oss-logs/import",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/oss-logs/export",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/oss-logs/page",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/oss-logs/{id}",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/oss",
    "limitApp": "default",
    "count": 500000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/oss/import",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/oss/export",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/oss/page",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/oss/{id}",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/operate-logs",
    "limitApp": "default",
    "count": 500000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/operate-logs/import",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/operate-logs/export",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/operate-logs/page",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/operate-logs/{id}",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/notice-logs",
    "limitApp": "default",
    "count": 500000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/notice-logs/import",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/notice-logs/export",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/notice-logs/page",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/notice-logs/{id}",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/menus",
    "limitApp": "default",
    "count": 500000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/menus/import",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/menus/export",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/menus/page",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/menus/{id}",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/login-log",
    "limitApp": "default",
    "count": 500000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/login-log/import",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/login-log/export",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/login-log/page",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/login-log/{id}",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/login-log/all",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/ips",
    "limitApp": "default",
    "count": 500000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/ips/import",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/ips/export",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/ips/page",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/ips/{id}",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/i18n-messages",
    "limitApp": "default",
    "count": 500000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/i18n-messages/import",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/i18n-messages/export",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/i18n-messages/page",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/i18n-messages/{id}",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/domain-events",
    "limitApp": "default",
    "count": 500000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/domain-events/import",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/domain-events/export",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/domain-events/page",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/domain-events/{id}",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/dicts",
    "limitApp": "default",
    "count": 500000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/dicts/import",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/dicts/export",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/dicts/page",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/dicts/{id}",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/dict-items",
    "limitApp": "default",
    "count": 500000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/dict-items/import",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/dict-items/export",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/dict-items/page",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/dict-items/{id}",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/depts",
    "limitApp": "default",
    "count": 500000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/depts/import",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/depts/export",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/depts/page",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/depts/{id}",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/clusters",
    "limitApp": "default",
    "count": 500000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/clusters/import",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/clusters/export",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/clusters/page",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/clusters/{id}",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  }
]
', '546e2d9817dd516db763f5ef3ef3a756', '2024-11-12 11:21:13.251', '2024-11-12 11:22:10.475', 'nacos', '0:0:0:0:0:0:0:1', 'laokou-admin', '8140e92b-fb43-48f5-b63b-7506185206a5', 'admin sentinel flow rule', '', '', 'json', '', '');
INSERT INTO "public"."config_info"  OVERRIDING SYSTEM VALUE VALUES  (11, 'gateway-flow.json', 'LAOKOU_GROUP', '[
  {
    "resource": "laokou-auth",
    "grade": 1,
    "count": 100000,
    "intervalSec": 1,
    "burst": 500000,
    "controlBehavior": 0
  },
  {
    "resource": "laokou-admin",
    "grade": 1,
    "count": 100000,
    "intervalSec": 1,
    "burst": 500000,
    "controlBehavior": 0
  },
  {
    "resource": "laokou-iot",
    "grade": 1,
    "count": 100000,
    "intervalSec": 1,
    "burst": 500000,
    "controlBehavior": 0
  },
  {
    "resource": "laokou-generator",
    "grade": 1,
    "count": 100000,
    "intervalSec": 1,
    "burst": 500000,
    "controlBehavior": 0
  }
]', '5e013d830e3af21e5e321c0f4910fda0', '2024-05-25 18:12:47.358', '2024-11-11 20:51:44.543', 'nacos', '0:0:0:0:0:0:0:1', 'laokou-gateway', '0dac1a68-2f01-40df-bd26-bf0cb199057a', 'gateway sentinel flow rule', '', '', 'json', '', '');
INSERT INTO "public"."config_info"  OVERRIDING SYSTEM VALUE VALUES  (12, 'seataServer.properties', 'SEATA_GROUP', '#For details about configuration items, see https://seata.io/zh-cn/docs/user/configurations.html
#Transport configuration, for client and server
transport.type=TCP
transport.server=NIO
transport.heartbeat=true
transport.enableTmClientBatchSendRequest=false
transport.enableRmClientBatchSendRequest=true
transport.enableTcServerBatchSendResponse=false
transport.rpcRmRequestTimeout=30000
transport.rpcTmRequestTimeout=30000
transport.rpcTcRequestTimeout=30000
transport.threadFactory.bossThreadPrefix=NettyBoss
transport.threadFactory.workerThreadPrefix=NettyServerNIOWorker
transport.threadFactory.serverExecutorThreadPrefix=NettyServerBizHandler
transport.threadFactory.shareBossWorker=false
transport.threadFactory.clientSelectorThreadPrefix=NettyClientSelector
transport.threadFactory.clientSelectorThreadSize=1
transport.threadFactory.clientWorkerThreadPrefix=NettyClientWorkerThread
transport.threadFactory.bossThreadSize=1
transport.threadFactory.workerThreadSize=default
transport.shutdown.wait=3
transport.serialization=seata
transport.compressor=none

#Transaction routing rules configuration, only for the client
service.vgroupMapping.default_tx_group=default
#If you use a registry, you can ignore it
service.default.grouplist=seata:8091
service.enableDegrade=false
service.disableGlobalTransaction=false

client.metadataMaxAgeMs=30000
#Transaction rule configuration, only for the client
client.rm.asyncCommitBufferLimit=10000
client.rm.lock.retryInterval=10
client.rm.lock.retryTimes=30
client.rm.lock.retryPolicyBranchRollbackOnConflict=true
client.rm.reportRetryCount=5
client.rm.tableMetaCheckEnable=true
client.rm.tableMetaCheckerInterval=60000
client.rm.sqlParserType=hikari
client.rm.reportSuccessEnable=false
client.rm.sagaBranchRegisterEnable=false
client.rm.sagaJsonParser=jackson
client.rm.tccActionInterceptorOrder=-2147482648
client.tm.commitRetryCount=5
client.tm.rollbackRetryCount=5
client.tm.defaultGlobalTransactionTimeout=60000
client.tm.degradeCheck=false
client.tm.degradeCheckAllowTimes=10
client.tm.degradeCheckPeriod=2000
client.tm.interceptorOrder=-2147482648
client.undo.dataValidation=true
client.undo.logSerialization=jackson
client.undo.onlyCareUpdateColumns=true
server.undo.logSaveDays=7
server.undo.logDeletePeriod=86400000
client.undo.logTable=undo_log
client.undo.compress.enable=true
client.undo.compress.type=zip
client.undo.compress.threshold=64k
#For TCC transaction mode
tcc.fence.logTableName=tcc_fence_log
tcc.fence.cleanPeriod=1h
# You can choose from the following options: fastjson, jackson, gson
tcc.contextJsonParserType=fastjson

#Log rule configuration, for client and server
log.exceptionRate=100

#Transaction storage configuration, only for the server. The file, db, and redis configuration values are optional.
store.mode=redis
store.lock.mode=redis
store.session.mode=redis
#Used for password encryption
store.publicKey=

#If `store.mode,store.lock.mode,store.session.mode` are not equal to `file`, you can remove the configuration block.
store.file.dir=file_store/data
store.file.maxBranchSessionSize=16384
store.file.maxGlobalSessionSize=512
store.file.fileWriteBufferCacheSize=16384
store.file.flushDiskMode=async
store.file.sessionReloadReadSize=100

#These configurations are required if the `store mode` is `db`. If `store.mode,store.lock.mode,store.session.mode` are not equal to `db`, you can remove the configuration block.
store.db.datasource=hikari
store.db.dbType=mysql
store.db.driverClassName=com.mysql.cj.jdbc.Driver
store.db.url=jdbc:mysql://mysql:3306/kcloud_platform_alibaba_seata?useUnicode=true&rewriteBatchedStatements=true
store.db.user=root
store.db.password=laokou123
store.db.minConn=5
store.db.maxConn=30
store.db.globalTable=global_table
store.db.branchTable=branch_table
store.db.distributedLockTable=distributed_lock
store.db.queryLimit=100
store.db.lockTable=lock_table
store.db.maxWait=5000

#These configurations are required if the `store mode` is `redis`. If `store.mode,store.lock.mode,store.session.mode` are not equal to `redis`, you can remove the configuration block.
store.redis.mode=single
store.redis.type=pipeline
store.redis.single.host=redis
store.redis.single.port=6379
store.redis.sentinel.masterName=
store.redis.sentinel.sentinelHosts=
store.redis.sentinel.sentinelPassword=
store.redis.maxConn=10
store.redis.minConn=1
store.redis.maxTotal=100
store.redis.database=0
store.redis.password=laokou123
store.redis.queryLimit=100

#Transaction rule configuration, only for the server
server.recovery.committingRetryPeriod=1000
server.recovery.asynCommittingRetryPeriod=1000
server.recovery.rollbackingRetryPeriod=1000
server.recovery.timeoutRetryPeriod=1000
server.maxCommitRetryTimeout=-1
server.maxRollbackRetryTimeout=-1
server.rollbackRetryTimeoutUnlockEnable=false
server.distributedLockExpireTime=10000
server.session.branchAsyncQueueSize=5000
server.session.enableBranchAsyncRemove=false
server.enableParallelRequestHandle=true
server.enableParallelHandleBranch=false

server.raft.cluster=seata:7091,seata:7092,seata:7093
server.raft.snapshotInterval=600
server.raft.applyBatch=32
server.raft.maxAppendBufferSize=262144
server.raft.maxReplicatorInflightMsgs=256
server.raft.disruptorBufferSize=16384
server.raft.electionTimeoutMs=2000
server.raft.reporterEnabled=false
server.raft.reporterInitialDelay=60
server.raft.serialization=jackson
server.raft.compressor=none
server.raft.sync=true

#Metrics configuration, only for the server
metrics.enabled=false
metrics.registryType=compact
metrics.exporterList=prometheus
metrics.exporterPrometheusPort=9898', 'a7c7188f1828b0521c7ce82a105bc070', '2024-12-15 20:30:03.552', '2024-12-15 20:30:03.552', 'nacos', '127.0.0.1', 'laokou-sample-seata-server', '', 'seata server配置', NULL, NULL, 'properties', NULL, '');
INSERT INTO "public"."config_info"  OVERRIDING SYSTEM VALUE VALUES  (13, 'gateway-flow.json', 'LAOKOU_GROUP', '[
  {
    "resource": "laokou-auth",
    "grade": 1,
    "count": 100000,
    "intervalSec": 1,
    "burst": 500000,
    "controlBehavior": 0
  },
  {
    "resource": "laokou-admin",
    "grade": 1,
    "count": 100000,
    "intervalSec": 1,
    "burst": 500000,
    "controlBehavior": 0
  },
  {
    "resource": "laokou-iot",
    "grade": 1,
    "count": 100000,
    "intervalSec": 1,
    "burst": 500000,
    "controlBehavior": 0
  },
  {
    "resource": "laokou-generator",
    "grade": 1,
    "count": 100000,
    "intervalSec": 1,
    "burst": 500000,
    "controlBehavior": 0
  }
]', '5e013d830e3af21e5e321c0f4910fda0', '2024-05-25 18:13:10.6', '2024-11-11 20:52:03.56', 'nacos', '0:0:0:0:0:0:0:1', 'laokou-gateway', '8140e92b-fb43-48f5-b63b-7506185206a5', 'gateway sentinel flow rule', '', '', 'json', '', '');
INSERT INTO "public"."config_info"  OVERRIDING SYSTEM VALUE VALUES  (31, 'router.json', 'LAOKOU_GROUP', '[
  {
    "id": "laokou-auth",
    "uri": "lb://laokou-auth",
    "predicates": [
      {
        "name": "Path",
        "args": {
          "pattern": "/auth/**"
        }
      },
      {
        "name": "Weight",
        "args": {
          "_genkey_0": "auth",
          "_genkey_1": "100"
        }
      }
    ],
    "filters": [
      {
        "name": "StripPrefix",
        "args": {
          "parts": "1"
        }
      },
      {
        "name": "RewritePath",
        "args": {
          "_genkey_0": "/auth/(?<path>.*)",
          "_genkey_1": "/$\\{path}"
        }
      }
    ],
    "metadata": {
      "version": "v3"
    },
    "order": 1
  },
  {
    "id": "laokou-admin",
    "uri": "lb://laokou-admin",
    "predicates": [
      {
        "name": "Path",
        "args": {
          "pattern": "/admin/**"
        }
      },
      {
        "name": "Weight",
        "args": {
          "_genkey_0": "admin",
          "_genkey_1": "100"
        }
      }
    ],
    "filters": [
      {
        "name": "StripPrefix",
        "args": {
          "parts": "1"
        }
      },
      {
        "name": "RewritePath",
        "args": {
          "_genkey_0": "/admin/(?<path>.*)",
          "_genkey_1": "/$\\{path}"
        }
      }
    ],
    "metadata": {
      "version": "v3"
    },
    "order": 1
  },
  {
    "id": "laokou-iot",
    "uri": "lb://laokou-iot",
    "predicates": [
      {
        "name": "Path",
        "args": {
          "pattern": "/iot/**"
        }
      },
      {
        "name": "Weight",
        "args": {
          "_genkey_0": "iot",
          "_genkey_1": "100"
        }
      }
    ],
    "filters": [
      {
        "name": "StripPrefix",
        "args": {
          "parts": "1"
        }
      },
      {
        "name": "RewritePath",
        "args": {
          "_genkey_0": "/iot/(?<path>.*)",
          "_genkey_1": "/$\\{path}"
        }
      }
    ],
    "metadata": {
      "version": "v3"
    },
    "order": 1
  }
]
', '0e03959c7b36b5d0c13fc33b2463e0d3', '2024-05-25 18:13:10.616', '2024-11-06 22:47:22.13', 'nacos', '0:0:0:0:0:0:0:1', 'laokou-gateway', '8140e92b-fb43-48f5-b63b-7506185206a5', '动态路由配置', '', '', 'json', '', '');
INSERT INTO "public"."config_info"  OVERRIDING SYSTEM VALUE VALUES  (26, 'router.json', 'LAOKOU_GROUP', '[
  {
    "id": "laokou-auth",
    "uri": "lb://laokou-auth",
    "predicates": [
      {
        "name": "Path",
        "args": {
          "pattern": "/auth/**"
        }
      },
      {
        "name": "Weight",
        "args": {
          "_genkey_0": "auth",
          "_genkey_1": "100"
        }
      }
    ],
    "filters": [
      {
        "name": "StripPrefix",
        "args": {
          "parts": "1"
        }
      },
      {
        "name": "RewritePath",
        "args": {
          "_genkey_0": "/auth/(?<path>.*)",
          "_genkey_1": "/$\\{path}"
        }
      }
    ],
    "metadata": {
      "version": "v3"
    },
    "order": 1
  },
  {
    "id": "laokou-admin",
    "uri": "lb://laokou-admin",
    "predicates": [
      {
        "name": "Path",
        "args": {
          "pattern": "/admin/**"
        }
      },
      {
        "name": "Weight",
        "args": {
          "_genkey_0": "admin",
          "_genkey_1": "100"
        }
      }
    ],
    "filters": [
      {
        "name": "StripPrefix",
        "args": {
          "parts": "1"
        }
      },
      {
        "name": "RewritePath",
        "args": {
          "_genkey_0": "/admin/(?<path>.*)",
          "_genkey_1": "/$\\{path}"
        }
      }
    ],
    "metadata": {
      "version": "v3"
    },
    "order": 1
  },
  {
    "id": "laokou-iot",
    "uri": "lb://laokou-iot",
    "predicates": [
      {
        "name": "Path",
        "args": {
          "pattern": "/iot/**"
        }
      },
      {
        "name": "Weight",
        "args": {
          "_genkey_0": "iot",
          "_genkey_1": "100"
        }
      }
    ],
    "filters": [
      {
        "name": "StripPrefix",
        "args": {
          "parts": "1"
        }
      },
      {
        "name": "RewritePath",
        "args": {
          "_genkey_0": "/iot/(?<path>.*)",
          "_genkey_1": "/$\\{path}"
        }
      }
    ],
    "metadata": {
      "version": "v3"
    },
    "order": 1
  }
]
', '0e03959c7b36b5d0c13fc33b2463e0d3', '2024-05-25 18:13:33.387', '2024-11-06 22:46:53.026', 'nacos', '0:0:0:0:0:0:0:1', 'laokou-gateway', '0dac1a68-2f01-40df-bd26-bf0cb199057a', '动态路由配置', '', '', 'json', '', '');
INSERT INTO "public"."config_info"  OVERRIDING SYSTEM VALUE VALUES  (30, 'router.json', 'LAOKOU_GROUP', '[
  {
    "id": "laokou-auth",
    "uri": "lb://laokou-auth",
    "predicates": [
      {
        "name": "Path",
        "args": {
          "pattern": "/auth/**"
        }
      },
      {
        "name": "Weight",
        "args": {
          "_genkey_0": "auth",
          "_genkey_1": "100"
        }
      }
    ],
    "filters": [
      {
        "name": "StripPrefix",
        "args": {
          "parts": "1"
        }
      },
      {
        "name": "RewritePath",
        "args": {
          "_genkey_0": "/auth/(?<path>.*)",
          "_genkey_1": "/$\\{path}"
        }
      }
    ],
    "metadata": {
      "version": "v3"
    },
    "order": 1
  },
  {
    "id": "laokou-admin",
    "uri": "lb://laokou-admin",
    "predicates": [
      {
        "name": "Path",
        "args": {
          "pattern": "/admin/**"
        }
      },
      {
        "name": "Weight",
        "args": {
          "_genkey_0": "admin",
          "_genkey_1": "100"
        }
      }
    ],
    "filters": [
      {
        "name": "StripPrefix",
        "args": {
          "parts": "1"
        }
      },
      {
        "name": "RewritePath",
        "args": {
          "_genkey_0": "/admin/(?<path>.*)",
          "_genkey_1": "/$\\{path}"
        }
      }
    ],
    "metadata": {
      "version": "v3"
    },
    "order": 1
  },
  {
    "id": "laokou-iot",
    "uri": "lb://laokou-iot",
    "predicates": [
      {
        "name": "Path",
        "args": {
          "pattern": "/iot/**"
        }
      },
      {
        "name": "Weight",
        "args": {
          "_genkey_0": "iot",
          "_genkey_1": "100"
        }
      }
    ],
    "filters": [
      {
        "name": "StripPrefix",
        "args": {
          "parts": "1"
        }
      },
      {
        "name": "RewritePath",
        "args": {
          "_genkey_0": "/iot/(?<path>.*)",
          "_genkey_1": "/$\\{path}"
        }
      }
    ],
    "metadata": {
      "version": "v3"
    },
    "order": 1
  }
]
', '0e03959c7b36b5d0c13fc33b2463e0d3', '2023-01-13 15:44:25', '2024-11-06 22:47:10.779', 'nacos', '0:0:0:0:0:0:0:1', 'laokou-gateway', 'a61abd4c-ef96-42a5-99a1-616adee531f3', '', '', '', 'text', '', '');
INSERT INTO "public"."config_info"  OVERRIDING SYSTEM VALUE VALUES  (38, 'auth-flow.json', 'LAOKOU_GROUP', '[
  {
    "resource": "/v3/captchas/{uuid}",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/captchas/send/mobile",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
    {
    "resource": "/v3/captchas/send/mail",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/secrets",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/tokens",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  }
]
', '2bb6ed92c98b4a1693426dadf1c96a30', '2024-11-11 21:17:37.578', '2024-11-11 21:18:17.553', 'nacos', '0:0:0:0:0:0:0:1', 'laokou-auth', '8140e92b-fb43-48f5-b63b-7506185206a5', 'auth sentinel flow rule', '', '', 'json', '', '');
INSERT INTO "public"."config_info"  OVERRIDING SYSTEM VALUE VALUES (39, 'auth-flow.json', 'LAOKOU_GROUP', '[
  {
    "resource": "/v3/captchas/{uuid}",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/captchas/send/mobile",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
    {
    "resource": "/v3/captchas/send/mail",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/secrets",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/tokens",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  }
]
', '2bb6ed92c98b4a1693426dadf1c96a30', '2024-11-11 21:16:13.23', '2024-11-11 21:17:25.382', 'nacos', '0:0:0:0:0:0:0:1', 'laokou-auth', 'a61abd4c-ef96-42a5-99a1-616adee531f3', 'auth sentinel flow rule', '', '', 'json', '', '');
INSERT INTO "public"."config_info"  OVERRIDING SYSTEM VALUE VALUES  (40, 'admin-flow.json', 'LAOKOU_GROUP', '[
  {
    "resource": "/v3/users",
    "limitApp": "default",
    "count": 500000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/users/import",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/users/export",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/users/page",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/users/{id}",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/users/profile",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/tenants",
    "limitApp": "default",
    "count": 500000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/tenants/import",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/tenants/export",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/sources",
    "limitApp": "default",
    "count": 500000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/sources/import",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/sources/export",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/sources/page",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/sources/{id}",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/roles",
    "limitApp": "default",
    "count": 500000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/roles/import",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/roles/export",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/roles/page",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/roles/{id}",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/oss-logs",
    "limitApp": "default",
    "count": 500000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/oss-logs/import",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/oss-logs/export",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/oss-logs/page",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/oss-logs/{id}",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/oss",
    "limitApp": "default",
    "count": 500000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/oss/import",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/oss/export",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/oss/page",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/oss/{id}",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/operate-logs",
    "limitApp": "default",
    "count": 500000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/operate-logs/import",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/operate-logs/export",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/operate-logs/page",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/operate-logs/{id}",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/notice-logs",
    "limitApp": "default",
    "count": 500000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/notice-logs/import",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/notice-logs/export",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/notice-logs/page",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/notice-logs/{id}",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/menus",
    "limitApp": "default",
    "count": 500000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/menus/import",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/menus/export",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/menus/page",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/menus/{id}",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/login-log",
    "limitApp": "default",
    "count": 500000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/login-log/import",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/login-log/export",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/login-log/page",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/login-log/{id}",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/login-log/all",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/ips",
    "limitApp": "default",
    "count": 500000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/ips/import",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/ips/export",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/ips/page",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/ips/{id}",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/i18n-messages",
    "limitApp": "default",
    "count": 500000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/i18n-messages/import",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/i18n-messages/export",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/i18n-messages/page",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/i18n-messages/{id}",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/domain-events",
    "limitApp": "default",
    "count": 500000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/domain-events/import",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/domain-events/export",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/domain-events/page",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/domain-events/{id}",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/dicts",
    "limitApp": "default",
    "count": 500000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/dicts/import",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/dicts/export",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/dicts/page",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/dicts/{id}",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/dict-items",
    "limitApp": "default",
    "count": 500000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/dict-items/import",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/dict-items/export",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/dict-items/page",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/dict-items/{id}",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/depts",
    "limitApp": "default",
    "count": 500000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/depts/import",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/depts/export",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/depts/page",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/depts/{id}",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/clusters",
    "limitApp": "default",
    "count": 500000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/clusters/import",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/clusters/export",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/clusters/page",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/clusters/{id}",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  }
]
', '546e2d9817dd516db763f5ef3ef3a756', '2024-11-11 21:19:54.557', '2024-11-12 11:13:47.766', 'nacos', '0:0:0:0:0:0:0:1', 'laokou-admin', 'a61abd4c-ef96-42a5-99a1-616adee531f3', 'admin sentinel flow rule', '', '', 'json', '', '');
INSERT INTO "public"."config_info"  OVERRIDING SYSTEM VALUE VALUES  (41, 'admin-flow.json', 'LAOKOU_GROUP', '[
  {
    "resource": "/v3/users",
    "limitApp": "default",
    "count": 500000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/users/import",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/users/export",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/users/page",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/users/{id}",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/users/profile",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/tenants",
    "limitApp": "default",
    "count": 500000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/tenants/import",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/tenants/export",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/tenants/page",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/tenants/{id}",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/sources",
    "limitApp": "default",
    "count": 500000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/sources/import",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/sources/export",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/sources/page",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/sources/{id}",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/roles",
    "limitApp": "default",
    "count": 500000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/roles/import",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/roles/export",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/roles/page",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/roles/{id}",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/oss-logs",
    "limitApp": "default",
    "count": 500000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/oss-logs/import",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/oss-logs/export",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/oss-logs/page",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/oss-logs/{id}",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/oss",
    "limitApp": "default",
    "count": 500000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/oss/import",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/oss/export",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/oss/page",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/oss/{id}",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/operate-logs",
    "limitApp": "default",
    "count": 500000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/operate-logs/import",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/operate-logs/export",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/operate-logs/page",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/operate-logs/{id}",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/notice-logs",
    "limitApp": "default",
    "count": 500000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/notice-logs/import",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/notice-logs/export",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/notice-logs/page",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/notice-logs/{id}",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/menus",
    "limitApp": "default",
    "count": 500000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/menus/import",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/menus/export",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/menus/page",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/menus/{id}",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/login-log",
    "limitApp": "default",
    "count": 500000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/login-log/import",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/login-log/export",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/login-log/page",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/login-log/{id}",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/login-log/all",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/ips",
    "limitApp": "default",
    "count": 500000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/ips/import",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/ips/export",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/ips/page",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/ips/{id}",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/i18n-messages",
    "limitApp": "default",
    "count": 500000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/i18n-messages/import",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/i18n-messages/export",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/i18n-messages/page",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/i18n-messages/{id}",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/domain-events",
    "limitApp": "default",
    "count": 500000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/domain-events/import",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/domain-events/export",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/domain-events/page",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/domain-events/{id}",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/dicts",
    "limitApp": "default",
    "count": 500000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/dicts/import",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/dicts/export",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/dicts/page",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/dicts/{id}",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/dict-items",
    "limitApp": "default",
    "count": 500000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/dict-items/import",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/dict-items/export",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/dict-items/page",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/dict-items/{id}",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/depts",
    "limitApp": "default",
    "count": 500000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/depts/import",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/depts/export",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/depts/page",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/depts/{id}",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/clusters",
    "limitApp": "default",
    "count": 500000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/clusters/import",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/clusters/export",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/clusters/page",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/clusters/{id}",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  }
]
', '546e2d9817dd516db763f5ef3ef3a756', '2024-11-11 21:20:18.495', '2024-11-12 11:14:01.899', 'nacos', '0:0:0:0:0:0:0:1', 'laokou-admin', '0dac1a68-2f01-40df-bd26-bf0cb199057a', 'admin sentinel flow rule', '', '', 'json', '', '');
INSERT INTO "public"."config_info"  OVERRIDING SYSTEM VALUE VALUES  (43, 'auth-flow.json', 'LAOKOU_GROUP', '[
  {
    "resource": "/v3/captchas/{uuid}",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/captchas/send/mobile",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
    {
    "resource": "/v3/captchas/send/mail",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/secrets",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  },
  {
    "resource": "/v3/tokens",
    "limitApp": "default",
    "count": 100000,
    "grade": 1,
    "strategy": 0,
    "controlBehavior": 0
  }
]
', '2bb6ed92c98b4a1693426dadf1c96a30', '2024-11-11 21:17:33.583', '2024-11-11 21:18:04.394', 'nacos', '0:0:0:0:0:0:0:1', 'laokou-auth', '0dac1a68-2f01-40df-bd26-bf0cb199057a', 'auth sentinel flow rule', '', '', 'json', '', '');
INSERT INTO "public"."config_info"  OVERRIDING SYSTEM VALUE VALUES  (51, 'gateway-flow.json', 'LAOKOU_GROUP', '[
  {
    "resource": "laokou-auth",
    "grade": 1,
    "count": 100000,
    "intervalSec": 1,
    "burst": 500000,
    "controlBehavior": 0
  },
  {
    "resource": "laokou-admin",
    "grade": 1,
    "count": 100000,
    "intervalSec": 1,
    "burst": 500000,
    "controlBehavior": 0
  },
  {
    "resource": "laokou-iot",
    "grade": 1,
    "count": 100000,
    "intervalSec": 1,
    "burst": 500000,
    "controlBehavior": 0
  },
  {
    "resource": "laokou-generator",
    "grade": 1,
    "count": 100000,
    "intervalSec": 1,
    "burst": 500000,
    "controlBehavior": 0
  }
]', '5e013d830e3af21e5e321c0f4910fda0', '2023-02-26 14:59:20', '2024-11-11 20:51:31.708', 'nacos', '0:0:0:0:0:0:0:1', 'laokou-gateway', 'a61abd4c-ef96-42a5-99a1-616adee531f3', 'gateway sentinel flow rule', '', '', 'json', '', '');
INSERT INTO "public"."config_info"  OVERRIDING SYSTEM VALUE VALUES  (29, 'application-shardingsphere.yaml', 'DEFAULT_GROUP', '# 加密公钥
public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJ4o6sn4WoPmbs7DR9mGQzuuUQM9erQTVPpwxIzB0ETYkyKffO097qXVRLA6KPmaV+/siWewR7vpfYYjWajw5KkCAwEAAQ==
dataSources:
  # 主表【数据库配置，请按照作者来，请不要瞎几把改！！！】
  master:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: org.postgresql.Driver
    jdbcUrl: jdbc:postgresql://postgresql:5432/kcloud_platform_test?tcpKeepAlive=true&reWriteBatchedInserts=true&stringtype=unspecified&ApplicationName=laokou-sample-shardingsphere&useSSL=false
    username: ENC(VZamSTMi224AH6RUtJGXNldiDp/XEL2ozRhBUu/o9ChodT4JEb9kE/j0EFhXKbjsfvLVacUW0AUzetA6OrNJug==)
    password: ENC(laIHkPM/z03tYjA95hES4+BhyjyhvrPjJynrC65oDyXnUTP0Tge1UxwERWFBbHoOOQZ2GzzUrRhEYJ3jFb89eQ==)
  # 从表【数据库配置，请按照作者来，请不要瞎几把改！！！】
  slave:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: org.postgresql.Driver
    jdbcUrl: jdbc:postgresql://postgresql:5432/kcloud_platform_test?tcpKeepAlive=true&reWriteBatchedInserts=true&stringtype=unspecified&ApplicationName=laokou-sample-shardingsphere&useSSL=false
    username: ENC(VZamSTMi224AH6RUtJGXNldiDp/XEL2ozRhBUu/o9ChodT4JEb9kE/j0EFhXKbjsfvLVacUW0AUzetA6OrNJug==)
    password: ENC(laIHkPM/z03tYjA95hES4+BhyjyhvrPjJynrC65oDyXnUTP0Tge1UxwERWFBbHoOOQZ2GzzUrRhEYJ3jFb89eQ==)
rules:
- !SHARDING
  tables:
    # 分表的表名
    boot_sys_user:
      # 分表规则，按月份分表
      actualDataNodes: master.boot_sys_user_20240$->{1..9},master.boot_sys_user_2024$->{10..12}
      # 分表策略
      tableStrategy:
        # 规格
        standard:
          # 按创建时间字段分表
          shardingColumn: create_date
          # 自定义分表算法名称
          shardingAlgorithmName: laokou_table_inline
      # 主键生成策略
      keyGenerateStrategy:
        # 主键字段名称
        column: id
        # 主键生成采用的算法名称
        keyGeneratorName: snowflake
  # 自定义分表算法
  shardingAlgorithms:
    # 自定义分表算法名称
    laokou_table_inline:
      # 时间范围分片算法
      type: INTERVAL
      props:
        # 分片键的时间戳格式
        datetime-pattern: "yyyy-MM-dd HH:mm:ss"
        # 真实表的后缀格式
        sharding-suffix-pattern: "yyyyMM"
        # 时间分片下界值
        datetime-lower: "2024-01-01 00:00:00"
        # 时间分片上界值
        datetime-upper: "2024-12-31 23:59:59"
        # 分片间隔
        datetime-interval-amount: 1
        # 按月分表
        datetime-interval-unit: "months"
  # 主键生成器
  keyGenerators:
    # 雪花算法配置
    snowflake:
      # 雪花算法
      type: SNOWFLAKE
      # 属性
      props:
        # 机器工作ID
        work-id: 123
- !READWRITE_SPLITTING
  # 数据源分组
  dataSourceGroups:
    # 读写分离配置
    laokou_readwrite_data_sources:
      # 主节点写入
      writeDataSourceName: master
      # 从节点读取
      readDataSourceNames:
        - slave
      # 自定义负载均衡算法名称
      loadBalancerName: laokou_load_balance_algorithm
  # 自定义负载均衡算法
  loadBalancers:
    # 自定义负载均衡算法名称
    laokou_load_balance_algorithm:
      # 轮询调度算法
      type: ROUND_ROBIN
# 属性配置
props:
  # 显示SQL语句
  sql-show: true', 'b9fc8e8c42efd77d4029eaa4f9794bae', '2024-10-26 19:01:28.101', '2025-03-12 11:53:33.869', 'nacos', '0:0:0:0:0:0:0:1', '', '', '', '', '', 'yaml', '', '');


-- ----------------------------
-- Primary Key structure for table users
-- ----------------------------
ALTER TABLE "public"."users" ADD CONSTRAINT "users_pkey" PRIMARY KEY ("username");

-- ----------------------------
-- Auto increment value for tenant_info
-- ----------------------------
SELECT setval('"public"."tenant_info_id_seq"', 1, false);

-- ----------------------------
-- Indexes structure for table tenant_info
-- ----------------------------
CREATE UNIQUE INDEX "tenant_info_kp_tenant_id_idx" ON "public"."tenant_info" USING btree (
  "kp" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "tenant_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);
CREATE INDEX "tenant_info_tenant_id_idx" ON "public"."tenant_info" USING btree (
  "tenant_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table tenant_info
-- ----------------------------
ALTER TABLE "public"."tenant_info" ADD CONSTRAINT "tenant_info_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for tenant_capacity
-- ----------------------------
SELECT setval('"public"."tenant_capacity_id_seq"', 1, false);

-- ----------------------------
-- Indexes structure for table tenant_capacity
-- ----------------------------
CREATE UNIQUE INDEX "tenant_capacity_tenant_id_idx" ON "public"."tenant_capacity" USING btree (
  "tenant_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table tenant_capacity
-- ----------------------------
ALTER TABLE "public"."tenant_capacity" ADD CONSTRAINT "tenant_capacity_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Indexes structure for table roles
-- ----------------------------
CREATE UNIQUE INDEX "roles_username_role_idx" ON "public"."roles" USING btree (
  "username" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "role" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

-- ----------------------------
-- Indexes structure for table permissions
-- ----------------------------
CREATE UNIQUE INDEX "permissions_role_resource_action_idx" ON "public"."permissions" USING btree (
  "role" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "resource" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "action" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

-- ----------------------------
-- Auto increment value for his_config_info
-- ----------------------------
SELECT setval('"public"."his_config_info_nid_seq"', 47, true);

-- ----------------------------
-- Indexes structure for table his_config_info
-- ----------------------------
CREATE INDEX "his_config_info_data_id_idx" ON "public"."his_config_info" USING btree (
  "data_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);
CREATE INDEX "his_config_info_gmt_create_idx" ON "public"."his_config_info" USING btree (
  "gmt_create" "pg_catalog"."timestamp_ops" ASC NULLS LAST
);
CREATE INDEX "his_config_info_gmt_modified_idx" ON "public"."his_config_info" USING btree (
  "gmt_modified" "pg_catalog"."timestamp_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table his_config_info
-- ----------------------------
ALTER TABLE "public"."his_config_info" ADD CONSTRAINT "his_config_info_pkey" PRIMARY KEY ("nid");

-- ----------------------------
-- Auto increment value for group_capacity
-- ----------------------------
SELECT setval('"public"."group_capacity_id_seq"', 1, false);

-- ----------------------------
-- Indexes structure for table group_capacity
-- ----------------------------
CREATE UNIQUE INDEX "group_capacity_group_id_idx" ON "public"."group_capacity" USING btree (
  "group_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table group_capacity
-- ----------------------------
ALTER TABLE "public"."group_capacity" ADD CONSTRAINT "group_capacity_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table databasechangeloglock
-- ----------------------------
ALTER TABLE "public"."databasechangeloglock" ADD CONSTRAINT "databasechangeloglock_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for config_tags_relation
-- ----------------------------
SELECT setval('"public"."config_tags_relation_nid_seq"', 63, true);

-- ----------------------------
-- Primary Key structure for table config_tags_relation
-- ----------------------------
ALTER TABLE "public"."config_tags_relation" ADD CONSTRAINT "config_tags_relation_pkey" PRIMARY KEY ("nid");

-- ----------------------------
-- Auto increment value for config_info_tag
-- ----------------------------
SELECT setval('"public"."config_info_tag_id_seq"', 1, false);

-- ----------------------------
-- Indexes structure for table config_info_tag
-- ----------------------------
CREATE UNIQUE INDEX "config_info_tag_data_id_group_id_tenant_id_tag_id_idx" ON "public"."config_info_tag" USING btree (
  "data_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "group_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "tenant_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "tag_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table config_info_tag
-- ----------------------------
ALTER TABLE "public"."config_info_tag" ADD CONSTRAINT "config_info_tag_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for config_info_beta
-- ----------------------------
SELECT setval('"public"."config_info_beta_id_seq"', 1, false);

-- ----------------------------
-- Indexes structure for table config_info_beta
-- ----------------------------
CREATE UNIQUE INDEX "config_info_beta_data_id_group_id_tenant_id_idx" ON "public"."config_info_beta" USING btree (
  "data_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "group_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "tenant_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table config_info_beta
-- ----------------------------
ALTER TABLE "public"."config_info_beta" ADD CONSTRAINT "config_info_beta_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for config_info_aggr
-- ----------------------------
SELECT setval('"public"."config_info_aggr_id_seq"', 1, false);

-- ----------------------------
-- Indexes structure for table config_info_aggr
-- ----------------------------
CREATE UNIQUE INDEX "config_info_aggr_data_id_group_id_tenant_id_datum_id_idx" ON "public"."config_info_aggr" USING btree (
  "data_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "group_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "tenant_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "datum_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table config_info_aggr
-- ----------------------------
ALTER TABLE "public"."config_info_aggr" ADD CONSTRAINT "config_info_aggr_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for config_info
-- ----------------------------
SELECT setval('"public"."config_info_id_seq"', 213, true);

-- ----------------------------
-- Indexes structure for table config_info
-- ----------------------------
CREATE UNIQUE INDEX "config_info_data_id_group_id_tenant_id_idx" ON "public"."config_info" USING btree (
  "data_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "group_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "tenant_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table config_info
-- ----------------------------
ALTER TABLE "public"."config_info" ADD CONSTRAINT "config_info_pkey" PRIMARY KEY ("id");
