/*
 Navicat Premium Dump SQL

 Source Server         : 127.0.0.1
 Source Server Type    : PostgreSQL
 Source Server Version : 170003 (170003)
 Source Host           : 127.0.0.1:5432
 Source Catalog        : kcloud_platform
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 170003 (170003)
 File Encoding         : 65001

 Date: 15/05/2025 11:26:07
*/

DROP TABLE IF EXISTS "public"."generator_column";
CREATE TABLE "public"."generator_column" (
	"id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"creator" int8 NOT NULL DEFAULT 0,
	"editor" int8 NOT NULL DEFAULT 0,
	"create_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"update_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"del_flag" int2 NOT NULL DEFAULT 0,
	"version" int4 NOT NULL DEFAULT 0,
	"tenant_id" int8 NOT NULL DEFAULT 0,
	"name" varchar(100) NOT NULL,
	"comment" varchar(400),
	"type" varchar(100) NOT NULL,
	"required_flag" int2 NOT NULL,
	"save_flag" int2 NOT NULL,
	"modify_flag" int2 NOT NULL,
	"query_flag" int2 NOT NULL,
	"page_flag" int2 NOT NULL,
	"query_type" varchar(50),
	"component_type" varchar(50),
	"dict_type" varchar(50) ,
	"field_name" varchar(50) NOT NULL,
	"field_type" varchar(50) NOT NULL,
	"info_id" int8 NOT NULL
);
COMMENT ON COLUMN "public"."generator_column"."id" IS 'ID';
COMMENT ON COLUMN "public"."generator_column"."creator" IS '创建人';
COMMENT ON COLUMN "public"."generator_column"."editor" IS '编辑人';
COMMENT ON COLUMN "public"."generator_column"."create_time" IS '创建时间';
COMMENT ON COLUMN "public"."generator_column"."update_time" IS '修改时间';
COMMENT ON COLUMN "public"."generator_column"."del_flag" IS '删除标识 0未删除 1已删除';
COMMENT ON COLUMN "public"."generator_column"."version" IS '版本号';
COMMENT ON COLUMN "public"."generator_column"."tenant_id" IS '租户ID';
COMMENT ON COLUMN "public"."generator_column"."name" IS '列名';
COMMENT ON COLUMN "public"."generator_column"."comment" IS '描述';
COMMENT ON COLUMN "public"."generator_column"."type" IS '类型';
COMMENT ON COLUMN "public"."generator_column"."required_flag" IS '必填标识 0否 1是';
COMMENT ON COLUMN "public"."generator_column"."save_flag" IS '保存标识 0否 1是';
COMMENT ON COLUMN "public"."generator_column"."modify_flag" IS '修改标识 0否 1是';
COMMENT ON COLUMN "public"."generator_column"."query_flag" IS '查询标识 0否 1是';
COMMENT ON COLUMN "public"."generator_column"."page_flag" IS '分页标识 0否 1是';
COMMENT ON COLUMN "public"."generator_column"."query_type" IS '查询类型';
COMMENT ON COLUMN "public"."generator_column"."component_type" IS '组件类型';
COMMENT ON COLUMN "public"."generator_column"."dict_type" IS '字典类型';
COMMENT ON COLUMN "public"."generator_column"."field_name" IS '字段名称';
COMMENT ON COLUMN "public"."generator_column"."field_type" IS '字段类型';
COMMENT ON COLUMN "public"."generator_column"."info_id" IS '信息ID';
COMMENT ON TABLE "public"."generator_column" IS '字段';

ALTER TABLE "public"."generator_column" ADD CONSTRAINT "generator_column_pkey" PRIMARY KEY ("id");

DROP TABLE IF EXISTS "public"."generator_info";
CREATE TABLE "public"."generator_info" (
	"id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"creator" int8 NOT NULL DEFAULT 0,
	"editor" int8 NOT NULL DEFAULT 0,
	"create_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"update_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"del_flag" int2 NOT NULL DEFAULT 0,
	"version" int4 NOT NULL DEFAULT 0,
	"tenant_id" int8 NOT NULL DEFAULT 0,
	"ds_name" varchar(50) NOT NULL,
	"db_name" varchar(50) NOT NULL,
	"table_name" varchar(50) NOT NULL,
	"author" varchar(50)  NOT NULL,
	"comment" varchar(50)  NOT NULL,
	"package_name" varchar(50)  NOT NULL,
	"module_name" varchar(50)  NOT NULL,
	"path" varchar(200)  NOT NULL,
	"service_id" varchar(50)  NOT NULL,
	"group_id" int8 NOT NULL
)
;
COMMENT ON COLUMN "public"."generator_info"."id" IS 'ID';
COMMENT ON COLUMN "public"."generator_info"."creator" IS '创建人';
COMMENT ON COLUMN "public"."generator_info"."editor" IS '编辑人';
COMMENT ON COLUMN "public"."generator_info"."create_time" IS '创建时间';
COMMENT ON COLUMN "public"."generator_info"."update_time" IS '修改时间';
COMMENT ON COLUMN "public"."generator_info"."del_flag" IS '删除标识 0未删除 1已删除';
COMMENT ON COLUMN "public"."generator_info"."version" IS '版本号';
COMMENT ON COLUMN "public"."generator_info"."tenant_id" IS '租户ID';
COMMENT ON COLUMN "public"."generator_info"."ds_name" IS '数据源名称';
COMMENT ON COLUMN "public"."generator_info"."db_name" IS '数据库名称';
COMMENT ON COLUMN "public"."generator_info"."table_name" IS '数据库表名称';
COMMENT ON COLUMN "public"."generator_info"."author" IS '作者';
COMMENT ON COLUMN "public"."generator_info"."comment" IS '描述';
COMMENT ON COLUMN "public"."generator_info"."package_name" IS '包名';
COMMENT ON COLUMN "public"."generator_info"."module_name" IS '模块名称';
COMMENT ON COLUMN "public"."generator_info"."path" IS '生成路径';
COMMENT ON COLUMN "public"."generator_info"."service_id" IS '服务ID';
COMMENT ON COLUMN "public"."generator_info"."group_id" IS '组ID';
COMMENT ON TABLE "public"."generator_info" IS '信息';

ALTER TABLE "public"."generator_info" ADD CONSTRAINT "generator_info_pkey" PRIMARY KEY ("id");

DROP TABLE IF EXISTS "public"."generator_template";
CREATE TABLE "public"."generator_template" (
	"id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"creator" int8 NOT NULL DEFAULT 0,
	"editor" int8 NOT NULL DEFAULT 0,
	"create_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"update_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"del_flag" int2 NOT NULL DEFAULT 0,
	"version" int4 NOT NULL DEFAULT 0,
	"tenant_id" int8 NOT NULL DEFAULT 0,
	"code" varchar(50)  NOT NULL,
	"name" varchar(50)  NOT NULL,
	"path_pattern" varchar(50) NOT NULL,
	"content" text  NOT NULL,
	"remark" varchar(400)
)
;
COMMENT ON COLUMN "public"."generator_template"."id" IS 'ID';
COMMENT ON COLUMN "public"."generator_template"."creator" IS '创建人';
COMMENT ON COLUMN "public"."generator_template"."editor" IS '编辑人';
COMMENT ON COLUMN "public"."generator_template"."create_time" IS '创建时间';
COMMENT ON COLUMN "public"."generator_template"."update_time" IS '修改时间';
COMMENT ON COLUMN "public"."generator_template"."del_flag" IS '删除标识 0未删除 1已删除';
COMMENT ON COLUMN "public"."generator_template"."version" IS '版本号';
COMMENT ON COLUMN "public"."generator_template"."tenant_id" IS '租户ID';
COMMENT ON COLUMN "public"."generator_template"."code" IS '编码';
COMMENT ON COLUMN "public"."generator_template"."name" IS '名称';
COMMENT ON COLUMN "public"."generator_template"."path_pattern" IS '路径表达式';
COMMENT ON COLUMN "public"."generator_template"."content" IS '内容';
COMMENT ON COLUMN "public"."generator_template"."remark" IS '备注';
COMMENT ON TABLE  "public"."generator_template" IS '模板';

ALTER TABLE "public"."generator_template" ADD CONSTRAINT "generator_template_pkey" PRIMARY KEY ("id");

DROP TABLE IF EXISTS "public"."generator_group";
CREATE TABLE "public"."generator_group" (
   "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   "creator" int8 NOT NULL DEFAULT 0,
   "editor" int8 NOT NULL DEFAULT 0,
   "create_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
   "update_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
   "del_flag" int2 NOT NULL DEFAULT 0,
   "version" int4 NOT NULL DEFAULT 0,
   "tenant_id" int8 NOT NULL DEFAULT 0,
   "name" varchar(50)  NOT NULL
)
;
COMMENT ON COLUMN "public"."generator_group"."id" IS 'ID';
COMMENT ON COLUMN "public"."generator_group"."creator" IS '创建人';
COMMENT ON COLUMN "public"."generator_group"."editor" IS '编辑人';
COMMENT ON COLUMN "public"."generator_group"."create_time" IS '创建时间';
COMMENT ON COLUMN "public"."generator_group"."update_time" IS '修改时间';
COMMENT ON COLUMN "public"."generator_group"."del_flag" IS '删除标识 0未删除 1已删除';
COMMENT ON COLUMN "public"."generator_group"."version" IS '版本号';
COMMENT ON COLUMN "public"."generator_group"."tenant_id" IS '租户ID';
COMMENT ON COLUMN "public"."generator_group"."name" IS '名称';
COMMENT ON TABLE  "public"."generator_group" IS '组';

ALTER TABLE "public"."generator_group" ADD CONSTRAINT "generator_group_pkey" PRIMARY KEY ("id");

DROP TABLE IF EXISTS "public"."generator_template_group";
CREATE TABLE "public"."generator_template_group" (
	"id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"creator" int8 NOT NULL DEFAULT 0,
	"editor" int8 NOT NULL DEFAULT 0,
	"create_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"update_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"del_flag" int2 NOT NULL DEFAULT 0,
	"version" int4 NOT NULL DEFAULT 0,
	"tenant_id" int8 NOT NULL DEFAULT 0,
	"template_id" int8  NOT NULL,
	"group_id" int8  NOT NULL
)
;
COMMENT ON COLUMN "public"."generator_template_group"."id" IS 'ID';
COMMENT ON COLUMN "public"."generator_template_group"."creator" IS '创建人';
COMMENT ON COLUMN "public"."generator_template_group"."editor" IS '编辑人';
COMMENT ON COLUMN "public"."generator_template_group"."create_time" IS '创建时间';
COMMENT ON COLUMN "public"."generator_template_group"."update_time" IS '修改时间';
COMMENT ON COLUMN "public"."generator_template_group"."del_flag" IS '删除标识 0未删除 1已删除';
COMMENT ON COLUMN "public"."generator_template_group"."version" IS '版本号';
COMMENT ON COLUMN "public"."generator_template_group"."tenant_id" IS '租户ID';
COMMENT ON COLUMN "public"."generator_template_group"."template_id" IS '模板ID';
COMMENT ON COLUMN "public"."generator_template_group"."group_id" IS '组ID';
COMMENT ON TABLE  "public"."generator_template_group" IS '模板组';

ALTER TABLE "public"."generator_template_group" ADD CONSTRAINT "generator_template_group_pkey" PRIMARY KEY ("id");
