/*
 Navicat Premium Dump SQL

 Source Server         : 127.0.0.1
 Source Server Type    : PostgreSQL
 Source Server Version : 170003 (170003)
 Source Host           : 127.0.0.1:5432
 Source Catalog        : kcloud_platform
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 170003 (170003)
 File Encoding         : 65001

 Date: 15/05/2025 11:26:07
*/

-- ----------------------------
-- -------------集群------------
-- ----------------------------
DROP TABLE IF EXISTS "public"."sys_cluster";
CREATE TABLE "public"."sys_cluster" (
 "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
 "creator" int8 NOT NULL DEFAULT 0,
 "editor" int8 NOT NULL DEFAULT 0,
 "create_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "update_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "del_flag" int2 NOT NULL DEFAULT 0,
 "version" int4 NOT NULL DEFAULT 0,
 "tenant_id" int8 NOT NULL DEFAULT 0,
 "name" varchar(50) NOT NULL,
 "code" varchar(50) NOT NULL,
 "remark" varchar(200) NOT NULL
);
COMMENT ON COLUMN "public"."sys_cluster"."id" IS 'ID';
COMMENT ON COLUMN "public"."sys_cluster"."creator" IS '创建人';
COMMENT ON COLUMN "public"."sys_cluster"."editor" IS '编辑人';
COMMENT ON COLUMN "public"."sys_cluster"."create_time" IS '创建时间';
COMMENT ON COLUMN "public"."sys_cluster"."update_time" IS '修改时间';
COMMENT ON COLUMN "public"."sys_cluster"."del_flag" IS '删除标识 0未删除 1已删除';
COMMENT ON COLUMN "public"."sys_cluster"."version" IS '版本号';
COMMENT ON COLUMN "public"."sys_cluster"."tenant_id" IS '租户ID';
COMMENT ON COLUMN "public"."sys_cluster"."name" IS '集群名称';
COMMENT ON COLUMN "public"."sys_cluster"."code" IS '集群编码';
COMMENT ON COLUMN "public"."sys_cluster"."remark" IS '集群备注';
COMMENT ON TABLE "public"."sys_cluster" IS '集群';

ALTER TABLE "public"."sys_cluster" ADD CONSTRAINT "sys_cluster_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- -------------部门------------
-- ----------------------------
DROP TABLE IF EXISTS "public"."sys_dept";
CREATE TABLE "public"."sys_dept" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "creator" int8 NOT NULL DEFAULT 0,
  "editor" int8 NOT NULL DEFAULT 0,
  "create_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "del_flag" int2 NOT NULL DEFAULT 0,
  "version" int4 NOT NULL DEFAULT 0,
  "tenant_id" int8 NOT NULL DEFAULT 0,
  "pid" int8 NOT NULL,
  "name" varchar(100) NOT NULL,
  "path" text NOT NULL DEFAULT '0',
  "sort" int4 NOT NULL DEFAULT 1
);
COMMENT ON COLUMN "public"."sys_dept"."id" IS 'ID';
COMMENT ON COLUMN "public"."sys_dept"."creator" IS '创建人';
COMMENT ON COLUMN "public"."sys_dept"."editor" IS '编辑人';
COMMENT ON COLUMN "public"."sys_dept"."create_time" IS '创建时间';
COMMENT ON COLUMN "public"."sys_dept"."update_time" IS '修改时间';
COMMENT ON COLUMN "public"."sys_dept"."del_flag" IS '删除标识 0未删除 1已删除';
COMMENT ON COLUMN "public"."sys_dept"."version" IS '版本号';
COMMENT ON COLUMN "public"."sys_dept"."tenant_id" IS '租户ID';
COMMENT ON COLUMN "public"."sys_dept"."pid" IS '部门父节点ID';
COMMENT ON COLUMN "public"."sys_dept"."name" IS '部门名称';
COMMENT ON COLUMN "public"."sys_dept"."path" IS '部门节点';
COMMENT ON COLUMN "public"."sys_dept"."sort" IS '部门排序';
COMMENT ON TABLE "public"."sys_dept" IS '部门';

ALTER TABLE "public"."sys_dept" ADD CONSTRAINT "sys_dept_pkey" PRIMARY KEY ("id");

INSERT INTO "public"."sys_dept" VALUES (1535858679453085698, 1, 1, '2022-11-02 22:35:30', '2023-09-22 11:31:42', 0, 4, 0, 1535887940687765505, '广州分公司', '0,1535887940687765505,1535858679453085698', 666);
INSERT INTO "public"."sys_dept" VALUES (1535881356595175426, 1, 1, '2022-11-02 22:35:30', '2023-09-22 11:31:42', 0, 18, 0, 1535887940687765505, '长沙分公司', '0,1535887940687765505,1535881356595175426', 111);
INSERT INTO "public"."sys_dept" VALUES (1535887129341599746, 1, 1, '2022-11-02 22:35:30', '2023-09-22 11:31:42', 0, 8, 0, 1535887940687765505, '深圳分公司', '0,1535887940687765505,1535887129341599746', 888);
INSERT INTO "public"."sys_dept" VALUES (1535887940687765505, 1, 1, '2022-11-16 12:12:55', '2023-09-22 11:31:42', 0, 38, 0, 0, '老寇云集团', '0,1535887940687765505', 1000);
INSERT INTO "public"."sys_dept" VALUES (1584488175088373761, 1, 1, '2022-11-02 22:35:30', '2023-09-22 11:31:42', 0, 43, 0, 1535881356595175426, '研发部', '0,1535887940687765505,1535881356595175426,1584488175088373761', 20);
INSERT INTO "public"."sys_dept" VALUES (1584488411756171265, 1, 1, '2022-11-02 22:35:30', '2023-09-22 11:31:42', 0, 9, 0, 1535881356595175426, '市场部', '0,1535887940687765505,1535881356595175426,1584488411756171265', 10);
INSERT INTO "public"."sys_dept" VALUES (1584488411756171266, 1, 1, '2022-11-02 22:35:30', '2023-09-22 11:31:42', 0, 19, 0, 1584488175088373761, '开发组', '0,1535887940687765505,1535881356595175426,1584488175088373761,1584488411756171266', 15);
INSERT INTO "public"."sys_dept" VALUES (1584488411756171268, 1, 1, '2023-02-10 22:01:36', '2023-09-22 11:31:42', 0, 9, 0, 1584488175088373761, '运维组', '0,1535887940687765505,1535881356595175426,1584488175088373761,1584488411756171268', 5);
INSERT INTO "public"."sys_dept" VALUES (1584488411756171269, 1, 1, '2023-02-10 22:06:44', '2023-09-22 11:31:42', 0, 8, 0, 1584488175088373761, '测试组', '0,1535887940687765505,1535881356595175426,1584488175088373761,1584488411756171269', 10);

-- ----------------------------
-- -------------字典------------
-- ----------------------------
DROP TABLE IF EXISTS "public"."sys_dict";
CREATE TABLE "public"."sys_dict" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "creator" int8 NOT NULL DEFAULT 0,
  "editor" int8 NOT NULL DEFAULT 0,
  "create_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "del_flag" int2 NOT NULL DEFAULT 0,
  "version" int4 NOT NULL DEFAULT 0,
  "tenant_id" int8 NOT NULL DEFAULT 0,
  "name" varchar(100) NOT NULL,
  "type" varchar(100) NOT NULL,
  "remark" varchar(500),
  "status" int2 NOT NULL DEFAULT 0
);
COMMENT ON COLUMN "public"."sys_dict"."id" IS 'ID';
COMMENT ON COLUMN "public"."sys_dict"."creator" IS '创建人';
COMMENT ON COLUMN "public"."sys_dict"."editor" IS '编辑人';
COMMENT ON COLUMN "public"."sys_dict"."create_time" IS '创建时间';
COMMENT ON COLUMN "public"."sys_dict"."update_time" IS '修改时间';
COMMENT ON COLUMN "public"."sys_dict"."del_flag" IS '删除标识 0未删除 1已删除';
COMMENT ON COLUMN "public"."sys_dict"."version" IS '版本号';
COMMENT ON COLUMN "public"."sys_dict"."tenant_id" IS '租户ID';
COMMENT ON COLUMN "public"."sys_dict"."name" IS '字典名称';
COMMENT ON COLUMN "public"."sys_dict"."type" IS '字典类型';
COMMENT ON COLUMN "public"."sys_dict"."remark" IS '字典备注';
COMMENT ON COLUMN "public"."sys_dict"."status" IS '字典状态 0启用 1停用';
COMMENT ON TABLE "public"."sys_dict" IS '字典';

ALTER TABLE "public"."sys_dict" ADD CONSTRAINT "sys_dict_pkey" PRIMARY KEY ("id");

INSERT INTO "public"."sys_dict" VALUES (1, 1, 1, '2024-05-09 00:15:30', '2024-05-09 00:15:40', 0, 0, 0, 'dict-type.manage.name.menu.show-hide', 'sys_menu_show_hide', '菜单状态列表', 0);

-- ----------------------------
-- -------------字典项------------
-- ----------------------------
DROP TABLE IF EXISTS "public"."sys_dict_item";
CREATE TABLE "public"."sys_dict_item" (
   "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   "creator" int8 NOT NULL DEFAULT 0,
   "editor" int8 NOT NULL DEFAULT 0,
   "create_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
   "update_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
   "del_flag" int2 NOT NULL DEFAULT 0,
   "version" int4 NOT NULL DEFAULT 0,
   "tenant_id" int8 NOT NULL DEFAULT 0,
   "label" varchar(100) NOT NULL,
   "value" varchar(100) NOT NULL,
   "sort" int4 NOT NULL DEFAULT 1,
   "remark" varchar(500),
   "status" int2 NOT NULL DEFAULT 0,
   "type_id" int8 NOT NULL
);
COMMENT ON COLUMN "public"."sys_dict_item"."id" IS 'ID';
COMMENT ON COLUMN "public"."sys_dict_item"."creator" IS '创建人';
COMMENT ON COLUMN "public"."sys_dict_item"."editor" IS '编辑人';
COMMENT ON COLUMN "public"."sys_dict_item"."create_time" IS '创建时间';
COMMENT ON COLUMN "public"."sys_dict_item"."update_time" IS '修改时间';
COMMENT ON COLUMN "public"."sys_dict_item"."del_flag" IS '删除标识 0未删除 1已删除';
COMMENT ON COLUMN "public"."sys_dict_item"."version" IS '版本号';
COMMENT ON COLUMN "public"."sys_dict_item"."tenant_id" IS '租户ID';
COMMENT ON COLUMN "public"."sys_dict_item"."label" IS '字典标签';
COMMENT ON COLUMN "public"."sys_dict_item"."value" IS '字典值';
COMMENT ON COLUMN "public"."sys_dict_item"."sort" IS '字典排序';
COMMENT ON COLUMN "public"."sys_dict_item"."remark" IS '字典备注';
COMMENT ON COLUMN "public"."sys_dict_item"."status" IS '字典状态 0启用 1停用';
COMMENT ON COLUMN "public"."sys_dict_item"."type_id" IS '类型ID';
COMMENT ON TABLE "public"."sys_dict_item" IS '字典项';

ALTER TABLE "public"."sys_dict_item" ADD CONSTRAINT "sys_dict_item_pkey" PRIMARY KEY ("id");

CREATE UNIQUE INDEX "sys_dict_type_tenantId_idx" ON "public"."sys_dict" USING btree (
   "type",
   "tenant_id"
);
COMMENT ON INDEX "public"."sys_dict_type_tenantId_idx" IS '类型_租户ID_唯一索引';

-- ----------------------------
-- -------------国际化消息------------
-- ----------------------------
DROP TABLE IF EXISTS "public"."sys_i18n_message";
CREATE TABLE "public"."sys_i18n_message" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "creator" int8 NOT NULL DEFAULT 0,
  "editor" int8 NOT NULL DEFAULT 0,
  "create_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "del_flag" int2 NOT NULL DEFAULT 0,
  "version" int4 NOT NULL DEFAULT 0,
  "tenant_id" int8 NOT NULL DEFAULT 0,
  "code" varchar(50) NOT NULL,
  "zh_message" varchar(50) NOT NULL,
  "en_message" varchar(50) NOT NULL
);
COMMENT ON COLUMN "public"."sys_i18n_message"."id" IS 'ID';
COMMENT ON COLUMN "public"."sys_i18n_message"."creator" IS '创建人';
COMMENT ON COLUMN "public"."sys_i18n_message"."editor" IS '编辑人';
COMMENT ON COLUMN "public"."sys_i18n_message"."create_time" IS '创建时间';
COMMENT ON COLUMN "public"."sys_i18n_message"."update_time" IS '修改时间';
COMMENT ON COLUMN "public"."sys_i18n_message"."del_flag" IS '删除标识 0未删除 1已删除';
COMMENT ON COLUMN "public"."sys_i18n_message"."version" IS '版本号';
COMMENT ON COLUMN "public"."sys_i18n_message"."tenant_id" IS '租户ID';
COMMENT ON COLUMN "public"."sys_i18n_message"."code" IS '编码';
COMMENT ON COLUMN "public"."sys_i18n_message"."zh_message" IS '中文';
COMMENT ON COLUMN "public"."sys_i18n_message"."en_message" IS '英文';
COMMENT ON TABLE "public"."sys_i18n_message" IS '国际化消息';

CREATE INDEX "sys_i18n_message_code_tenantId_idx" ON "public"."sys_i18n_message" USING btree (
  "code",
  "tenant_id"
);
COMMENT ON INDEX "public"."sys_i18n_message_code_tenantId_idx" IS '编码_租户ID_唯一索引';

ALTER TABLE "public"."sys_i18n_message" ADD CONSTRAINT "sys_i18n_message_pkey" PRIMARY KEY ("id");

INSERT INTO "public"."sys_i18n_message" VALUES (1, 1, 1, '2024-05-07 10:45:30', '2024-05-07 10:45:37', 0, 0, 0, 'sys.manage', '系统管理', 'System Management');
INSERT INTO "public"."sys_i18n_message" VALUES (2, 1, 1, '2024-05-07 10:45:30', '2024-05-07 10:45:37', 0, 0, 0, 'menu.manage', '菜单管理', 'Menu Management');
INSERT INTO "public"."sys_i18n_message" VALUES (4, 1, 1, '2024-05-07 10:45:30', '2024-05-07 10:45:37', 0, 0, 0, 'dict.manage', '字典管理', 'Dictionary Management');

-- ----------------------------
-- -------------菜单------------
-- ----------------------------
DROP TABLE IF EXISTS "public"."sys_menu";
CREATE TABLE "public"."sys_menu" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "creator" int8 NOT NULL DEFAULT 0,
  "editor" int8 NOT NULL DEFAULT 0,
  "create_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "del_flag" int2 NOT NULL DEFAULT 0,
  "version" int4 NOT NULL DEFAULT 0,
  "tenant_id" int8 NOT NULL DEFAULT 0,
  "pid" int8 NOT NULL,
  "permission" varchar(200),
  "type" int2 NOT NULL DEFAULT 0,
  "name" varchar(100) NOT NULL,
  "path" varchar(100),
  "icon" varchar(50),
  "sort" int4 NOT NULL DEFAULT 1,
  "hidden" int2 NOT NULL DEFAULT 0,
  "status" int2 NOT NULL DEFAULT 0,
  "url" varchar(400)
);
COMMENT ON COLUMN "public"."sys_menu"."id" IS 'ID';
COMMENT ON COLUMN "public"."sys_menu"."creator" IS '创建人';
COMMENT ON COLUMN "public"."sys_menu"."editor" IS '编辑人';
COMMENT ON COLUMN "public"."sys_menu"."create_time" IS '创建时间';
COMMENT ON COLUMN "public"."sys_menu"."update_time" IS '修改时间';
COMMENT ON COLUMN "public"."sys_menu"."del_flag" IS '删除标识 0未删除 1已删除';
COMMENT ON COLUMN "public"."sys_menu"."version" IS '版本号';
COMMENT ON COLUMN "public"."sys_menu"."tenant_id" IS '租户ID';
COMMENT ON COLUMN "public"."sys_menu"."pid" IS '菜单父节点ID';
COMMENT ON COLUMN "public"."sys_menu"."permission" IS '菜单权限标识';
COMMENT ON COLUMN "public"."sys_menu"."type" IS '菜单类型 0菜单 1按钮';
COMMENT ON COLUMN "public"."sys_menu"."name" IS '菜单名称';
COMMENT ON COLUMN "public"."sys_menu"."path" IS '菜单路径';
COMMENT ON COLUMN "public"."sys_menu"."icon" IS '菜单图标';
COMMENT ON COLUMN "public"."sys_menu"."sort" IS '菜单排序';
COMMENT ON COLUMN "public"."sys_menu"."status" IS '菜单状态 0启用 1停用';
COMMENT ON TABLE "public"."sys_menu" IS '菜单';

ALTER TABLE "public"."sys_menu" ADD CONSTRAINT "sys_menu_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."sys_menu" ADD CONSTRAINT "sys_menu_permission_unique" UNIQUE ("permission");

CREATE INDEX "sys_menu_type_idx" ON "public"."sys_menu" USING btree ("type");
COMMENT ON INDEX "public"."sys_menu_type_idx" IS '菜单类型_索引';

INSERT INTO "public"."sys_menu" VALUES (1, 1, 1, '2024-06-04 17:20:42', '2024-06-04 17:20:46', 0, 0, 0, 0, NULL, 0, '系统管理', '/sys', 'SettingOutlined', 90000, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (2, 1, 1, '2024-06-04 17:27:14', '2024-06-04 17:27:12', 0, 0, 0, 1, NULL, 0, '日志管理', '/sys/log', '', 1000, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (3, 1, 1, '2024-09-15 12:56:07', '2024-09-15 12:56:10', 0, 0, 0, 2, NULL, 0, '登录日志', '/sys/log/login', '', 800, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (4, 1, 1, '2024-06-04 17:27:14', '2024-06-04 17:27:12', 0, 0, 0, 3, 'sys:login-log:page', 1, '分页查询登录日志列表', NULL, '', 50, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (5, 1, 1, '2024-06-04 17:27:14', '2024-06-04 17:27:12', 0, 0, 0, 3, 'sys:login-log:export', 1, '导出全部登录日志', NULL, '', 40, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (6, 1, 1, '2024-09-17 18:36:56', '2024-09-17 18:36:59', 0, 0, 0, 2, NULL, 0, '通知日志', '/sys/log/notice', '', 700, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (7, 1, 1, '2024-09-17 18:38:24', '2024-09-17 18:38:26', 0, 0, 0, 6, 'sys:notice-log:page', 1, '分页查询通知日志列表', NULL, '', 50, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (8, 1, 1, '2024-09-17 18:39:34', '2024-09-17 18:39:37', 0, 0, 0, 6, 'sys:notice-log:export', 1, '导出全部通知日志', NULL, '', 40, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (9, 1, 1, '2025-01-11 14:10:54', '2025-01-11 14:10:57', 0, 0, 0, 3, 'sys:login-log:detail', 1, '查看登录日志', '', '', 30, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (10, 1, 1, '2025-01-11 14:13:13', '2025-01-11 14:13:16', 0, 0, 0, 6, 'sys:notice-log:detail', 1, '查看通知日志', NULL, NULL, 30, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (11, 1, 1, '2025-01-18 09:26:17', '2025-01-18 09:26:20', 0, 0, 0, 0, NULL, 0, '物联管理', '/iot', 'RobotOutlined', 80000, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (12, 1, 1, '2025-01-18 09:28:42', '2025-01-18 09:28:44', 0, 0, 0, 11, NULL, 0, '设备管理', '/iot/device', NULL, 5000, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (13, 1, 1, '2025-01-18 09:30:03', '2025-01-18 09:30:05', 0, 0, 0, 12, NULL, 0, '设备', '/iot/device/index', NULL, 100, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (14, 1, 1, '2025-01-18 09:37:53', '2025-01-18 09:37:55', 0, 0, 0, 12, NULL, 0, '物模型', '/iot/device/thingModel', NULL, 400, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (15, 1, 1, '2025-01-18 09:38:58', '2025-01-18 09:39:00', 0, 0, 0, 12, NULL, 0, '产品', '/iot/device/product', NULL, 200, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (16, 1, 1, '2025-01-18 09:39:31', '2025-01-18 09:39:34', 0, 0, 0, 12, NULL, 0, '产品类别', '/iot/device/productCategory', NULL, 300, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (17, 1, 1, '2025-01-21 05:19:17', '2025-01-21 05:19:20', 0, 0, 0, 1, NULL, 0, '权限管理', '/sys/permission', NULL, 5000, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (18, 1, 1, '2025-01-21 05:19:17', '2025-01-21 05:19:20', 0, 0, 0, 17, NULL, 0, '菜单', '/sys/permission/menu', NULL, 900, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (19, 1, 1, '2025-01-21 05:19:17', '2025-01-21 05:19:20', 0, 0, 0, 17, NULL, 0, '部门', '/sys/permission/dept', NULL, 800, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (20, 1, 1, '2025-01-21 05:19:17', '2025-01-21 05:19:20', 0, 0, 0, 17, NULL, 0, '角色', '/sys/permission/role', NULL, 700, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (21, 1, 1, '2025-01-21 05:19:17', '2025-01-21 05:19:20', 0, 0, 0, 17, NULL, 0, '用户', '/sys/permission/user', NULL, 600, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (22, 1, 1, '2025-01-21 05:19:17', '2025-01-21 05:19:20', 0, 0, 0, 1, NULL, 0, '租户管理', '/sys/tenant', NULL, 4000, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (23, 1, 1, '2025-01-21 05:19:17', '2025-01-21 05:19:20', 0, 0, 0, 22, NULL, 0, '数据源', '/sys/tenant/source', NULL, 400, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (24, 1, 1, '2025-01-21 05:19:17', '2025-01-21 05:19:20', 0, 0, 0, 22, NULL, 0, '套餐', '/sys/tenant/package', NULL, 300, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (25, 1, 1, '2025-01-21 05:19:17', '2025-01-21 05:19:20', 0, 0, 0, 22, NULL, 0, '租户', '/sys/tenant/index', NULL, 200, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (26, 1, 1, '2025-01-21 05:19:17', '2025-01-21 05:19:20', 0, 0, 0, 1, NULL, 0, '基础数据', '/sys/base', NULL, 2000, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (27, 1, 1, '2025-01-21 05:19:17', '2025-01-21 05:19:20', 0, 0, 0, 26, NULL, 0, '数据字典', '/sys/base/dict', NULL, 900, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (28, 1, 1, '2024-09-15 12:56:07', '2024-09-15 12:56:10', 0, 0, 0, 2, NULL, 0, '操作日志', '/sys/log/operate', '', 900, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (29, 1, 1, '2025-01-21 05:19:17', '2025-01-21 05:19:20', 0, 0, 0, 26, NULL, 0, '国际化', '/sys/base/i18n', NULL, 800, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (30, 1, 1, '2025-01-21 05:19:17', '2025-01-21 05:19:20', 0, 0, 0, 1, NULL, 0, '对象存储', '/sys/oss', NULL, 1000, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (31, 1, 1, '2025-01-21 05:19:17', '2025-01-21 05:19:20', 0, 0, 0, 30, NULL, 0, '对象存储配置', '/sys/oss/config', NULL, 200, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (32, 1, 1, '2025-01-21 05:19:17', '2025-01-21 05:19:20', 0, 0, 0, 30, NULL, 0, '对象存储日志', '/sys/oss/log', NULL, 100, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (33, 1, 1, '2025-01-21 05:19:17', '2025-01-21 05:19:20', 0, 0, 0, 1, NULL, 0, '集群管理', '/sys/cluster', NULL, 3000, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (34, 1, 1, '2025-01-21 05:19:17', '2025-01-29 11:20:15.092772', 0, 0, 0, 18, 'sys:menu:list-tree', 1, '查询菜单树列表', '', NULL, 50, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (35, 1, 1, '2025-01-21 05:19:17', '2025-01-29 11:20:15.092772', 0, 0, 0, 18, 'sys:menu:remove', 1, '删除菜单', '', NULL, 20, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (36, 1, 1, '2025-01-21 05:19:17', '2025-01-29 14:32:03.026995', 0, 0, 0, 18, 'sys:menu:save', 1, '新增菜单', '', NULL, 40, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (37, 1, 1, '2025-01-31 13:08:53.459704', '2025-01-31 13:08:53.459779', 0, 0, 0, 18, 'sys:menu:detail', 1, '查看菜单', NULL, NULL, 10, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (38, 1, 1, '2025-01-31 13:50:50.855744', '2025-01-31 13:50:50.856767', 0, 0, 0, 18, 'sys:menu:modify', 1, '修改菜单', NULL, NULL, 30, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (39, 1, 1, '2025-02-01 09:57:06.903239', '2025-02-01 09:57:16.643637', 0, 1, 0, 19, 'sys:dept:list-tree', 1, '查询部门树列表', NULL, NULL, 50, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (40, 1, 1, '2025-02-02 13:24:26.26515', '2025-02-02 13:24:26.26515', 0, 0, 0, 19, 'sys:dept:detail', 1, '查看部门', NULL, NULL, 10, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (41, 1, 1, '2025-02-02 13:36:39.981857', '2025-02-02 13:36:39.981857', 0, 0, 0, 19, 'sys:dept:save', 1, '新增部门', NULL, NULL, 40, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (42, 1, 1, '2025-02-02 13:37:18.191332', '2025-02-02 13:37:26.503011', 0, 1, 0, 19, 'sys:dept:modify', 1, '修改部门', NULL, NULL, 30, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (43, 1, 1, '2025-02-02 13:37:56.611868', '2025-02-02 13:38:04.173925', 0, 1, 0, 19, 'sys:dept:remove', 1, '删除部门', NULL, NULL, 20, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (44, 1, 1, '2025-02-03 10:18:36.114539', '2025-02-03 10:18:36.115538', 0, 0, 0, 20, 'sys:role:page', 1, '分页查询角色列表', NULL, NULL, 50, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (45, 1, 1, '2025-02-03 10:19:23.231544', '2025-02-03 10:19:23.232089', 0, 0, 0, 20, 'sys:role:save', 1, '新增角色', NULL, NULL, 40, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (46, 1, 1, '2025-02-03 10:20:30.753445', '2025-02-03 10:20:30.753445', 0, 0, 0, 20, 'sys:role:modify', 1, '修改角色', NULL, NULL, 30, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (47, 1, 1, '2025-02-03 10:20:55.204108', '2025-02-03 10:20:55.204108', 0, 0, 0, 20, 'sys:role:remove', 1, '删除角色', NULL, NULL, 20, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (48, 1, 1, '2025-02-03 10:21:33.499697', '2025-02-03 10:21:33.499697', 0, 0, 0, 20, 'sys:role:detail', 1, '查看角色', NULL, NULL, 10, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (49, 1, 1, '2025-02-04 13:45:32.958243', '2025-02-04 13:45:32.959244', 0, 0, 0, 21, 'sys:user:page', 1, '分页查询用户列表', NULL, NULL, 50, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (50, 1, 1, '2025-02-04 13:46:48.225873', '2025-02-04 13:46:48.226411', 0, 0, 0, 21, 'sys:user:save', 1, '新增用户', NULL, NULL, 40, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (51, 1, 1, '2025-02-04 13:47:19.981199', '2025-02-04 13:47:19.981199', 0, 0, 0, 21, 'sys:user:modify', 1, '修改用户', NULL, NULL, 30, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (52, 1, 1, '2025-02-04 13:47:47.639939', '2025-02-04 13:47:47.639939', 0, 0, 0, 21, 'sys:user:remove', 1, '删除用户', NULL, NULL, 20, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (53, 1, 1, '2025-02-04 13:48:34.215596', '2025-02-04 13:48:34.215596', 0, 0, 0, 21, 'sys:user:detail', 1, '查看用户', NULL, NULL, 10, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (54, 1, 1, '2025-03-02 17:52:49.303296', '2025-03-02 17:54:03.34208', 0, 2, 0, 28, 'sys:operate-log:page', 1, '分页查询操作日志列表', NULL, NULL, 50, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (55, 1, 1, '2025-03-02 18:06:30.782409', '2025-03-02 18:07:31.180306', 0, 1, 0, 28, 'sys:operate-log:export', 1, '导出全部操作日志', NULL, NULL, 40, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (56, 1, 1, '2025-03-02 18:09:02.472121', '2025-03-02 18:09:02.472121', 0, 0, 0, 28, 'sys:operate-log:detail', 1, '查看操作日志', NULL, NULL, 30, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (57, 1, 1, '2025-03-16 11:24:21.93876', '2025-03-16 11:24:21.93876', 0, 0, 0, 13, 'iot:device:detail', 1, '查看设备', NULL, NULL, 10, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (58, 1, 1, '2025-03-16 11:24:02.28912', '2025-03-16 11:24:02.28912', 0, 0, 0, 13, 'iot:device:remove', 1, '删除设备', NULL, NULL, 20, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (59, 1, 1, '2025-03-16 11:23:41.504246', '2025-03-16 11:23:41.504246', 0, 0, 0, 13, 'iot:device:modify', 1, '修改设备', NULL, NULL, 30, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (60, 1, 1, '2025-03-16 11:23:23.056863', '2025-03-16 11:23:23.056863', 0, 0, 0, 13, 'iot:device:save', 1, '新增设备', NULL, NULL, 40, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (61, 1, 1, '2025-03-16 11:22:56.958172', '2025-03-16 11:22:56.958172', 0, 0, 0, 13, 'iot:device:page', 1, '分页查询设备', NULL, NULL, 50, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (62, 1, 1, '2025-03-16 11:22:20.518897', '2025-03-16 11:22:20.518897', 0, 0, 0, 16, 'iot:product-category:detail', 1, '查看产品类别', NULL, NULL, 10, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (63, 1, 1, '2025-03-16 11:22:00.290849', '2025-03-16 11:22:00.290849', 0, 0, 0, 16, 'iot:product-category:remove', 1, '删除产品类别', NULL, NULL, 20, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (64, 1, 1, '2025-03-16 11:21:32.205209', '2025-03-16 11:21:32.205209', 0, 0, 0, 16, 'iot:product-category:modify', 1, '修改产品类别', NULL, NULL, 30, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (65, 1, 1, '2025-03-16 11:21:04.431009', '2025-03-16 11:21:04.431009', 0, 0, 0, 16, 'iot:product-category:save', 1, '新增产品类别', NULL, NULL, 40, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (66, 1, 1, '2025-03-16 11:20:40.603807', '2025-03-16 11:20:40.603807', 0, 0, 0, 16, 'iot:product-category:list-tree', 1, '查询产品类别树列表', NULL, NULL, 50, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (67, 1, 1, '2025-03-16 11:19:25.506634', '2025-03-16 11:19:25.506634', 0, 0, 0, 15, 'iot:product:detail', 1, '查看产品', NULL, NULL, 10, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (68, 1, 1, '2025-03-16 11:18:43.37544', '2025-03-16 11:18:43.37544', 0, 0, 0, 15, 'iot:product:remove', 1, '删除产品', NULL, NULL, 20, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (69, 1, 1, '2025-03-16 11:17:16.858243', '2025-03-16 11:18:07.952616', 0, 1, 0, 15, 'iot:product:modify', 1, '修改产品', NULL, NULL, 30, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (70, 1, 1, '2025-03-16 11:16:56.540728', '2025-03-16 11:18:02.393751', 0, 1, 0, 15, 'iot:product:save', 1, '新增产品', NULL, NULL, 40, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (71, 1, 1, '2025-03-16 11:04:36.477875', '2025-03-16 11:04:36.477875', 0, 0, 0, 15, 'iot:product:page', 1, '分页查询产品', NULL, NULL, 50, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (72, 1, 1, '2025-03-16 11:02:48.298633', '2025-03-16 11:02:48.298633', 0, 0, 0, 14, 'iot:thing-model:detail', 1, '查看物模型', NULL, NULL, 10, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (73, 1, 1, '2025-03-16 11:02:24.689321', '2025-03-16 11:02:24.689321', 0, 0, 0, 14, 'iot:thing-model:remove', 1, '删除物模型', NULL, NULL, 20, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (74, 1, 1, '2025-03-16 11:01:52.176027', '2025-03-16 11:18:56.079399', 0, 2, 0, 14, 'iot:thing-model:modify', 1, '修改物模型', NULL, NULL, 30, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (75, 1, 1, '2025-03-16 11:01:31.000074', '2025-03-16 11:01:31.000074', 0, 0, 0, 14, 'iot:thing-model:save', 1, '新增物模型', NULL, NULL, 40, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (76, 1, 1, '2025-03-16 11:00:58.755018', '2025-03-16 11:00:58.755018', 0, 0, 0, 14, 'iot:thing-model:page', 1, '分页查询物模型列表', NULL, NULL, 50, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (77, 1, 1, '2025-03-16 11:19:25.506634', '2025-03-16 11:19:25.506634', 0, 0, 0, 31, 'sys:oss:detail', 1, '查看OSS', NULL, NULL, 10, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (78, 1, 1, '2025-03-16 11:18:43.375444', '2025-03-16 11:18:43.375444', 0, 0, 0, 31, 'sys:oss:remove', 1, '删除OSS', NULL, NULL, 20, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (79, 1, 1, '2025-03-16 11:17:16.858243', '2025-03-16 11:18:07.952616', 0, 1, 0, 31, 'sys:oss:modify', 1, '修改OSS', NULL, NULL, 30, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (80, 1, 1, '2025-03-16 11:16:56.540728', '2025-03-16 11:18:02.393751', 0, 1, 0, 31, 'sys:oss:save', 1, '新增OSS', NULL, NULL, 40, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (81, 1, 1, '2025-03-16 11:04:36.477875', '2025-03-16 11:04:36.477875', 0, 0, 0, 31, 'sys:oss:page', 1, '分页查询OSS列表', NULL, NULL, 50, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (82, 1, 1, '2025-03-15 12:15:37.277552', '2025-03-15 12:15:37.278549', 0, 0, 0, 31, 'sys:oss:upload', 1, '上传文件', NULL, NULL, 5, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (83, 1, 1, '2025-07-29 21:39:07', '2025-07-29 21:39:08', 0, 0, 0, 32, 'sys:oss-log:page', 1, '分页查询OSS日志列表', NULL, NULL, 50, 0, 0, NULL);
INSERT INTO "public"."sys_menu" VALUES (84, 1, 1, '2025-07-29 21:40:53', '2025-07-29 21:40:55', 0, 0, 0, 32, 'sys:oss-log:export', 1, '导出全部OSS日志', NULL, NULL, 40, 0, 0, NULL);
-- ----------------------------
-- -------------菜单套餐------------
-- ----------------------------
DROP TABLE IF EXISTS "public"."sys_menu_package";
CREATE TABLE "public"."sys_menu_package" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "creator" int8 NOT NULL DEFAULT 0,
  "editor" int8 NOT NULL DEFAULT 0,
  "create_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "del_flag" int2 NOT NULL DEFAULT 0,
  "version" int4 NOT NULL DEFAULT 0,
  "tenant_id" int8 NOT NULL DEFAULT 0,
  "menu_id" int8 NOT NULL,
  "package_id" int8 NOT NULL
);
COMMENT ON COLUMN "public"."sys_menu_package"."id" IS 'ID';
COMMENT ON COLUMN "public"."sys_menu_package"."creator" IS '创建人';
COMMENT ON COLUMN "public"."sys_menu_package"."editor" IS '编辑人';
COMMENT ON COLUMN "public"."sys_menu_package"."create_time" IS '创建时间';
COMMENT ON COLUMN "public"."sys_menu_package"."update_time" IS '修改时间';
COMMENT ON COLUMN "public"."sys_menu_package"."del_flag" IS '删除标识 0未删除 1已删除';
COMMENT ON COLUMN "public"."sys_menu_package"."version" IS '版本号';
COMMENT ON COLUMN "public"."sys_menu_package"."tenant_id" IS '租户ID';
COMMENT ON COLUMN "public"."sys_menu_package"."menu_id" IS '菜单ID';
COMMENT ON COLUMN "public"."sys_menu_package"."package_id" IS '套餐ID';
COMMENT ON TABLE "public"."sys_menu_package" IS '菜单套餐';

ALTER TABLE "public"."sys_menu_package" ADD CONSTRAINT "sys_menu_package_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- -------------消息------------
-- ----------------------------
DROP TABLE IF EXISTS "public"."sys_message";
CREATE TABLE "public"."sys_message" (
	 "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	 "creator" int8 NOT NULL DEFAULT 0,
	 "editor" int8 NOT NULL DEFAULT 0,
	 "create_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	 "update_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	 "del_flag" int2 NOT NULL DEFAULT 0,
	 "version" int4 NOT NULL DEFAULT 0,
	 "tenant_id" int8 NOT NULL DEFAULT 0,
	 "title" varchar(400) NOT NULL,
	 "content" text NOT NULL,
	 "type" int2 NOT NULL DEFAULT 0
)
;
COMMENT ON COLUMN "public"."sys_message"."id" IS 'ID';
COMMENT ON COLUMN "public"."sys_message"."creator" IS '创建人';
COMMENT ON COLUMN "public"."sys_message"."editor" IS '编辑人';
COMMENT ON COLUMN "public"."sys_message"."create_time" IS '创建时间';
COMMENT ON COLUMN "public"."sys_message"."update_time" IS '修改时间';
COMMENT ON COLUMN "public"."sys_message"."del_flag" IS '删除标识 0未删除 1已删除';
COMMENT ON COLUMN "public"."sys_message"."version" IS '版本号';
COMMENT ON COLUMN "public"."sys_message"."tenant_id" IS '租户ID';
COMMENT ON COLUMN "public"."sys_message"."title" IS '消息标题';
COMMENT ON COLUMN "public"."sys_message"."content" IS '消息内容';
COMMENT ON COLUMN "public"."sys_message"."type" IS '消息类型 0通知 1提醒';
COMMENT ON TABLE "public"."sys_message" IS '消息';

ALTER TABLE "public"."sys_message" ADD CONSTRAINT "sys_message_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- -------------OSS------------
-- ----------------------------
DROP TABLE IF EXISTS "public"."sys_oss";
CREATE TABLE "public"."sys_oss" (
 "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
 "creator" int8 NOT NULL DEFAULT 0,
 "editor" int8 NOT NULL DEFAULT 0,
 "create_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "update_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "del_flag" int2 NOT NULL DEFAULT 0,
 "version" int4 NOT NULL DEFAULT 0,
 "tenant_id" int8 NOT NULL DEFAULT 0,
 "name" varchar(20) NOT NULL,
 "type" varchar(50) NOT NULL,
 "param" json NOT NULL,
 "status" int2 NOT NULL DEFAULT 0
);
COMMENT ON COLUMN "public"."sys_oss"."id" IS 'ID';
COMMENT ON COLUMN "public"."sys_oss"."creator" IS '创建人';
COMMENT ON COLUMN "public"."sys_oss"."editor" IS '编辑人';
COMMENT ON COLUMN "public"."sys_oss"."create_time" IS '创建时间';
COMMENT ON COLUMN "public"."sys_oss"."update_time" IS '修改时间';
COMMENT ON COLUMN "public"."sys_oss"."del_flag" IS '删除标识 0未删除 1已删除';
COMMENT ON COLUMN "public"."sys_oss"."version" IS '版本号';
COMMENT ON COLUMN "public"."sys_oss"."tenant_id" IS '租户ID';
COMMENT ON COLUMN "public"."sys_oss"."name" IS 'OSS的名称';
COMMENT ON COLUMN "public"."sys_oss"."type" IS 'OSS的类型';
COMMENT ON COLUMN "public"."sys_oss"."param" IS 'OSS的参数';
COMMENT ON COLUMN "public"."sys_oss"."status" IS 'OSS的状态 0启用 1停用';
COMMENT ON TABLE "public"."sys_oss" IS 'OSS';

ALTER TABLE "public"."sys_oss" ADD CONSTRAINT "sys_oss_pkey" PRIMARY KEY ("id");

INSERT INTO "public"."sys_oss" ("id", "creator", "editor", "create_time", "update_time", "del_flag", "version", "tenant_id", "name", "type", "param", "status") VALUES (1, 1, 1, '2025-06-21 15:41:16', '2025-06-21 15:41:19', 0, 0, 0, '本地 OSS', 'local', '{"path":"D:/laokou/tmp","directory":"/upload","domain":"http://oss.laokou.org"}', 0);
INSERT INTO "public"."sys_oss" ("id", "creator", "editor", "create_time", "update_time", "del_flag", "version", "tenant_id", "name", "type", "param", "status") VALUES (2, 1, 1, '2025-06-28 12:30:53', '2025-06-28 12:30:55', 0, 0, 0, '亚马逊S3 OSS', 'amazon_s3', '{"endpoint":"https://s3.oss-cn-shenzhen.aliyuncs.com", "region":"shenzhen", "accessKey":"LTAI5tAEkzXJzbNjvYZPRgtf", "secretKey":"exoPPyR6e4uS0sCf6IwsCJnpJ95gal", "bucketName":"laokou","pathStyleAccessEnabled":0}', 1);
INSERT INTO "public"."sys_oss" ("id", "creator", "editor", "create_time", "update_time", "del_flag", "version", "tenant_id", "name", "type", "param", "status") VALUES (3, 1, 1, '2025-06-28 12:30:53', '2025-06-28 12:30:55', 0, 0, 0, 'MinIO OSS', 'minio', '{"endpoint":"http://oss.laokou.org:9040", "region":"shenzhen", "accessKey":"asZo0GlcnCDRA0V8kqFg", "secretKey":"ebjV0cWm0MIE8JLPygWNXZuiBRxEv5o7XzvLA3yr", "bucketName":"laokou"}', 0);

-- ----------------------------
-- -------------套餐------------
-- ----------------------------
DROP TABLE IF EXISTS "public"."sys_package";
CREATE TABLE "public"."sys_package" (
 "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
 "creator" int8 NOT NULL DEFAULT 0,
 "editor" int8 NOT NULL DEFAULT 0,
 "create_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "update_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "del_flag" int2 NOT NULL DEFAULT 0,
 "version" int4 NOT NULL DEFAULT 0,
 "tenant_id" int8 NOT NULL DEFAULT 0,
 "name" varchar(100) NOT NULL
);
COMMENT ON COLUMN "public"."sys_package"."id" IS 'ID';
COMMENT ON COLUMN "public"."sys_package"."creator" IS '创建人';
COMMENT ON COLUMN "public"."sys_package"."editor" IS '编辑人';
COMMENT ON COLUMN "public"."sys_package"."create_time" IS '创建时间';
COMMENT ON COLUMN "public"."sys_package"."update_time" IS '修改时间';
COMMENT ON COLUMN "public"."sys_package"."del_flag" IS '删除标识 0未删除 1已删除';
COMMENT ON COLUMN "public"."sys_package"."version" IS '版本号';
COMMENT ON COLUMN "public"."sys_package"."tenant_id" IS '租户ID';
COMMENT ON COLUMN "public"."sys_package"."name" IS '套餐名称';
COMMENT ON TABLE "public"."sys_package" IS '套餐';

ALTER TABLE "public"."sys_package" ADD CONSTRAINT "sys_package_pkey" PRIMARY KEY ("id");

INSERT INTO "public"."sys_package" VALUES (1, 1, 1, '2023-02-09 13:38:42', '2023-09-25 17:27:57', 0, 10, 0, '普通套餐');
INSERT INTO "public"."sys_package" VALUES (2, 1, 1, '2023-02-09 16:44:04', '2023-10-27 22:07:09', 0, 18, 0, '豪华套餐');
INSERT INTO "public"."sys_package" VALUES (3, 1, 1, '2023-02-09 17:09:08', '2023-09-17 16:03:47', 0, 15, 0, '免费套餐');

-- ----------------------------
-- -------------套餐------------
-- ----------------------------
DROP TABLE IF EXISTS "public"."sys_role";
CREATE TABLE "public"."sys_role" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "creator" int8 NOT NULL DEFAULT 0,
  "editor" int8 NOT NULL DEFAULT 0,
  "create_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "del_flag" int2 NOT NULL DEFAULT 0,
  "version" int4 NOT NULL DEFAULT 0,
  "tenant_id" int8 NOT NULL DEFAULT 0,
  "name" varchar(50) NOT NULL,
  "sort" int4 NOT NULL DEFAULT 1,
  "data_scope" varchar(30) NOT NULL DEFAULT 'all'
);
COMMENT ON COLUMN "public"."sys_role"."id" IS 'ID';
COMMENT ON COLUMN "public"."sys_role"."creator" IS '创建人';
COMMENT ON COLUMN "public"."sys_role"."editor" IS '编辑人';
COMMENT ON COLUMN "public"."sys_role"."create_time" IS '创建时间';
COMMENT ON COLUMN "public"."sys_role"."update_time" IS '修改时间';
COMMENT ON COLUMN "public"."sys_role"."del_flag" IS '删除标识 0未删除 1已删除';
COMMENT ON COLUMN "public"."sys_role"."version" IS '版本号';
COMMENT ON COLUMN "public"."sys_role"."tenant_id" IS '租户ID';
COMMENT ON COLUMN "public"."sys_role"."name" IS '角色名称';
COMMENT ON COLUMN "public"."sys_role"."sort" IS '角色排序';
COMMENT ON COLUMN "public"."sys_role"."data_scope" IS '数据范围 all全部 custom自定义 dept_self仅本部门 dept部门及以下 self仅本人';
COMMENT ON TABLE "public"."sys_role" IS '角色';

ALTER TABLE "public"."sys_role" ADD CONSTRAINT "sys_role_pkey" PRIMARY KEY ("id");

INSERT INTO "public"."sys_role" VALUES (1, 1, 1, '2021-11-27 17:11:15', '2023-12-17 17:42:29', 0, 97, 0, '游客', 10, 'all');
INSERT INTO "public"."sys_role" VALUES (2, 1, 1, '2021-11-27 17:11:19', '2023-12-17 17:40:13', 0, 250, 0, '管理员', 100, 'all');
INSERT INTO "public"."sys_role" VALUES (3, 1, 1, '2022-06-12 19:38:32', '2023-12-17 17:41:35', 0, 42, 0, '测试', 50, 'all');

-- ----------------------------
-- -------------角色部门------------
-- ----------------------------
DROP TABLE IF EXISTS "public"."sys_role_dept";
CREATE TABLE "public"."sys_role_dept" (
   "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   "creator" int8 NOT NULL DEFAULT 0,
   "editor" int8 NOT NULL DEFAULT 0,
   "create_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
   "update_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
   "del_flag" int2 NOT NULL DEFAULT 0,
   "version" int4 NOT NULL DEFAULT 0,
   "tenant_id" int8 NOT NULL DEFAULT 0,
   "role_id" int8 NOT NULL,
   "dept_id" int8 NOT NULL
);
COMMENT ON COLUMN "public"."sys_role_dept"."id" IS 'ID';
COMMENT ON COLUMN "public"."sys_role_dept"."creator" IS '创建人';
COMMENT ON COLUMN "public"."sys_role_dept"."editor" IS '编辑人';
COMMENT ON COLUMN "public"."sys_role_dept"."create_time" IS '创建时间';
COMMENT ON COLUMN "public"."sys_role_dept"."update_time" IS '修改时间';
COMMENT ON COLUMN "public"."sys_role_dept"."del_flag" IS '删除标识 0未删除 1已删除';
COMMENT ON COLUMN "public"."sys_role_dept"."version" IS '版本号';
COMMENT ON COLUMN "public"."sys_role_dept"."tenant_id" IS '租户ID';
COMMENT ON COLUMN "public"."sys_role_dept"."role_id" IS '角色ID';
COMMENT ON COLUMN "public"."sys_role_dept"."dept_id" IS '部门ID';
COMMENT ON TABLE "public"."sys_role_dept" IS '角色部门';

ALTER TABLE "public"."sys_role_dept" ADD CONSTRAINT "sys_role_dept_pkey" PRIMARY KEY ("id");

CREATE UNIQUE INDEX "sys_role_dept_roleId_deptId_idx" ON "public"."sys_role_dept" USING btree (
	"role_id",
	"dept_id"
);
COMMENT ON INDEX "public"."sys_role_dept_roleId_deptId_idx" IS '角色ID_部门ID_唯一索引';

-- ----------------------------
-- -------------角色菜单------------
-- ----------------------------
DROP TABLE IF EXISTS "public"."sys_role_menu";
CREATE TABLE "public"."sys_role_menu" (
   "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   "creator" int8 NOT NULL DEFAULT 0,
   "editor" int8 NOT NULL DEFAULT 0,
   "create_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
   "update_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
   "del_flag" int4 NOT NULL DEFAULT 0,
   "version" int4 NOT NULL DEFAULT 0,
   "tenant_id" int8 NOT NULL DEFAULT 0,
   "role_id" int8 NOT NULL,
   "menu_id" int8 NOT NULL
);
COMMENT ON COLUMN "public"."sys_role_menu"."id" IS 'ID';
COMMENT ON COLUMN "public"."sys_role_menu"."creator" IS '创建人';
COMMENT ON COLUMN "public"."sys_role_menu"."editor" IS '编辑人';
COMMENT ON COLUMN "public"."sys_role_menu"."create_time" IS '创建时间';
COMMENT ON COLUMN "public"."sys_role_menu"."update_time" IS '修改时间';
COMMENT ON COLUMN "public"."sys_role_menu"."del_flag" IS '删除标识 0未删除 1已删除';
COMMENT ON COLUMN "public"."sys_role_menu"."version" IS '版本号';
COMMENT ON COLUMN "public"."sys_role_menu"."tenant_id" IS '租户ID';
COMMENT ON COLUMN "public"."sys_role_menu"."role_id" IS '角色ID';
COMMENT ON COLUMN "public"."sys_role_menu"."menu_id" IS '菜单ID';
COMMENT ON TABLE "public"."sys_role_menu" IS '角色菜单';

ALTER TABLE "public"."sys_role_menu" ADD CONSTRAINT "sys_role_menu_pkey" PRIMARY KEY ("id");

CREATE UNIQUE INDEX "sys_role_menu_roleId_menuId_idx" ON "public"."sys_role_menu" USING btree (
	"role_id",
	"menu_id"
);
COMMENT ON INDEX "public"."sys_role_menu_roleId_menuId_idx" IS '角色ID_菜单ID_唯一索引';

-- ----------------------------
-- -------------数据源------------
-- ----------------------------
DROP TABLE IF EXISTS "public"."sys_source";
CREATE TABLE "public"."sys_source" (
	"id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"creator" int8 NOT NULL DEFAULT 0,
	"editor" int8 NOT NULL DEFAULT 0,
	"create_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"update_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"del_flag" int2 NOT NULL DEFAULT 0,
	"version" int4 NOT NULL DEFAULT 0,
	"tenant_id" int8 NOT NULL DEFAULT 0,
	"name" varchar(50) NOT NULL,
	"driver_class_name" varchar(100) NOT NULL,
	"url" varchar(500) NOT NULL,
	"username" varchar(100) NOT NULL,
	"password" varchar(100) NOT NULL
);
COMMENT ON COLUMN "public"."sys_source"."id" IS 'ID';
COMMENT ON COLUMN "public"."sys_source"."creator" IS '创建人';
COMMENT ON COLUMN "public"."sys_source"."editor" IS '编辑人';
COMMENT ON COLUMN "public"."sys_source"."create_time" IS '创建时间';
COMMENT ON COLUMN "public"."sys_source"."update_time" IS '修改时间';
COMMENT ON COLUMN "public"."sys_source"."del_flag" IS '删除标识 0未删除 1已删除';
COMMENT ON COLUMN "public"."sys_source"."version" IS '版本号';
COMMENT ON COLUMN "public"."sys_source"."tenant_id" IS '租户ID';
COMMENT ON COLUMN "public"."sys_source"."name" IS '数据源名称';
COMMENT ON COLUMN "public"."sys_source"."driver_class_name" IS '数据源的驱动名称';
COMMENT ON COLUMN "public"."sys_source"."url" IS '数据源的连接信息';
COMMENT ON COLUMN "public"."sys_source"."username" IS '数据源的用户名';
COMMENT ON COLUMN "public"."sys_source"."password" IS '数据源的密码';
COMMENT ON TABLE "public"."sys_source" IS '数据源';

ALTER TABLE "public"."sys_source" ADD CONSTRAINT "sys_source_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- -------------租户------------
-- ----------------------------
DROP TABLE IF EXISTS "public"."sys_tenant";
CREATE TABLE "public"."sys_tenant" (
	"id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"creator" int8 NOT NULL DEFAULT 0,
	"editor" int8 NOT NULL DEFAULT 0,
	"create_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"update_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"del_flag" int2 NOT NULL DEFAULT 0,
	"version" int4 NOT NULL DEFAULT 0,
	"tenant_id" int8 NOT NULL DEFAULT 0,
	"name" varchar(100) NOT NULL,
	"code" varchar(30) NOT NULL,
	"source_id" int8 NOT NULL,
	"package_id" int8 NOT NULL
);
COMMENT ON COLUMN "public"."sys_tenant"."id" IS 'ID';
COMMENT ON COLUMN "public"."sys_tenant"."creator" IS '创建人';
COMMENT ON COLUMN "public"."sys_tenant"."editor" IS '编辑人';
COMMENT ON COLUMN "public"."sys_tenant"."create_time" IS '创建时间';
COMMENT ON COLUMN "public"."sys_tenant"."update_time" IS '修改时间';
COMMENT ON COLUMN "public"."sys_tenant"."del_flag" IS '删除标识 0未删除 1已删除';
COMMENT ON COLUMN "public"."sys_tenant"."version" IS '版本号';
COMMENT ON COLUMN "public"."sys_tenant"."tenant_id" IS '租户ID';
COMMENT ON COLUMN "public"."sys_tenant"."name" IS '租户名称';
COMMENT ON COLUMN "public"."sys_tenant"."code" IS '租户编码';
COMMENT ON COLUMN "public"."sys_tenant"."source_id" IS '数据源ID';
COMMENT ON COLUMN "public"."sys_tenant"."package_id" IS '套餐ID';
COMMENT ON TABLE "public"."sys_tenant" IS '租户';

ALTER TABLE "public"."sys_tenant" ADD CONSTRAINT "sys_tenant_pkey" PRIMARY KEY ("id");

INSERT INTO "public"."sys_tenant" VALUES (1, 1, 1, '2023-09-17 15:42:27', '2023-12-17 18:37:13', 0, 1, 0, '阿里集团', 'tenant1', 1, 2);

-- ----------------------------
-- -------------用户------------
-- ----------------------------
DROP TABLE IF EXISTS "public"."sys_user";
CREATE TABLE "public"."sys_user" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "creator" int8 NOT NULL DEFAULT 0,
  "editor" int8 NOT NULL DEFAULT 0,
  "create_time" timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "del_flag" int2 NOT NULL DEFAULT 0,
  "version" int4 NOT NULL DEFAULT 0,
  "tenant_id" int8 NOT NULL DEFAULT 0,
  "password" varchar(100) NOT NULL,
  "super_admin" int2 NOT NULL DEFAULT 0,
  "mail" varchar(200),
  "mobile" varchar(60),
  "status" int2 NOT NULL DEFAULT 0,
  "avatar" int8 NOT NULL DEFAULT 1,
  "username_phrase" varchar(1600),
  "mail_phrase" varchar(1600),
  "mobile_phrase" varchar(150),
  "username" varchar(200) NOT NULL
)
;
COMMENT ON COLUMN "public"."sys_user"."id" IS 'ID';
COMMENT ON COLUMN "public"."sys_user"."creator" IS '创建人';
COMMENT ON COLUMN "public"."sys_user"."editor" IS '编辑人';
COMMENT ON COLUMN "public"."sys_user"."create_time" IS '创建时间';
COMMENT ON COLUMN "public"."sys_user"."update_time" IS '修改时间';
COMMENT ON COLUMN "public"."sys_user"."del_flag" IS '删除标识 0未删除 1已删除';
COMMENT ON COLUMN "public"."sys_user"."version" IS '版本号';
COMMENT ON COLUMN "public"."sys_user"."tenant_id" IS '租户ID';
COMMENT ON COLUMN "public"."sys_user"."username" IS '用户名';
COMMENT ON COLUMN "public"."sys_user"."password" IS '用户密码';
COMMENT ON COLUMN "public"."sys_user"."super_admin" IS '超级管理员标识 0否 1是';
COMMENT ON COLUMN "public"."sys_user"."mail" IS '用户邮箱';
COMMENT ON COLUMN "public"."sys_user"."mobile" IS '用户手机号';
COMMENT ON COLUMN "public"."sys_user"."status" IS '用户状态 0启用 1禁用';
COMMENT ON COLUMN "public"."sys_user"."avatar" IS '用户头像';
COMMENT ON COLUMN "public"."sys_user"."username_phrase" IS '用户名短语';
COMMENT ON COLUMN "public"."sys_user"."mail_phrase" IS '用户邮箱短语';
COMMENT ON COLUMN "public"."sys_user"."mobile_phrase" IS '用户手机号短语';
COMMENT ON TABLE "public"."sys_user" IS '用户';

ALTER TABLE "public"."sys_user" ADD CONSTRAINT "sys_user_pkey" PRIMARY KEY ("id");

CREATE UNIQUE INDEX "sys_user_mail_tenantId_idx" ON "public"."sys_user" USING btree (
	"mail",
	"tenant_id"
);
COMMENT ON INDEX "public"."sys_user_mail_tenantId_idx" IS '邮箱_租户ID_唯一索引';

CREATE UNIQUE INDEX "sys_user_mobile_tenantId_idx" ON "public"."sys_user" USING btree (
	"mobile",
	"tenant_id"
);
COMMENT ON INDEX "public"."sys_user_mobile_tenantId_idx" IS '手机号_租户ID_唯一索引';

CREATE UNIQUE INDEX "sys_user_username_tenantId_idx" ON "public"."sys_user" USING btree (
	"username",
	"tenant_id"
);
COMMENT ON INDEX "public"."sys_user_username_tenantId_idx" IS '用户名_租户ID_唯一索引';

INSERT INTO "public"."sys_user" VALUES (1, 1, 1, '2022-01-01 20:13:11+08', '2024-04-29 23:52:52+08', 0, 0, 0, '{bcrypt}$2a$10$bGXM7u58FPMDanMyqvZ7Reb9sqJiUTCdAcb1wN5IIkFa8nYOMOioK', 1, 'Ylh4QTF0YmdEWWJR2TEQZjlR4rzAz/73MsL8gxlNSv+/j3L7Sxne4hFAP+W9', 'Ylh4QTF0YmdEWWJR2j0YYjxS577BzIgIGdpZbU2I7EIUTVaxqvWu', 0, 1, 'Ylh4QTF0YmdEWWJRimFMPAPt8S6U+J8eEhIZiErF69o=~Ylh4QTF0YmdEWWJRj2hIO/7mcHvbRltmR9cojv2C2jE=', 'Ylh4QTF0YmdEWWJR2TEQZt/I7tdiOALwVrZXFxK5boI=~Ylh4QTF0YmdEWWJR3zQSZDEzo/mQ2Kt2ooeStwwy1DM=~Ylh4QTF0YmdEWWJR2jYQYvkuHP0mNYNzkmUPAkpRnNs=~Ylh4QTF0YmdEWWJR2DQWY04zb3FkQTCmuPFi97WrI08=~Ylh4QTF0YmdEWWJR2jIXZToqPakPCzCwmjz4XLwksmM=~Ylh4QTF0YmdEWWJR3DMRYRY/bEOz79QYxdiB5xtGMoU=~Ylh4QTF0YmdEWWJR3TUVYYBJ7iU6aLpsTeXBwNhb1lk=~Ylh4QTF0YmdEWWJR2zEVFRAKn1yHzG9spDDE8afQ1Ls=~Ylh4QTF0YmdEWWJR3zFhJLv17Ndjz3ymZABhpoKJPCE=~Ylh4QTF0YmdEWWJR30VQJOy8KF8pYc2r4yJkfOWIWnw=~Ylh4QTF0YmdEWWJRq3RQe8Vs9XmHQG6AkHOCtSwt6cA=~Ylh4QTF0YmdEWWJRmnQPNipHlgS+8wcVPz+EC5gdeeM=~Ylh4QTF0YmdEWWJRmitCOoJ+zG0CpSympji+U7NWxUw=~Ylh4QTF0YmdEWWJRxWZOOE8J8sq9k7iJhdxbniMpw9I=', 'Ylh4QTF0YmdEWWJR2j0YOQJF4W0Ofxd/k/LFC4GzoQ==~Ylh4QTF0YmdEWWJR3DEVZk3r4C1hv2eOukkPSzTOffA=~Ylh4QTF0YmdEWWJR2TAWY8HwM9jwPxZFMFE0pFibp9k=', 'Ylh4QTF0YmdEWWJRimFMPGaJmldyuWIb9BNmUN1ULMI7');
INSERT INTO "public"."sys_user" VALUES (5, 1, 1, '2022-06-16 00:48:28+08', '2024-04-29 23:52:52+08', 0, 1, 0, '{bcrypt}$2a$10$RX9zW6rUMbGjybnlW77FWezhgbH0ZsFinGtKaoOsbovkEgij7kzNC', 0, NULL, NULL, 0, 1, 'Ylh4QTF0YmdEWWJRh2ROPuSvWyrTvf2MaPrw8GpjTBM=~Ylh4QTF0YmdEWWJRimpKYMTCzQiEJvp5Ar80c6jh1Wg=', NULL, NULL, 'Ylh4QTF0YmdEWWJRh2ROPj1LULONpfXTh6mWUOIX9SFO');
INSERT INTO "public"."sys_user" VALUES (2, 1, 1, '2023-03-09 13:52:04+08', '2024-04-29 23:52:52+08', 0, 1, 0, '{bcrypt}$2a$10$J0DMR5098R33H6F.s5H/deeMLyo/j4yyzZgAn6gkyC0j537G7veKG', 0, NULL, NULL, 0, 1, 'Ylh4QTF0YmdEWWJRn2BSIeyAJZxxvGa9Rma06h4QOnQ=', NULL, NULL, 'Ylh4QTF0YmdEWWJRn2BSIeyAJZxxvGa9Rma06h4QOnQ=');
INSERT INTO "public"."sys_user" VALUES (3, 1, 1, '2022-01-31 11:29:35+08', '2024-04-29 23:52:52+08', 0, 0, 0, '{bcrypt}$2a$10$ysAmruc249SiAUpIqQzrpeM8wcdpgIJ6nEdtsXQnDrBgvLZkt7tJ6', 0, NULL, NULL, 0, 1, 'Ylh4QTF0YmdEWWJRgGpUJiNPIjdI2XP1ZWEFUmonJDs=~Ylh4QTF0YmdEWWJRhHBSPSMrKeV2KZK27WU4BJGux6Q=~Ylh4QTF0YmdEWWJRnnZJYJsjtsAm+CPpK1W9SDWk46s=', NULL, NULL, 'Ylh4QTF0YmdEWWJRgGpUJmBT8fGpMah42bhHMZ9Aapk+jQ==');
INSERT INTO "public"."sys_user" VALUES (4, 1, 1, '2022-06-16 00:33:39+08', '2024-04-29 23:52:52+08', 0, 0, 0, '{bcrypt}$2a$10$Wac.3sTE4A4pi/Zy6B/HWOstwLFjOH9g8Qrf4gHiBLa/avKAVcwpG', 0, NULL, NULL, 0, 1, 'Ylh4QTF0YmdEWWJRnHBMPWPaKJGlV652rAqtN8Q9MYg=~Ylh4QTF0YmdEWWJRnmhJYJS/YXrtS/sF9dNgHyAmxEI=', NULL, NULL, 'Ylh4QTF0YmdEWWJRnHBMPT3MJcA20x+AfW1mDSW5q1zV');

-- ----------------------------
-- -------------用户部门------------
-- ----------------------------
DROP TABLE IF EXISTS "public"."sys_user_dept";
CREATE TABLE "public"."sys_user_dept" (
   "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   "creator" int8 NOT NULL DEFAULT 0,
   "editor" int8 NOT NULL DEFAULT 0,
   "create_time" timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
   "update_time" timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
   "del_flag" int2 NOT NULL DEFAULT 0,
   "version" int4 NOT NULL DEFAULT 0,
   "tenant_id" int8 NOT NULL DEFAULT 0,
   "user_id" int8 NOT NULL,
   "dept_id" int8 NOT NULL
);
COMMENT ON COLUMN "public"."sys_user_dept"."id" IS 'ID';
COMMENT ON COLUMN "public"."sys_user_dept"."creator" IS '创建人';
COMMENT ON COLUMN "public"."sys_user_dept"."editor" IS '编辑人';
COMMENT ON COLUMN "public"."sys_user_dept"."create_time" IS '创建时间';
COMMENT ON COLUMN "public"."sys_user_dept"."update_time" IS '修改时间';
COMMENT ON COLUMN "public"."sys_user_dept"."del_flag" IS '删除标识 0未删除 1已删除';
COMMENT ON COLUMN "public"."sys_user_dept"."version" IS '版本号';
COMMENT ON COLUMN "public"."sys_user_dept"."tenant_id" IS '租户ID';
COMMENT ON COLUMN "public"."sys_user_dept"."user_id" IS '用户ID';
COMMENT ON COLUMN "public"."sys_user_dept"."dept_id" IS '部门ID';
COMMENT ON TABLE "public"."sys_user_dept" IS '用户部门';

ALTER TABLE "public"."sys_user_dept" ADD CONSTRAINT "sys_user_dept_pkey" PRIMARY KEY ("id");

CREATE UNIQUE INDEX "sys_user_dept_userId_deptId_idx" ON "public"."sys_user_dept" USING btree (
	"user_id",
	"dept_id"
);
COMMENT ON INDEX "public"."sys_user_dept_userId_deptId_idx" IS '用户ID_部门ID_唯一索引';

-- ----------------------------
-- -------------用户消息------------
-- ----------------------------
DROP TABLE IF EXISTS "public"."sys_user_message";
CREATE TABLE "public"."sys_user_message" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "creator" int8 NOT NULL DEFAULT 0,
  "editor" int8 NOT NULL DEFAULT 0,
  "create_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "del_flag" int2 NOT NULL DEFAULT 0,
  "version" int4 NOT NULL DEFAULT 0,
  "tenant_id" int8 NOT NULL DEFAULT 0,
  "user_id" int8 NOT NULL,
  "message_id" int8 NOT NULL,
  "read_flag" int2 NOT NULL DEFAULT 0
);
COMMENT ON COLUMN "public"."sys_user_message"."id" IS 'ID';
COMMENT ON COLUMN "public"."sys_user_message"."creator" IS '创建人';
COMMENT ON COLUMN "public"."sys_user_message"."editor" IS '编辑人';
COMMENT ON COLUMN "public"."sys_user_message"."create_time" IS '创建时间';
COMMENT ON COLUMN "public"."sys_user_message"."update_time" IS '修改时间';
COMMENT ON COLUMN "public"."sys_user_message"."del_flag" IS '删除标识 0未删除 1已删除';
COMMENT ON COLUMN "public"."sys_user_message"."version" IS '版本号';
COMMENT ON COLUMN "public"."sys_user_message"."tenant_id" IS '租户ID';
COMMENT ON COLUMN "public"."sys_user_message"."user_id" IS '用户ID';
COMMENT ON COLUMN "public"."sys_user_message"."message_id" IS '消息ID';
COMMENT ON COLUMN "public"."sys_user_message"."read_flag" IS '消息已读标识 0未读 1已读';
COMMENT ON TABLE "public"."sys_user_message" IS '用户消息';

ALTER TABLE "public"."sys_user_message" ADD CONSTRAINT "sys_user_message_pkey" PRIMARY KEY ("id");

CREATE INDEX "sys_user_message_readFlag_userId_idx" ON "public"."sys_user_message" USING btree (
	"read_flag",
	"user_id"
);
COMMENT ON INDEX "public"."sys_user_message_readFlag_userId_idx" IS '消息已读标识_用户ID_索引';

-- ----------------------------
-- -------------用户角色------------
-- ----------------------------
DROP TABLE IF EXISTS "public"."sys_user_role";
CREATE TABLE "public"."sys_user_role" (
   "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   "creator" int8 NOT NULL DEFAULT 0,
   "editor" int8 NOT NULL DEFAULT 0,
   "create_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
   "update_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
   "del_flag" int2 NOT NULL DEFAULT 0,
   "version" int4 NOT NULL DEFAULT 0,
   "tenant_id" int8 NOT NULL DEFAULT 0,
   "user_id" int8 NOT NULL,
   "role_id" int8 NOT NULL
);
COMMENT ON COLUMN "public"."sys_user_role"."id" IS 'ID';
COMMENT ON COLUMN "public"."sys_user_role"."creator" IS '创建人';
COMMENT ON COLUMN "public"."sys_user_role"."editor" IS '编辑人';
COMMENT ON COLUMN "public"."sys_user_role"."create_time" IS '创建时间';
COMMENT ON COLUMN "public"."sys_user_role"."update_time" IS '修改时间';
COMMENT ON COLUMN "public"."sys_user_role"."del_flag" IS '删除标识 0未删除 1已删除';
COMMENT ON COLUMN "public"."sys_user_role"."version" IS '版本号';
COMMENT ON COLUMN "public"."sys_user_role"."tenant_id" IS '租户ID';
COMMENT ON COLUMN "public"."sys_user_role"."user_id" IS '用户ID';
COMMENT ON COLUMN "public"."sys_user_role"."role_id" IS '角色ID';
COMMENT ON TABLE "public"."sys_user_role" IS '用户角色';

ALTER TABLE "public"."sys_user_role" ADD CONSTRAINT "sys_user_role_pkey" PRIMARY KEY ("id");

CREATE UNIQUE INDEX "sys_user_role_userId_roleId_idx" ON "public"."sys_user_role" USING btree (
	"user_id",
	"role_id"
);
COMMENT ON INDEX "public"."sys_user_role_userId_roleId_idx" IS '用户ID_角色ID_唯一索引';

DROP TABLE IF EXISTS "public"."oauth2_authorization_consent";
CREATE TABLE "public"."oauth2_authorization_consent" (
	 "registered_client_id" varchar(100) NOT NULL,
	 "principal_name" varchar(200) NOT NULL,
	 "authorities" varchar(1000) NOT NULL
);

ALTER TABLE "public"."oauth2_authorization_consent" ADD CONSTRAINT "oauth2_authorization_consent_pkey" PRIMARY KEY ("registered_client_id", "principal_name");

DROP TABLE IF EXISTS "public"."oauth2_registered_client";
CREATE TABLE "public"."oauth2_registered_client" (
	"id" varchar(100) NOT NULL,
	"client_id" varchar(100)  NOT NULL,
	"client_id_issued_at" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"client_secret" varchar(200) ,
	"client_secret_expires_at" timestamp(6),
	"client_name" varchar(200)  NOT NULL,
	"client_authentication_methods" varchar(1000)  NOT NULL,
	"authorization_grant_types" varchar(1000)  NOT NULL,
	"redirect_uris" varchar(1000) ,
	"post_logout_redirect_uris" varchar(1000) ,
	"scopes" varchar(1000) NOT NULL,
	"client_settings" varchar(2000) NOT NULL,
	"token_settings" varchar(2000) NOT NULL
);

ALTER TABLE "public"."oauth2_registered_client" ADD CONSTRAINT "oauth2_registered_client_pkey" PRIMARY KEY ("id");
