# jasypt
jasypt:
  encryptor:
    password: ${SECRET_KEY:laokou}
server:
  port: ${SERVER_PORT:10005}
  compression:
    enabled: true
  ssl:
    # 开启证书
    enabled: false
    # 证书位置
    key-store: classpath:scg-keystore.p12
    # 证书别名
    key-alias: ${spring.application.name}
    # 秘钥类型
    key-store-type: PKCS12
    # 证书密码
    key-store-password: laokou
  http2:
    enabled: false
  shutdown: graceful
  servlet:
    context-path: /api
  tomcat:
    threads:
      # 工作线程池的最大线程数
      max: 500
      # 工作线程池的最小备用线程数
      min-spare: 50
    # 最大连接数
    max-connections: 10000
    # 当所有工作线程都在忙时，允许等待处理的最大连接数
    accept-count: 200
    # URI编码
    uri-encoding: UTF-8
    # 连接超时时间
    connection-timeout: 60s
spring:
  application:
    name: ${SERVICE_ID:laokou-iot}
  profiles:
    active: @PROFILE-ACTIVE@
  # 开启虚拟线程
  threads:
    virtual:
      enabled: true
  lifecycle:
    timeout-per-shutdown-phase: "2m"
  websocket-server:
    port: 1001
    service-id: ${spring.application.name}-websocket
    key-cert-private-key-password: laokou
  # security
  security:
    oauth2:
      resource-server:
        enabled: true
        request-matcher:
          ignore-patterns:
            GET:
              - /v3/api-docs/**=laokou-iot
              - /actuator/**=laokou-iot
              - /scalar/**=laokou-iot
              - /favicon.svg=laokou-iot
  cloud:
    # Loadbalancer配置
    loadbalancer:
      nacos:
        enabled: true
    inetutils:
      ignored-interfaces:
        - docker0
        - veth.*

scalar:
  enabled: true
springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: true
    path: /v3/api-docs
    version: openapi_3_1

# mybatis-plus
mybatis-plus:
  # 全局处理
  global-config:
    db-config:
      column-format: "\"%s\""
  tenant:
    enabled: true
  sql-monitor:
    enabled: true
    interval: 0
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl

# actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  tracing:
    export:
      enabled: true
    propagation:
      type: w3c
    # 采样率 => 100%
    sampling:
      probability: 1
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://otel-collector:4317/v1/traces
          compression: gzip
          timeout: 10s
          transport: grpc

logging:
  config: classpath:log4j2-@PROFILE-ACTIVE@.xml

system-settings:
  node-id: 1
  app-mode: microservice
