#/**
# * Copyright (c) 2022 KCloud-Platform-Alibaba Authors. All Rights Reserved.
# * <p>
# * Licensed under the Apache License, Version 2.0 (the "License");
# * you may not use this file except in compliance with the License.
# * You may obtain a copy of the License at
# * <p>
# *   http://www.apache.org/licenses/LICENSE-2.0
# * <p>
# * Unless required by applicable law or agreed to in writing, software
# * distributed under the License is distributed on an "AS IS" BASIS,
# * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# * See the License for the specific language governing permissions and
# * limitations under the License.
# */
# 账号密码登录
POST http://127.0.0.1:1111/oauth2/token
Authorization: Basic YXV0aC1jbGllbnQ6c2VjcmV0
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="grant_type"

password
--WebAppBoundary
Content-Disposition: form-data; name="username"

admin
--WebAppBoundary
Content-Disposition: form-data; name="password"

admin123
--WebAppBoundary
Content-Disposition: form-data; name="uuid"

1111
--WebAppBoundary
Content-Disposition: form-data; name="captcha"

bdbc
--WebAppBoundary
Content-Disposition: form-data; name="tenantId"

0
--WebAppBoundary

#########

# 手机登录
# 手机号测试代码地址：https://github.com/KouShenhai/KCloud-Platform-Alibaba/blob/master/laokou-service/laokou-module/laokou-sms/laokou-sms-server/src/test/java/org/laokou/sms/server/SmsTest.java
POST http://127.0.0.1:1111/oauth2/token
Authorization: Basic YXV0aC1jbGllbnQ6c2VjcmV0
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="grant_type"

sms
--WebAppBoundary
Content-Disposition: form-data; name="mobile"

你的手机号
--WebAppBoundary
Content-Disposition: form-data; name="code"

手机号验证码
--WebAppBoundary
Content-Disposition: form-data; name="tenantId"

0
--WebAppBoundary


#########

# 邮箱登录
# 邮箱测试代码地址：https://github.com/KouShenhai/KCloud-Platform-Alibaba/blob/master/laokou-service/laokou-module/laokou-mail/laokou-mail-server/src/test/java/org/laokou/mail/server/MailTest.java
POST http://127.0.0.1:1111/oauth2/token
Authorization: Basic YXV0aC1jbGllbnQ6c2VjcmV0
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="grant_type"

mail
--WebAppBoundary
Content-Disposition: form-data; name="mail"

你的邮箱
--WebAppBoundary
Content-Disposition: form-data; name="code"

邮箱验证码
--WebAppBoundary
Content-Disposition: form-data; name="tenantId"

0
--WebAppBoundary

#########

# 授权码登录(默认数据库)
# 账号/密码：admin/admin123
# 获取code地址：http://127.0.0.1:1111/oauth2/authorize?client_id=auth-client&client_secret=secret&response_type=code&scope=password&redirect_uri=https://www.baidu.com
POST http://127.0.0.1:1111/oauth2/token
Authorization: Basic YXV0aC1jbGllbnQ6c2VjcmV0
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="grant_type"

authorization_code
--WebAppBoundary
Content-Disposition: form-data; name="code"

K7gA8Wm6CKKZPBf-Xhhl-nM5PS_3vi8htN7DEeZrTnqTHCx0LH7Yx3hHVLBh5x0MkyxVpDGsGabb9OOM6V1-PfI4V6BOlu9q59IK8Bmmvap8Fbgw7rvLCsJoCurG1rz_
--WebAppBoundary
Content-Disposition: form-data; name="redirect_uri"

https://www.baidu.com
--WebAppBoundary