# 账号密码登录
POST http://localhost:1111/oauth2/token
Authorization: Basic YXV0aC1jbGllbnQ6c2VjcmV0
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="grant_type"

password
--WebAppBoundary
Content-Disposition: form-data; name="username"

admin
--WebAppBoundary
Content-Disposition: form-data; name="password"

admin123
--WebAppBoundary
Content-Disposition: form-data; name="uuid"

1111
--WebAppBoundary
Content-Disposition: form-data; name="captcha"

bdbc
--WebAppBoundary

#########

# 手机登录
POST http://localhost:1111/oauth2/token
Authorization: Basic YXV0aC1jbGllbnQ6c2VjcmV0
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="grant_type"

sms
--WebAppBoundary
Content-Disposition: form-data; name="phone"

13487567891
--WebAppBoundary
Content-Disposition: form-data; name="code"

1234
--WebAppBoundary