import type { Metadata } from "next";
import React from 'react';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { ReduxProvider } from '@/app/_client/redux/store';
import { ErrorBoundary } from "next/dist/client/components/error-boundary";
import { Layout } from "antd";

export const metadata: Metadata = {
  title: "寇云",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};
const RootLayout = ({ children }: React.PropsWithChildren) => (
  <html lang="en">
    <body style={{ margin: '0 0 0 0' }}>
      <ReduxProvider>
        <AntdRegistry>
          {children}
        </AntdRegistry>
      </ReduxProvider>
    </body>
  </html>
);
export default RootLayout;


