server:
  port: ${SERVER_PORT:9998}
  ssl:
    # 开启证书
    enabled: @SSL-ENABLED@
    # 证书位置
    key-store: classpath:scg-keystore.p12
    # 证书别名
    key-alias: ${spring.application.name}
    # 秘钥类型
    key-store-type: PKCS12
    # 证书密码
    key-store-password: laokou
  http2:
    enabled: @SSL-ENABLED@
  shutdown: graceful
  forward-headers-strategy: native

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  tracing:
    enabled: true
    propagation:
      type: w3c
    # 采样率 => 100%
    sampling:
      probability: 1
  otlp:
    tracing:
      endpoint: http://otel-collector:4317/v1/traces
      compression: gzip
      timeout: 10s
      transport: grpc
    metrics:
      export:
        enabled: false
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  config: classpath:log4j2-@PROFILE-ACTIVE@.xml

spring:
  application:
    name: ${SERVICE_ID:laokou-udp}
  profiles:
    active: @PROFILE-ACTIVE@
  threads:
    virtual:
      enabled: true
  udp-server:
    ports:
      - 4880
      - 4881
      - 4882
      - 4883
      - 4884
      - 4885
      - 4886
      - 4887
      - 4888
      - 4889
      - 4890
      - 4891
      - 4892
      - 4893
      - 4894
      - 4895
      - 4896
      - 4897
      - 4898
      - 4899
      - 4900
      - 4901
      - 4902
      - 4903
      - 4904
      - 4905
      - 4906
      - 4907
      - 4908
      - 4909
      - 4910
      - 4911
      - 4912
      - 4913
      - 4914
      - 4915
      - 4916
      - 4917
      - 4918
      - 4919
      - 4920
      - 4921
      - 4922
      - 4923
      - 4924
      - 4925
      - 4926
      - 4927
      - 4928
      - 4929
      - 4930
      - 4931
      - 4932
      - 4933
      - 4934
      - 4935
      - 4936
      - 4937
      - 4938
      - 4939
      - 4940
      - 4941
      - 4942
      - 4943
      - 4944
      - 4945
      - 4946
      - 4947
      - 4948
      - 4949
      - 4950
      - 4951
      - 4952
      - 4953
      - 4954
      - 4955
      - 4956
      - 4957
      - 4958
      - 4959
      - 4960
      - 4961
      - 4962
      - 4963
      - 4964
      - 4965
      - 4966
      - 4967
      - 4968
      - 4969
      - 4970
      - 4971
      - 4972
      - 4973
      - 4974
      - 4975
      - 4976
      - 4977
      - 4978
      - 4979
      - 4980
      - 4981
      - 4982
      - 4983
      - 4984
      - 4985
      - 4986
      - 4987
      - 4988
      - 4989
      - 4990
      - 4991
      - 4992
      - 4993
      - 4994
      - 4995
      - 4996
      - 4997
      - 4998
      - 4999
      - 5000
